// BPMN 语义来源：src/care/http/watering-advice-route.ts、src/care/application/*、src/care/http/long-term-care-routes.ts、
// src/identity/http/*、src/user-plant/http/*、src/user-plant/application/*、src/user-plant/domain/guest-claim-lease.ts。
const err = (prefix, code, name) => ({ id: `${prefix}_error_${code}_${name.replace(/[^A-Za-z0-9]/g, '_').toLowerCase()}`.slice(0, 80), code: String(code), name })
const node = (id, type, name, lane, col, row = 0, extra = {}) => ({ id, type, name, lane, col, row, ...extra })
const end = (prefix, id, name, lane, col, row, code, errName, doc) => node(id, 'endEvent', name, lane, col, row, { error: err(prefix, code, errName), doc })
const flow = (id, from, to, name) => ({ id, from, to, ...(name ? { name } : {}) })

// ---------------------------------------------------------------- ① 浇水建议请求
const W = 'wa'
export const wateringAdvice = {
  id: 'watering_advice_request', processId: 'watering_advice_request_process', processName: '浇水建议请求（watering-advice/v1）',
  participantName: 'POST /api/v2/care/watering-advice',
  documentation: '反映 createWateringAdviceRouteHandler 固定请求链：限制 → 认证 → 主体 → DTO → 归属前置 → 策略/基线/辐射 → 组装（纯计算）→ 幂等事务 → 白名单响应。外部读取全部在事务前完成。',
  lanes: [
    { id: 'wa_lane_user', name: '用户 / 小程序' },
    { id: 'wa_lane_identity', name: 'identity 域' },
    { id: 'wa_lane_care', name: 'care 云函数' },
    { id: 'wa_lane_user_plant', name: 'user-plant 域' },
    { id: 'wa_lane_knowledge', name: 'plant-knowledge 域' },
    { id: 'wa_lane_provider', name: '外部 Provider' },
  ],
  nodes: [
    node('wa_start', 'startEvent', '发起浇水建议', 'wa_lane_user', 0),
    node('wa_limits', 'task', '请求限制：JSON 媒体类型与 1MB 上限', 'wa_lane_care', 1, 0, { doc: 'readRestrictedRequest：媒体类型 → 415，超过 1,048,576 字节 → 413；先于认证。' }),
    node('wa_gw_limits', 'exclusiveGateway', '请求可接收？', 'wa_lane_care', 2),
    end(W, 'wa_end_413_415', '415 / 413 拒绝', 'wa_lane_care', 2, -1, 415, 'UNSUPPORTED_MEDIA_TYPE_OR_PAYLOAD_TOO_LARGE'),
    node('wa_principal', 'task', '解析 Bearer 主体（游客或登录用户）', 'wa_lane_identity', 3, 0, { doc: 'guest_or_authenticated：resolvePrincipal + 合同校验 + issuedAt ≤ now < expiresAt。' }),
    node('wa_gw_principal', 'exclusiveGateway', '主体有效？', 'wa_lane_identity', 4),
    end(W, 'wa_end_401', '401 PRINCIPAL_INVALID', 'wa_lane_identity', 4, -1, 401, 'PRINCIPAL_INVALID'),
    node('wa_dto', 'task', 'DTO 校验与唯一 Idempotency-Key', 'wa_lane_care', 5, 0, { doc: 'parseWateringAdviceRequest；坐标降到 0.01°；长期植物目标不得提交 catalogTaxonRef/pot/lastWatering；请求摘要为规范 JSON SHA-256。' }),
    node('wa_gw_dto', 'exclusiveGateway', 'DTO 合法？', 'wa_lane_care', 6),
    end(W, 'wa_end_400', '400 VALIDATION_FAILED', 'wa_lane_care', 6, -1, 400, 'VALIDATION_FAILED'),
    node('wa_gw_target', 'exclusiveGateway', '目标类型？', 'wa_lane_user_plant', 7),
    node('wa_read_case', 'task', '确认本人有效临时案例（readOwnedCase）', 'wa_lane_user_plant', 8, -1, { doc: '游客 gpc_ / 登录 epc_ 前缀须与主体一致；本人 active 未过期案例为 owned。' }),
    node('wa_gw_case', 'exclusiveGateway', '案例归本人？', 'wa_lane_user_plant', 9, -1),
    end(W, 'wa_end_case_404', '404 NOT_FOUND', 'wa_lane_user_plant', 9, -2, 404, 'NOT_FOUND'),
    node('wa_read_plant', 'task', '读取植物上下文与最近浇水事实（仅登录用户）', 'wa_lane_user_plant', 8, 1, { doc: '游客请求长期植物 → 400；readPlantContext（档案实测盆、品种绑定、档案版本）与 readLatestWateringFact；服务端值覆盖品种、盆器与上次浇水。' }),
    node('wa_gw_plant', 'exclusiveGateway', '植物可用？', 'wa_lane_user_plant', 9, 1),
    end(W, 'wa_end_plant_reject', '400 游客 / 404 / 409 归档 / 503', 'wa_lane_user_plant', 9, 2, 404, 'USER_PLANT_NOT_FOUND_OR_ARCHIVED'),
    node('wa_gw_target_merge', 'exclusiveGateway', '', 'wa_lane_user_plant', 10),
    node('wa_read_policy', 'task', '读取活动浇水策略 care/mvp_watering', 'wa_lane_care', 11, 0, { doc: 'readWateringPolicy(capturedAt)：无可用发布为 null（结果为暂不可用，不是错误）。' }),
    node('wa_read_baseline', 'task', '读取 Tropicals 名义基线（硬规则 v1）', 'wa_lane_knowledge', 12, 0, { doc: 'readPlantBaseline(catalogTaxonRef)；无品种或不受支持为 null。' }),
    node('wa_gw_reads', 'exclusiveGateway', '读取成功？', 'wa_lane_care', 13),
    end(W, 'wa_end_reads_503', '503 SERVICE_UNAVAILABLE', 'wa_lane_care', 13, -1, 503, 'SERVICE_UNAVAILABLE'),
    node('wa_window', 'task', '计算 Open-Meteo 查询窗口（回看≤92天，预报16天）', 'wa_lane_care', 14, 0, { doc: 'resolveOpenMeteoRequestWindow：回看起点为盆土观察、上次浇水、Lux 读数中最早者。' }),
    node('wa_fetch', 'serviceTask', '获取并标准化 Open-Meteo 辐射', 'wa_lane_provider', 15, 0, { doc: 'fetchRadiation；Provider 失败或异常时 radiation=null（光照缺段，流程继续，仍返回 200）。' }),
    node('wa_light', 'businessRuleTask', '光照锚点 → 植物位置 PPFD 时段序列', 'wa_lane_care', 16, 0, { decisionRef: 'mvp_decision_plant_light_anchor', doc: 'deriveMvpPlantLightIntervals：PPFD(h)=Lux 换算区间×GHI(h)÷GHI(测量时段)；测量后 24 小时内附室内实测 VPD。策略或辐射缺失时不计算，环境时段为空。' }),
    node('wa_light_response', 'businessRuleTask', '光响应 L(q)=q/(q+75)，相对 qref=50', 'wa_lane_care', 17, 0, { decisionRef: 'mvp_decision_light_response', doc: '逐时段，TypeScript 计算；超出 PPFD 0～1500 为缺段。' }),
    node('wa_vpd', 'businessRuleTask', 'VPD 包络（Dref=1.4、s=0.6，含区间内峰值；无实测用 0.7～2.2）', 'wa_lane_care', 18, 0, { decisionRef: 'mvp_decision_vpd_envelope', doc: '逐时段，TypeScript 计算；超出 VPD 0.1～4 为缺段。' }),
    node('wa_retention', 'businessRuleTask', '栽培干燥倍率：盆体积比＋主要材料可用水 → S / P / Ae', 'wa_lane_care', 19, 0, { decisionRef: 'mvp_decision_cultivation_retention', doc: 'deriveCultivationDrying（v3，合同 §8）：实际内盆对参考盆 15/11/13cm 的体积比与土表面积比（留空 1、3cm 两端取包络），基质可用水按主要材料规则混合；S=v×AW÷0.3，P=v^[0,0.52]，Ae=土表面积比。几何不全/装不了土/未选基质，以及 v1/v2：S=0.8～1.25、P=Ae=1。盆壁蒸发 κ 未纳入（待验证票 z8v0kmvewm）。' }),
    node('wa_demand', 'businessRuleTask', '环境需水强度：0.8×L×H×P＋0.2×D/1.4×Ae', 'wa_lane_care', 20, 0, { decisionRef: 'mvp_decision_environment_demand', doc: '任一分量缺段 → 该时段从干燥时段清单丢弃。' }),

    node('wa_progress', 'businessRuleTask', '缺段补齐（v3，≤6h）与逐时段干燥进度累积、检查窗口', 'wa_lane_care', 21, 0, { decisionRef: 'mvp_decision_drying_progress', doc: 'fillMvpDryingGaps：v3 起两个有效时段之间 ≤6h 的空洞用有效域全区间需求补齐（首段之前、预报终点之后不补）。rate=[Demand_pot.min÷S.max, Demand_pot.max÷S.min]，进度 += rate×时长÷24h；补齐后仍有空洞 → 历史为 history_gap、未来停止覆盖。' }),
    node('wa_build', 'businessRuleTask', '浇水决策与公开结果（MVP 浇水决策）', 'wa_lane_care', 22, 0, { decisionRef: 'mvp_decision_public_result', doc: 'assessMvpWatering 其余步骤：湿度分组、盆土有效期与映射、本轮窗口、安全门、盆器安全、行动、水量与公开结果；buildWateringAdvice 另组装输入清单、算法发布清单与派生摘要。以上 7 步均为纯计算，不访问网络或数据库。' }),
    node('wa_gw_persist', 'exclusiveGateway', '持久化分支？', 'wa_lane_care', 23),
    node('wa_txn_case', 'task', '事务：幂等占位→锁案例→查建会话→追加结果→读回', 'wa_lane_care', 24, -1, { doc: 'createWateringAdviceApplicationService：会话与结果期限等于案例期限；暂不可用结果同样追加；不写浇水事实、计划或提醒。' }),
    node('wa_txn_plant', 'task', '事务：幂等占位→锁本人植物→复核指纹→写结果与建议', 'wa_lane_care', 24, 1, { doc: 'createUserPlantWateringAdviceApplicationService：404/409 归档；档案版本、品种绑定、最近浇水事实任一变化 → 回滚 503；可确认结果同事务写 care_proposals。' }),
    node('wa_gw_persist_merge', 'exclusiveGateway', '', 'wa_lane_care', 25),
    node('wa_gw_txn', 'exclusiveGateway', '事务结果？', 'wa_lane_care', 26),
    end(W, 'wa_end_txn_409', '404 / 409 拒绝', 'wa_lane_care', 26, -1, 409, 'IDEMPOTENCY_CONFLICT_OR_NOT_FOUND', '同键异体 409 IDEMPOTENCY_CONFLICT；事务内案例/植物不存在 404、归档 409（作为首次结果记录，可重放）。'),
    end(W, 'wa_end_txn_503', '503 处理中 / 提交未知', 'wa_lane_care', 26, 1, 503, 'SERVICE_UNAVAILABLE_RETRY', '首个请求未完成、提交结果未知且只读对账未命中、或指纹变化：客户端用同一幂等键重试。'),
    node('wa_end_ok', 'endEvent', '200 浇水建议（含首次结果重放）', 'wa_lane_user', 27),
  ],
  flows: [
    flow('wa_f01', 'wa_start', 'wa_limits'),
    flow('wa_f02', 'wa_limits', 'wa_gw_limits'),
    flow('wa_f03', 'wa_gw_limits', 'wa_end_413_415', '否'),
    flow('wa_f04', 'wa_gw_limits', 'wa_principal', '是'),
    flow('wa_f05', 'wa_principal', 'wa_gw_principal'),
    flow('wa_f06', 'wa_gw_principal', 'wa_end_401', '否'),
    flow('wa_f07', 'wa_gw_principal', 'wa_dto', '是'),
    flow('wa_f08', 'wa_dto', 'wa_gw_dto'),
    flow('wa_f09', 'wa_gw_dto', 'wa_end_400', '否'),
    flow('wa_f10', 'wa_gw_dto', 'wa_gw_target', '是'),
    flow('wa_f11', 'wa_gw_target', 'wa_read_case', '临时案例'),
    flow('wa_f12', 'wa_gw_target', 'wa_read_plant', '长期植物'),
    flow('wa_f13', 'wa_read_case', 'wa_gw_case'),
    flow('wa_f14', 'wa_gw_case', 'wa_end_case_404', '否'),
    flow('wa_f15', 'wa_gw_case', 'wa_gw_target_merge', '是'),
    flow('wa_f16', 'wa_read_plant', 'wa_gw_plant'),
    flow('wa_f17', 'wa_gw_plant', 'wa_end_plant_reject', '否'),
    flow('wa_f18', 'wa_gw_plant', 'wa_gw_target_merge', '是'),
    flow('wa_f19', 'wa_gw_target_merge', 'wa_read_policy'),
    flow('wa_f20', 'wa_read_policy', 'wa_read_baseline'),
    flow('wa_f21', 'wa_read_baseline', 'wa_gw_reads'),
    flow('wa_f22', 'wa_gw_reads', 'wa_end_reads_503', '否'),
    flow('wa_f23', 'wa_gw_reads', 'wa_window', '是'),
    flow('wa_f24', 'wa_window', 'wa_fetch'),
    flow('wa_f25', 'wa_fetch', 'wa_light'),
    flow('wa_f35', 'wa_light', 'wa_light_response'),
    flow('wa_f36', 'wa_light_response', 'wa_vpd'),
    flow('wa_f37', 'wa_vpd', 'wa_retention'),
    flow('wa_f38', 'wa_retention', 'wa_demand'),
    flow('wa_f39', 'wa_demand', 'wa_progress'),
    flow('wa_f40', 'wa_progress', 'wa_build'),
    flow('wa_f26', 'wa_build', 'wa_gw_persist'),
    flow('wa_f27', 'wa_gw_persist', 'wa_txn_case', '临时案例'),
    flow('wa_f28', 'wa_gw_persist', 'wa_txn_plant', '长期植物'),
    flow('wa_f29', 'wa_txn_case', 'wa_gw_persist_merge'),
    flow('wa_f30', 'wa_txn_plant', 'wa_gw_persist_merge'),
    flow('wa_f31', 'wa_gw_persist_merge', 'wa_gw_txn'),
    flow('wa_f32', 'wa_gw_txn', 'wa_end_txn_409', '拒绝'),
    flow('wa_f33', 'wa_gw_txn', 'wa_end_txn_503', '重试'),
    flow('wa_f34', 'wa_gw_txn', 'wa_end_ok', '200'),
  ],
}

// ---------------------------------------------------------------- ② 长期养护闭环
const T = 'ltc'
export const longTermCare = {
  id: 'long_term_care_loop', processId: 'long_term_care_loop_process', processName: '长期养护闭环（long-term-care/v1）',
  participantName: '长期养护：建议 → 确认 → 检查计划 → 完成',
  documentation: '反映 createUserPlantWateringAdviceApplicationService、createLongTermCareCommands（confirmProposal、completePlan）与 long-term-care-routes。所有写接口走 runIdempotentWrite：同键同体重放首次结果、同键异体 409 IDEMPOTENCY_CONFLICT、处理中 503。诊断与建议不自动写事实；只有用户确认才写计划或事实，不写提醒任务。代码中长期养护没有 410 分支：过期建议返回 409 CARE_PROPOSAL_NOT_CONFIRMABLE，过期计划返回 409 CARE_PLAN_EXPIRED。计划过期（§12）由独立的每小时定时事件函数 care-plan-expiry 写入，与用户完成请求以 status=planned 条件互斥。',
  lanes: [
    { id: 'ltc_lane_user', name: '用户 / 小程序' },
    { id: 'ltc_lane_identity', name: 'identity 域' },
    { id: 'ltc_lane_care', name: 'care 云函数' },
    { id: 'ltc_lane_user_plant', name: 'user-plant 域' },
    { id: 'ltc_lane_expiry', name: 'care-plan-expiry 事件函数' },
  ],
  nodes: [
    node('ltc_start', 'startEvent', '请求长期植物浇水建议', 'ltc_lane_user', 0),
    node('ltc_advice', 'callActivity', '生成浇水建议（流程①长期植物分支）', 'ltc_lane_care', 1, 0, { calledElement: 'watering_advice_request_process' }),
    node('ltc_proposal_rule', 'businessRuleTask', '判定是否生成可确认建议', 'ltc_lane_care', 2, 0, { decisionRef: 'ltc_decision_proposal', doc: 'isConfirmableWateringResult：ready 且 action ∈ {water_allowed, check_later, check_now, priority_check}；有效期 = 窗口最晚端或生成时刻 + 24h。与结果同事务写入。' }),
    node('ltc_gw_proposal', 'exclusiveGateway', '有 proposalRef？', 'ltc_lane_care', 3),
    node('ltc_end_no_proposal', 'endEvent', '仅展示结果（无建议）', 'ltc_lane_care', 3, -1),
    node('ltc_decide', 'userTask', '选择：安排检查 / 记录浇水 / 忽略', 'ltc_lane_user', 4, 0, { doc: 'POST /api/v2/care/user-plants/{userPlantRef}/proposals/{proposalRef}/confirmations，严格三选一。' }),
    node('ltc_auth1', 'task', '解析登录主体', 'ltc_lane_identity', 5),
    node('ltc_gw_auth1', 'exclusiveGateway', '主体有效？', 'ltc_lane_identity', 6),
    end(T, 'ltc_end_auth1_401', '401 / 400', 'ltc_lane_identity', 6, -1, 401, 'PRINCIPAL_INVALID_OR_VALIDATION_FAILED', '主体无效 401；路径引用或正文不合法 400。'),
    node('ltc_context', 'task', '读取档案上下文与日历名称（事务前）', 'ltc_lane_user_plant', 7, 0, { doc: 'readPlantContext（昵称、档案版本、品种绑定）；无昵称时读品种中文名。读取失败 503。' }),
    node('ltc_gw_context', 'exclusiveGateway', '植物存在？', 'ltc_lane_user_plant', 8),
    end(T, 'ltc_end_context_404', '404 USER_PLANT_NOT_FOUND', 'ltc_lane_user_plant', 8, 1, 404, 'USER_PLANT_NOT_FOUND'),
    node('ltc_lock_plant1', 'task', '事务：幂等占位 → 锁本人植物', 'ltc_lane_care', 9),
    node('ltc_gw_plant1', 'exclusiveGateway', '植物可写？', 'ltc_lane_care', 10),
    end(T, 'ltc_end_plant1_404', '404 USER_PLANT_NOT_FOUND', 'ltc_lane_care', 10, -1, 404, 'USER_PLANT_NOT_FOUND'),
    end(T, 'ltc_end_plant1_409', '409 USER_PLANT_ARCHIVED', 'ltc_lane_care', 10, 1, 409, 'USER_PLANT_ARCHIVED'),
    node('ltc_fingerprint', 'task', '复核档案版本与品种绑定', 'ltc_lane_care', 11),
    node('ltc_gw_fingerprint', 'exclusiveGateway', '读取后未变化？', 'ltc_lane_care', 12),
    end(T, 'ltc_end_fingerprint_503', '503 回滚，同键重试', 'ltc_lane_care', 12, 1, 503, 'SERVICE_UNAVAILABLE_RETRY'),
    node('ltc_lock_proposal', 'task', '锁定建议', 'ltc_lane_care', 13),
    node('ltc_gw_confirmable', 'exclusiveGateway', 'proposed 且未过期？', 'ltc_lane_care', 14),
    end(T, 'ltc_end_not_confirmable', '409 CARE_PROPOSAL_NOT_CONFIRMABLE', 'ltc_lane_care', 14, -1, 409, 'CARE_PROPOSAL_NOT_CONFIRMABLE', '已确认、已忽略、已过期或不存在；没有 410。'),
    node('ltc_gw_decision', 'exclusiveGateway', '决定类型？', 'ltc_lane_care', 15),
    node('ltc_dismiss', 'task', '建议置 dismissed', 'ltc_lane_care', 16, -2),
    node('ltc_end_dismissed', 'endEvent', '200 已忽略', 'ltc_lane_care', 17, -2),
    node('ltc_schedule_rule', 'businessRuleTask', '计算检查计划时刻', 'ltc_lane_care', 16, 0, { decisionRef: 'ltc_decision_check_schedule' }),
    node('ltc_gw_schedule', 'exclusiveGateway', '时刻合法？', 'ltc_lane_care', 17),
    end(T, 'ltc_end_schedule_400', '400 时刻超出窗口', 'ltc_lane_care', 17, -1, 400, 'VALIDATION_FAILED_SCHEDULE'),
    node('ltc_write_plan', 'task', '写检查计划 check_soil（planned）＋日历；建议 confirmed', 'ltc_lane_care', 18, 0, { doc: 'buildCareCalendar：标题“检查{名称}盆土”，时长 30 分钟；一个建议至多一个计划；不写 reminder_jobs。' }),
    node('ltc_occurred_rule1', 'businessRuleTask', '校验浇水时刻', 'ltc_lane_care', 16, 2, { decisionRef: 'ltc_decision_watering_occurred_at' }),
    node('ltc_gw_occurred1', 'exclusiveGateway', '时刻合法？', 'ltc_lane_care', 17, 2),
    end(T, 'ltc_end_occurred1_400', '400 浇水时间不合法', 'ltc_lane_care', 17, 3, 400, 'VALIDATION_FAILED_OCCURRED_AT'),
    node('ltc_write_fact1', 'task', '写浇水事实；建议 confirmed', 'ltc_lane_care', 18, 2),
    node('ltc_end_fact1', 'endEvent', '200 已记录浇水', 'ltc_lane_care', 19, 2),
    node('ltc_check', 'userTask', '到期检查盆土并提交完成（done / skipped，带 version）', 'ltc_lane_user', 19, 0, { doc: 'POST .../plans/{planRef}/completions；skipped 不得带 soil/watering。' }),
    node('ltc_auth2', 'task', '解析登录主体', 'ltc_lane_identity', 20),
    node('ltc_gw_auth2', 'exclusiveGateway', '主体有效？', 'ltc_lane_identity', 21),
    end(T, 'ltc_end_auth2_401', '401 / 400', 'ltc_lane_identity', 21, -1, 401, 'PRINCIPAL_INVALID_OR_VALIDATION_FAILED'),
    node('ltc_lock_plant2', 'task', '事务：幂等占位 → 锁本人植物', 'ltc_lane_care', 22),
    node('ltc_gw_plant2', 'exclusiveGateway', '植物可写？', 'ltc_lane_care', 23),
    end(T, 'ltc_end_plant2_404', '404 USER_PLANT_NOT_FOUND', 'ltc_lane_care', 23, -1, 404, 'USER_PLANT_NOT_FOUND'),
    end(T, 'ltc_end_plant2_409', '409 USER_PLANT_ARCHIVED', 'ltc_lane_care', 23, 1, 409, 'USER_PLANT_ARCHIVED'),
    node('ltc_lock_plan', 'task', '锁定计划', 'ltc_lane_care', 24),
    node('ltc_gw_plan', 'exclusiveGateway', '计划存在？', 'ltc_lane_care', 25),
    end(T, 'ltc_end_plan_404', '404 计划不存在', 'ltc_lane_care', 25, -1, 404, 'USER_PLANT_NOT_FOUND_PLAN'),
    node('ltc_gw_expired', 'exclusiveGateway', '计划已过期？', 'ltc_lane_care', 26),
    end(T, 'ltc_end_plan_expired', '409 CARE_PLAN_EXPIRED', 'ltc_lane_care', 26, -1, 409, 'CARE_PLAN_EXPIRED', '计划状态为 expired：无论 version 是否匹配、done 还是 skipped，判定先于版本比对；不写事实、观察，不改计划（§12.3）。'),
    node('ltc_gw_version', 'exclusiveGateway', 'planned 且 version 一致？', 'ltc_lane_care', 27),
    end(T, 'ltc_end_version_409', '409 CARE_PLAN_VERSION_CONFLICT', 'ltc_lane_care', 27, -1, 409, 'CARE_PLAN_VERSION_CONFLICT'),
    node('ltc_gw_outcome', 'exclusiveGateway', '完成结果？', 'ltc_lane_care', 28),
    node('ltc_cancel', 'task', '计划 cancelled，version+1', 'ltc_lane_care', 29, -1),
    node('ltc_gw_watering', 'exclusiveGateway', '附带浇水？', 'ltc_lane_care', 29, 1),
    node('ltc_occurred_rule2', 'businessRuleTask', '校验浇水时刻', 'ltc_lane_care', 30, 1, { decisionRef: 'ltc_decision_watering_occurred_at' }),
    node('ltc_gw_occurred2', 'exclusiveGateway', '时刻合法？', 'ltc_lane_care', 31, 1),
    end(T, 'ltc_end_occurred2_400', '400 浇水时间不合法', 'ltc_lane_care', 31, 2, 400, 'VALIDATION_FAILED_OCCURRED_AT'),
    node('ltc_write_fact2', 'task', '写浇水事实', 'ltc_lane_care', 32, 1),
    node('ltc_gw_watering_merge', 'exclusiveGateway', '', 'ltc_lane_care', 33, 1),
    node('ltc_gw_soil', 'exclusiveGateway', '附带盆土观察？', 'ltc_lane_care', 34, 1),
    node('ltc_write_soil', 'task', '写盆土观察（user_context，低置信）', 'ltc_lane_care', 35, 2, { doc: 'care_environment_observations：factor_type=soil_surface，观察时刻=服务端当前时刻（Q2）。' }),
    node('ltc_gw_soil_merge', 'exclusiveGateway', '', 'ltc_lane_care', 36, 1),
    node('ltc_complete', 'task', '计划 completed，version+1', 'ltc_lane_care', 37, 1),
    node('ltc_gw_outcome_merge', 'exclusiveGateway', '', 'ltc_lane_care', 38),
    node('ltc_expiry_start', 'startEvent', '每小时定时触发', 'ltc_lane_expiry', 20, 0, { timerCycle: 'R/PT1H', doc: 'CloudBase 定时触发器 7 段 cron「0 0 * * * * *」挂在普通（事件型）云函数 care-plan-expiry 上（§12.5、§12.7）。' }),
    node('ltc_expiry_deadline', 'task', '锁定截止：cutoff=开始时刻−72h；时长上限=开始+函数超时/2', 'ltc_lane_expiry', 21, 0, { doc: 'resolveExpiryRunDeadlineMs；单次运行内所有批次使用同一截止时刻。' }),
    node('ltc_gw_expiry_timeout', 'exclusiveGateway', '取到函数超时？', 'ltc_lane_expiry', 22),
    node('ltc_end_expiry_not_started', 'endEvent', 'not_started（不猜默认值）', 'ltc_lane_expiry', 22, -1, { doc: '写 care_plan_expiry_run 日志（outcome=not_started）。' }),
    node('ltc_expiry_batches', 'businessRuleTask', '分批条件更新：planned 且已过期 → expired，version+1', 'ltc_lane_expiry', 23, 0, { loop: true, decisionRef: 'ltc_decision_plan_expired', doc: 'UPDATE care_plans SET status=expired, version=version+1 WHERE status=planned AND scheduled_at_ms < cutoff ORDER BY scheduled_at_ms, id LIMIT 500；每批独立短事务。status=planned 条件是并发闸门：用户先完成的计划不会被覆盖。循环直到某批影响行数 < 500、到达时长上限或某批失败。不写事实、观察、提醒，不改来源建议。' }),
    node('ltc_gw_expiry_outcome', 'exclusiveGateway', '运行结果？', 'ltc_lane_expiry', 24),
    node('ltc_end_expiry_deadline', 'endEvent', 'deadline_reached（剩余下次处理）', 'ltc_lane_expiry', 24, -1, { doc: '已开启的批次跑完，不再开启新批次。' }),
    node('ltc_end_expiry_failed', 'endEvent', 'failed（该批回滚，下次收敛）', 'ltc_lane_expiry', 24, 1, { doc: '已提交批次保留；另写 care_plan_expiry_batch_failed（只含错误类名）。提交结果未知同样停止。' }),
    node('ltc_end_expiry_drained', 'endEvent', 'drained（已清空）', 'ltc_lane_expiry', 25, 0, { doc: '写 care_plan_expiry_run：outcome、expiredCount、batchCount、cutoffAt、durationMs，不含任何内部主键或公开引用。' }),
    node('ltc_end_done', 'endEvent', '200 计划闭环', 'ltc_lane_user', 39),
  ],
  flows: [
    flow('ltc_f01', 'ltc_start', 'ltc_advice'),
    flow('ltc_f02', 'ltc_advice', 'ltc_proposal_rule'),
    flow('ltc_f03', 'ltc_proposal_rule', 'ltc_gw_proposal'),
    flow('ltc_f04', 'ltc_gw_proposal', 'ltc_end_no_proposal', '否'),
    flow('ltc_f05', 'ltc_gw_proposal', 'ltc_decide', '是'),
    flow('ltc_f06', 'ltc_decide', 'ltc_auth1'),
    flow('ltc_f07', 'ltc_auth1', 'ltc_gw_auth1'),
    flow('ltc_f08', 'ltc_gw_auth1', 'ltc_end_auth1_401', '否'),
    flow('ltc_f09', 'ltc_gw_auth1', 'ltc_context', '是'),
    flow('ltc_f10', 'ltc_context', 'ltc_gw_context'),
    flow('ltc_f11', 'ltc_gw_context', 'ltc_end_context_404', '否'),
    flow('ltc_f12', 'ltc_gw_context', 'ltc_lock_plant1', '是'),
    flow('ltc_f13', 'ltc_lock_plant1', 'ltc_gw_plant1'),
    flow('ltc_f14', 'ltc_gw_plant1', 'ltc_end_plant1_404', '不存在'),
    flow('ltc_f15', 'ltc_gw_plant1', 'ltc_end_plant1_409', '已归档'),
    flow('ltc_f16', 'ltc_gw_plant1', 'ltc_fingerprint', '可写'),
    flow('ltc_f17', 'ltc_fingerprint', 'ltc_gw_fingerprint'),
    flow('ltc_f18', 'ltc_gw_fingerprint', 'ltc_end_fingerprint_503', '已变化'),
    flow('ltc_f19', 'ltc_gw_fingerprint', 'ltc_lock_proposal', '未变化'),
    flow('ltc_f20', 'ltc_lock_proposal', 'ltc_gw_confirmable'),
    flow('ltc_f21', 'ltc_gw_confirmable', 'ltc_end_not_confirmable', '否'),
    flow('ltc_f22', 'ltc_gw_confirmable', 'ltc_gw_decision', '是'),
    flow('ltc_f23', 'ltc_gw_decision', 'ltc_dismiss', 'dismiss'),
    flow('ltc_f24', 'ltc_dismiss', 'ltc_end_dismissed'),
    flow('ltc_f25', 'ltc_gw_decision', 'ltc_schedule_rule', 'schedule_check'),
    flow('ltc_f26', 'ltc_schedule_rule', 'ltc_gw_schedule'),
    flow('ltc_f27', 'ltc_gw_schedule', 'ltc_end_schedule_400', '否'),
    flow('ltc_f28', 'ltc_gw_schedule', 'ltc_write_plan', '是'),
    flow('ltc_f29', 'ltc_gw_decision', 'ltc_occurred_rule1', 'record_watering'),
    flow('ltc_f30', 'ltc_occurred_rule1', 'ltc_gw_occurred1'),
    flow('ltc_f31', 'ltc_gw_occurred1', 'ltc_end_occurred1_400', '否'),
    flow('ltc_f32', 'ltc_gw_occurred1', 'ltc_write_fact1', '是'),
    flow('ltc_f33', 'ltc_write_fact1', 'ltc_end_fact1'),
    flow('ltc_f34', 'ltc_write_plan', 'ltc_check'),
    flow('ltc_f35', 'ltc_check', 'ltc_auth2'),
    flow('ltc_f36', 'ltc_auth2', 'ltc_gw_auth2'),
    flow('ltc_f37', 'ltc_gw_auth2', 'ltc_end_auth2_401', '否'),
    flow('ltc_f38', 'ltc_gw_auth2', 'ltc_lock_plant2', '是'),
    flow('ltc_f39', 'ltc_lock_plant2', 'ltc_gw_plant2'),
    flow('ltc_f40', 'ltc_gw_plant2', 'ltc_end_plant2_404', '不存在'),
    flow('ltc_f41', 'ltc_gw_plant2', 'ltc_end_plant2_409', '已归档'),
    flow('ltc_f42', 'ltc_gw_plant2', 'ltc_lock_plan', '可写'),
    flow('ltc_f43', 'ltc_lock_plan', 'ltc_gw_plan'),
    flow('ltc_f44', 'ltc_gw_plan', 'ltc_end_plan_404', '否'),
    flow('ltc_f45', 'ltc_gw_plan', 'ltc_gw_expired', '是'),
    flow('ltc_f64', 'ltc_gw_expired', 'ltc_end_plan_expired', '是'),
    flow('ltc_f65', 'ltc_gw_expired', 'ltc_gw_version', '否'),
    flow('ltc_f46', 'ltc_gw_version', 'ltc_end_version_409', '否'),
    flow('ltc_f47', 'ltc_gw_version', 'ltc_gw_outcome', '是'),
    flow('ltc_f48', 'ltc_gw_outcome', 'ltc_cancel', 'skipped'),
    flow('ltc_f49', 'ltc_gw_outcome', 'ltc_gw_watering', 'done'),
    flow('ltc_f50', 'ltc_gw_watering', 'ltc_occurred_rule2', '是'),
    flow('ltc_f51', 'ltc_occurred_rule2', 'ltc_gw_occurred2'),
    flow('ltc_f52', 'ltc_gw_occurred2', 'ltc_end_occurred2_400', '否'),
    flow('ltc_f53', 'ltc_gw_occurred2', 'ltc_write_fact2', '是'),
    flow('ltc_f54', 'ltc_write_fact2', 'ltc_gw_watering_merge'),
    flow('ltc_f55', 'ltc_gw_watering', 'ltc_gw_watering_merge', '否'),
    flow('ltc_f56', 'ltc_gw_watering_merge', 'ltc_gw_soil'),
    flow('ltc_f57', 'ltc_gw_soil', 'ltc_write_soil', '是'),
    flow('ltc_f58', 'ltc_write_soil', 'ltc_gw_soil_merge'),
    flow('ltc_f59', 'ltc_gw_soil', 'ltc_gw_soil_merge', '否'),
    flow('ltc_f60', 'ltc_gw_soil_merge', 'ltc_complete'),
    flow('ltc_f61', 'ltc_cancel', 'ltc_gw_outcome_merge'),
    flow('ltc_f62', 'ltc_complete', 'ltc_gw_outcome_merge'),
    flow('ltc_f63', 'ltc_gw_outcome_merge', 'ltc_end_done'),
    flow('ltc_f66', 'ltc_expiry_start', 'ltc_expiry_deadline'),
    flow('ltc_f67', 'ltc_expiry_deadline', 'ltc_gw_expiry_timeout'),
    flow('ltc_f68', 'ltc_gw_expiry_timeout', 'ltc_end_expiry_not_started', '否'),
    flow('ltc_f69', 'ltc_gw_expiry_timeout', 'ltc_expiry_batches', '是'),
    flow('ltc_f70', 'ltc_expiry_batches', 'ltc_gw_expiry_outcome'),
    flow('ltc_f71', 'ltc_gw_expiry_outcome', 'ltc_end_expiry_deadline', '到时长上限'),
    flow('ltc_f72', 'ltc_gw_expiry_outcome', 'ltc_end_expiry_failed', '批次失败'),
    flow('ltc_f73', 'ltc_gw_expiry_outcome', 'ltc_end_expiry_drained', '批次<500'),
  ],
}

// ---------------------------------------------------------------- ③ 游客 → 临时案例 → 登录 → 认领
const C = 'gc'
export const guestClaim = {
  id: 'guest_claim', processId: 'guest_claim_process', processName: '游客临时案例与登录认领（guest-session-claim/v1）',
  participantName: '游客 → 临时案例 → 登录 → 认领',
  routeLast: ['gc_f47', 'gc_f37'],
  documentation: '反映 createGuestSessionRouteHandler、createTemporaryCaseApplicationService、登录会话签发、createClaimGuestPlantCaseApplicationService 与 decideGuestClaimLease。认领状态机 requested → processing → completed；处理租约 30 秒（硬规则 user-plant.guest_claim.processing_lease_seconds）。',
  lanes: [
    { id: 'gc_lane_user', name: '用户 / 小程序' },
    { id: 'gc_lane_identity', name: 'identity 域' },
    { id: 'gc_lane_user_plant', name: 'user-plant 域' },
    { id: 'gc_lane_subscription', name: 'subscription 域' },
    { id: 'gc_lane_provider', name: '外部 Provider' },
  ],
  nodes: [
    node('gc_start', 'startEvent', '未登录进入小程序', 'gc_lane_user', 0),
    node('gc_guest_policy', 'task', '游客签发：DTO、锁定游客策略与摘要子密钥', 'gc_lane_identity', 1, 0, { doc: 'POST /api/v2/identity/guest-sessions；不读取任何 IP 请求头。DTO 不合法 400。' }),
    node('gc_gw_guest_policy', 'exclusiveGateway', '可签发？', 'gc_lane_identity', 2),
    end(C, 'gc_end_guest_policy', '400 / 503', 'gc_lane_identity', 2, -1, 503, 'GUEST_ISSUE_UNAVAILABLE', 'DTO 不合法 400；无可信策略或子密钥 503（失败关闭）。'),
    node('gc_gw_douyin', 'exclusiveGateway', '抖音且带 anonymousCode 且开关开启？', 'gc_lane_identity', 3),
    node('gc_douyin', 'serviceTask', '换取 anonymous_openid（失败按无信号）', 'gc_lane_provider', 4, 0, { doc: '只取 HMAC 摘要；anonymousCode 与匿名 openid 不进入日志、审计或响应。' }),
    node('gc_gw_douyin_merge', 'exclusiveGateway', '', 'gc_lane_identity', 5),
    node('gc_issue_guest', 'task', '按匿名信号限流并签发游客会话', 'gc_lane_identity', 6, 0, { doc: 'issueGuestSession；令牌只在成功响应出现一次。' }),
    node('gc_gw_issue', 'exclusiveGateway', '签发结果？', 'gc_lane_identity', 7),
    end(C, 'gc_end_issue_429', '429 RATE_LIMITED', 'gc_lane_identity', 7, -1, 429, 'RATE_LIMITED'),
    end(C, 'gc_end_issue_503', '503 SERVICE_UNAVAILABLE', 'gc_lane_identity', 7, 1, 503, 'SERVICE_UNAVAILABLE'),
    node('gc_create_case_req', 'userTask', '保存 guestToken，提交创建临时案例', 'gc_lane_user', 8, 0, { doc: 'POST /api/v2/user-plants/temporary-cases（游客 Bearer + Idempotency-Key）。' }),
    node('gc_lock_session', 'task', '事务：幂等占位 → 锁游客会话并计数有效案例', 'gc_lane_user_plant', 9),
    node('gc_gw_case', 'exclusiveGateway', '可创建？', 'gc_lane_user_plant', 10),
    end(C, 'gc_end_case_401', '401 PRINCIPAL_INVALID', 'gc_lane_user_plant', 10, -1, 401, 'PRINCIPAL_INVALID'),
    end(C, 'gc_end_case_409', '409 TEMPORARY_CASE_LIMIT_REACHED', 'gc_lane_user_plant', 10, 1, 409, 'TEMPORARY_CASE_LIMIT_REACHED'),
    node('gc_insert_case', 'task', '写入案例 gpc_（失效＝游客会话失效）并读回', 'gc_lane_user_plant', 11, 0, { doc: 'decideGuestTemporaryCase；游客没有独立案例有效期配置。确定拒绝也记为幂等首次结果。' }),
    node('gc_login_req', 'userTask', '使用临时案例后选择登录', 'gc_lane_user', 12, 0, { doc: '临时案例可用于浇水建议（流程①临时案例分支）。登录：POST /api/v2/identity/sessions（一次性平台 code，不要求 Idempotency-Key）。' }),
    node('gc_login_input', 'task', '登录请求校验', 'gc_lane_identity', 13),
    node('gc_verify_code', 'serviceTask', '验真一次性平台 code', 'gc_lane_provider', 14, 0, { doc: '微信/抖音/小红书受控 Provider；未配置平台失败关闭。同一 code 重试拒绝。' }),
    node('gc_issue_session', 'task', '解析或创建统一 user_id，签发 Bearer 会话', 'gc_lane_identity', 15, 0, { doc: '(platform, platform_subject_id) 唯一约束保证不重复创建用户或绑定。' }),
    node('gc_gw_login', 'exclusiveGateway', '登录成功？', 'gc_lane_identity', 16),
    end(C, 'gc_end_login_401', '400 / 401 凭证无效', 'gc_lane_identity', 16, -1, 401, 'LOGIN_PRINCIPAL_INVALID', '输入不合法 400；平台凭证无效或已消费 401。'),
    end(C, 'gc_end_login_503', '503 SERVICE_UNAVAILABLE', 'gc_lane_identity', 16, 1, 503, 'LOGIN_SERVICE_UNAVAILABLE'),
    node('gc_claim_req', 'userTask', '提交认领（登录 Bearer＋guestToken＋案例＋目标）', 'gc_lane_user', 17, 0, { doc: 'POST /api/v2/user-plants/claims；目标为 existing_user_plant 或 new_user_plant。' }),
    node('gc_claim_input', 'task', '请求限制、登录主体、DTO 与幂等键', 'gc_lane_user_plant', 18),
    node('gc_gw_claim_input', 'exclusiveGateway', '请求合法？', 'gc_lane_user_plant', 19),
    end(C, 'gc_end_claim_input', '401 / 400 / 413 / 415', 'gc_lane_user_plant', 19, -1, 401, 'CLAIM_REQUEST_REJECTED'),
    node('gc_gw_target', 'exclusiveGateway', '新建植物？', 'gc_lane_user_plant', 20),
    node('gc_capability', 'serviceTask', '读取能力快照（失败为 null）', 'gc_lane_subscription', 21, 0, { doc: '缺能力不猜测授权，由完成事务判定。' }),
    node('gc_gw_target_merge', 'exclusiveGateway', '', 'gc_lane_user_plant', 22),
    node('gc_receipt', 'task', '读取原成功收据（新连接只读）', 'gc_lane_user_plant', 23),
    node('gc_gw_receipt', 'exclusiveGateway', '已有收据？', 'gc_lane_user_plant', 24),
    end(C, 'gc_end_receipt_409', '409 IDEMPOTENCY_CONFLICT', 'gc_lane_user_plant', 24, 1, 409, 'IDEMPOTENCY_CONFLICT'),
    node('gc_register', 'task', '事务一：登记命令 requested → 取得处理租约', 'gc_lane_user_plant', 25, 0, { doc: 'register + leaseRepository.acquire 同一事务；登记或租约阶段异常回滚并返回 503。' }),
    node('gc_gw_register', 'exclusiveGateway', '登记结果？', 'gc_lane_user_plant', 26),
    end(C, 'gc_end_register_409', '409 / 401 / 503', 'gc_lane_user_plant', 26, -1, 409, 'GUEST_SESSION_NOT_CLAIMABLE', '不可认领或幂等冲突 409；主体无效 401；存储不可用 503。'),
    end(C, 'gc_end_register_410', '410 GUEST_SESSION_EXPIRED', 'gc_lane_user_plant', 26, 1, 410, 'GUEST_SESSION_EXPIRED'),
    node('gc_gw_lease', 'exclusiveGateway', '租约裁决？', 'gc_lane_user_plant', 27, 0),
    end(C, 'gc_end_lease_503', '503 处理中（同键重试）', 'gc_lane_user_plant', 27, -1, 503, 'CLAIM_PROCESSING', '他人持有未过期租约（now < leaseExpiresAt），不接管。'),
    node('gc_gw_terminal', 'exclusiveGateway', '命令终态？', 'gc_lane_user_plant', 27, 1),
    end(C, 'gc_end_failed_409', '409 GUEST_SESSION_NOT_CLAIMABLE', 'gc_lane_user_plant', 27, 2, 409, 'GUEST_SESSION_NOT_CLAIMABLE_FAILED'),
    node('gc_recheck_receipt', 'task', '只读核对原收据', 'gc_lane_user_plant', 28, 1, { doc: '核对不到为 503。' }),
    node('gc_complete', 'task', '事务二：完成认领（持有者匹配且租约未过期才写）', 'gc_lane_user_plant', 28, 0, { doc: '取得 = 首次（attempt=1）、过期接管（attempt+1，换持有者）或本人已持有；新建植物校验能力快照；提交未知时只读核对。' }),
    node('gc_gw_complete', 'exclusiveGateway', '完成结果？', 'gc_lane_user_plant', 29, 0),
    end(C, 'gc_end_complete_reject', '409 / 401 / 403 / 503', 'gc_lane_user_plant', 29, -1, 409, 'CLAIM_COMPLETION_REJECTED', 'not_claimable 409、capability_snapshot_expired 409、principal_invalid 401、capability_denied 403、unavailable 503。'),
    end(C, 'gc_end_complete_410', '410 GUEST_SESSION_EXPIRED', 'gc_lane_user_plant', 29, 1, 410, 'GUEST_SESSION_EXPIRED_COMPLETION'),
    node('gc_gw_success_merge', 'exclusiveGateway', '', 'gc_lane_user_plant', 30),
    node('gc_object_kinds', 'task', '读取已认领对象类别', 'gc_lane_user_plant', 31, 0, { doc: '读取失败 503；replayed = 结果 claimRef ≠ 本次候选。' }),
    node('gc_end_ok', 'endEvent', '200 认领成功（userPlantId）', 'gc_lane_user', 32),
  ],
  flows: [
    flow('gc_f01', 'gc_start', 'gc_guest_policy'),
    flow('gc_f02', 'gc_guest_policy', 'gc_gw_guest_policy'),
    flow('gc_f03', 'gc_gw_guest_policy', 'gc_end_guest_policy', '否'),
    flow('gc_f04', 'gc_gw_guest_policy', 'gc_gw_douyin', '是'),
    flow('gc_f05', 'gc_gw_douyin', 'gc_douyin', '是'),
    flow('gc_f06', 'gc_douyin', 'gc_gw_douyin_merge'),
    flow('gc_f07', 'gc_gw_douyin', 'gc_gw_douyin_merge', '否'),
    flow('gc_f08', 'gc_gw_douyin_merge', 'gc_issue_guest'),
    flow('gc_f09', 'gc_issue_guest', 'gc_gw_issue'),
    flow('gc_f10', 'gc_gw_issue', 'gc_end_issue_429', '限流'),
    flow('gc_f11', 'gc_gw_issue', 'gc_end_issue_503', '不可用'),
    flow('gc_f12', 'gc_gw_issue', 'gc_create_case_req', '200'),
    flow('gc_f13', 'gc_create_case_req', 'gc_lock_session'),
    flow('gc_f14', 'gc_lock_session', 'gc_gw_case'),
    flow('gc_f15', 'gc_gw_case', 'gc_end_case_401', '会话无效'),
    flow('gc_f16', 'gc_gw_case', 'gc_end_case_409', '达上限'),
    flow('gc_f17', 'gc_gw_case', 'gc_insert_case', '可创建'),
    flow('gc_f18', 'gc_insert_case', 'gc_login_req'),
    flow('gc_f19', 'gc_login_req', 'gc_login_input'),
    flow('gc_f20', 'gc_login_input', 'gc_verify_code'),
    flow('gc_f21', 'gc_verify_code', 'gc_issue_session'),
    flow('gc_f22', 'gc_issue_session', 'gc_gw_login'),
    flow('gc_f23', 'gc_gw_login', 'gc_end_login_401', '凭证无效'),
    flow('gc_f24', 'gc_gw_login', 'gc_end_login_503', '不可用'),
    flow('gc_f25', 'gc_gw_login', 'gc_claim_req', '成功'),
    flow('gc_f26', 'gc_claim_req', 'gc_claim_input'),
    flow('gc_f27', 'gc_claim_input', 'gc_gw_claim_input'),
    flow('gc_f28', 'gc_gw_claim_input', 'gc_end_claim_input', '否'),
    flow('gc_f29', 'gc_gw_claim_input', 'gc_gw_target', '是'),
    flow('gc_f30', 'gc_gw_target', 'gc_capability', '是'),
    flow('gc_f31', 'gc_capability', 'gc_gw_target_merge'),
    flow('gc_f32', 'gc_gw_target', 'gc_gw_target_merge', '否'),
    flow('gc_f33', 'gc_gw_target_merge', 'gc_receipt'),
    flow('gc_f34', 'gc_receipt', 'gc_gw_receipt'),
    flow('gc_f35', 'gc_gw_receipt', 'gc_end_receipt_409', '幂等冲突'),
    flow('gc_f36', 'gc_gw_receipt', 'gc_register', '无'),
    flow('gc_f37', 'gc_gw_receipt', 'gc_gw_success_merge', '已完成'),
    flow('gc_f38', 'gc_register', 'gc_gw_register'),
    flow('gc_f39', 'gc_gw_register', 'gc_end_register_409', '拒绝'),
    flow('gc_f40', 'gc_gw_register', 'gc_end_register_410', '已过期'),
    flow('gc_f41', 'gc_gw_register', 'gc_gw_lease', '已登记'),
    flow('gc_f42', 'gc_gw_lease', 'gc_end_lease_503', '他人持有'),
    flow('gc_f43', 'gc_gw_lease', 'gc_gw_terminal', '终态'),
    flow('gc_f44', 'gc_gw_lease', 'gc_complete', '取得'),
    flow('gc_f45', 'gc_gw_terminal', 'gc_end_failed_409', '已失败'),
    flow('gc_f46', 'gc_gw_terminal', 'gc_recheck_receipt', '已完成'),
    flow('gc_f47', 'gc_recheck_receipt', 'gc_gw_success_merge'),
    flow('gc_f48', 'gc_complete', 'gc_gw_complete'),
    flow('gc_f49', 'gc_gw_complete', 'gc_end_complete_reject', '拒绝'),
    flow('gc_f50', 'gc_gw_complete', 'gc_end_complete_410', '已过期'),
    flow('gc_f51', 'gc_gw_complete', 'gc_gw_success_merge', '已完成'),
    flow('gc_f52', 'gc_gw_success_merge', 'gc_object_kinds'),
    flow('gc_f53', 'gc_object_kinds', 'gc_end_ok'),
  ],
}
