// DMN 语义来源：cloudfunctions-v2/src/care/** 与 models/care/mvp-watering-policy-release.v3.json（care-watering-mvp/v3；v1/v2 行为单列）。
const S = s => `"${s}"`

export const mvpWatering = {
  id: 'mvp_watering_decisions',
  name: 'MVP 浇水决策（care-watering-mvp/v3，兼容 v1/v2）',
  description: '只读可视化：反映 cloudfunctions-v2/src/care 当前代码中的 MVP 浇水决策构成（assessMvpWatering 组合用例）。数值积分（环境需求、干燥进度、检查窗口时刻、装土体积）由 TypeScript 计算并作为输入数据进入；本文件未接入任何规则引擎，修改它不改变线上行为。参数取自已发布策略 care-watering-mvp/v3（mvp-watering-policy-release.v3.json）；v1/v2 的不同行为在各表规则行中单列。',
  nodes: [
    // ---------- 输入数据 ----------
    { id: 'mvp_input_plant_baseline', kind: 'inputData', col: 1, row: 0, name: '植物名义基线（Tropicals）', variable: 'plant_baseline',
      description: 'readPlantBaseline 读取的 tier、trigger 与 baselineDays；缺失或不受支持为 null。基线天数在策略参考条件下解释为等效干燥单位（合同 §1）。' },
    { id: 'mvp_input_soil_observation', kind: 'inputData', col: 0, row: 2, name: '盆土观察（四态＋范围＋时刻）', variable: 'soil_observation',
      description: 'state ∈ wet|moist|dry|uncertain，scope ∈ surface|root_zone，observedAt ≤ now。HTTP 路径中 buildWateringAdvice 以 reliable=true 传入（请求无来源字段）。' },
    { id: 'mvp_input_last_confirmed_watering', kind: 'inputData', col: 2, row: 2, name: '最近确认实际浇水时刻', variable: 'last_confirmed_watering_at',
      description: '临时案例来自请求 lastWatering；长期植物来自最近一条浇水事实。未知为 null，不补今天、不补零进度。' },
    { id: 'mvp_input_policy_snapshot', kind: 'inputData', col: 4, row: 2, name: '活动浇水策略快照', variable: 'policy_published',
      description: 'readWateringPolicy 读取 business_policy_releases 中 care/mvp_watering 的活动发布；无可用发布为 null（结果为暂不可用，不是错误）。读取器接受 v1/v2/v3；v1/v2 不按盆伸缩、不补缺段、忽略主要材料。' },
    { id: 'mvp_input_measured_pot', kind: 'inputData', col: 8, row: 4, name: '实际种植内盆（确认、尺寸、排水）', variable: 'measured_pot',
      description: 'actualInnerPotConfirmed、drainageAvailable、potTop/BottomDiameterCm、potHeightCm。deriveMeasuredPot：尺寸齐全且合法时 potGeometryValid=true，否则为 null（代码不产生 false）。长期植物取档案实测盆，客户端不得提交。' },
    { id: 'mvp_input_substrate_materials', kind: 'inputData', col: 6, row: 5, name: '基质材料集合', variable: 'substrate_materials',
      description: '9 类代码 general|coco|ceramsite|peat|perlite|bark|sphagnum|gritty|coarse_sand；按集合处理，重复不改变结果，null/undefined 空洞跳过；未知代码抛错。' },
    { id: 'mvp_input_lux_reading', kind: 'inputData', col: 0, row: 7, name: '植物位置 Lux 读数', variable: 'lux_reading',
      description: 'lux、measuredAtMs、source ∈ meter|camera_estimate；可缺失。' },
    { id: 'mvp_input_outdoor_radiation', kind: 'inputData', col: 1, row: 8, name: 'Open-Meteo 辐射序列（GHI）', variable: 'outdoor_radiation',
      description: 'fetchRadiation 标准化后的时段 GHI；Provider 不可用为 null（光照缺段，仍返回 200）。查询窗口：回看至最早证据（≤92 天），预报恒为 16 天。' },
    // ---------- 知识源（已发布策略 v2 的不同章节） ----------
    { id: 'mvp_input_indoor_vpd', kind: 'inputData', col: 3, row: 7, name: '室内 VPD 区间（缺失时用策略兜底 0.7–2.2）', variable: 'indoor_vpd',
      description: '请求 indoorClimate（温度、相对湿度）经 Tetens 公式 0.6108·exp(17.27T/(T+237.3))·(1−RH/100) 得同刻点值，只用于测量后 24 小时内开始的时段；其余时段为 null，由 VPD 包络改用策略兜底区间 indoorVpdFallbackKpa 0.7～2.2kPa（estimate）。不使用室外 VPD，也不用未准入的室外→室内模型。' },
    { id: 'mvp_knowledge_light_response', kind: 'knowledgeSource', col: 0, row: 6, name: '策略 v2/v3 §2 光响应参数',
      description: 'referencePpfd=50、lightHalfSaturationPpfd=75、validPpfd 0～1500（v2、v3 同值）。' },
    { id: 'mvp_knowledge_vpd', kind: 'knowledgeSource', col: 2, row: 8, name: '策略 v2/v3 §2 VPD 参数',
      description: 'referenceVpdKpa=1.4、vpdSensitivity=0.6、validVpdKpa 0.1～4、indoorVpdFallbackKpa 0.7～2.2（v2、v3 同值）。' },
    { id: 'mvp_knowledge_demand', kind: 'knowledgeSource', col: 3, row: 6, name: '策略 v2/v3 §2 蒸腾占比',
      description: 'transpirationShare=0.8（叶片蒸腾项权重；基质蒸发项权重 0.2）。' },
    { id: 'mvp_input_primary_material', kind: 'inputData', col: 8, row: 6, name: '主要材料（体积占一半及以上，可缺失）', variable: 'primary_material',
      description: '请求 primarySubstrateMaterial（2026-10-10 新增）：九类材料代码之一或 null；必须属于所选材料，否则 400 VALIDATION_FAILED（含未选材料却标主要材料）。只在 v3 策略下参与；v1/v2 忽略。' },
    { id: 'mvp_knowledge_reference_pot', kind: 'knowledgeSource', col: 4, row: 5, name: '策略 v3 §8 参考盆与留空高度',
      description: 'referencePot：盆口内径 15、盆底内径 11、内深 13cm（约 1.7L，不透气、有排水孔）；headspaceCm 1～3（两端点分别计算）。' },
    { id: 'mvp_knowledge_cultivation', kind: 'knowledgeSource', col: 3, row: 5, name: '策略 v3 §8 参考物性与兜底存量比',
      description: 'referenceAvailableWater=0.30（参考泥炭类可用水 AW，Bilderback 2005 口径 CC−θ(1500kPa)，定义锚点用点值）；plantDemandVolumeExponent b=[0, 0.52]（Poorter 2012：盆容积翻倍生物量 +43%）；cultivationRetention 0.8～1.25 在 v3 中语义收窄为“缺几何或缺基质时的兜底存量比”。' },
    { id: 'mvp_knowledge_gap_fill', kind: 'knowledgeSource', col: 1, row: 5, name: '缺段补齐硬规则 6h',
      description: 'MVP_DRYING_GAP_FILL_MAX_HOURS=6（配置目录 care.watering.drying_gap_fill_max_hours，hard_rule，合同 §8.11）：证据连续性的准入边界，不随策略发布调整。' },
    { id: 'mvp_annotation_wall_evaporation', kind: 'textAnnotation', col: 5, row: 5,
      text: '盆壁蒸发 κ（素烧陶等透气盆壁）：未纳入模型，待验证票 z8v0kmvewm；当前所有盆按不透气盆壁计算。' },
    { id: 'mvp_knowledge_soil_fraction', kind: 'knowledgeSource', col: 1, row: 1, name: '策略 v2/v3 §3 盆土剩余比例',
      description: 'remainingFraction：wet 0.6～1.0、moist 0.25～0.6、surfaceDryOnly 0～0.5（v2、v3 同值）。' },
    { id: 'mvp_knowledge_soil_validity', kind: 'knowledgeSource', col: 0, row: 3, name: '策略 v2/v3 §3a 盆土有效期',
      description: 'soilEvidenceFallbackHours=24、soilEvidenceMaxHours=72（用户 2026-10-09 裁决 U6）；v1 为固定 soilEvidenceTtlHours。' },
    { id: 'mvp_knowledge_light', kind: 'knowledgeSource', col: 0, row: 8, name: '策略 v2/v3 §2a 光照锚点参数',
      description: 'luxPerPpfd 50～58、luxAnchorMinGhiWm2=50、luxUncertainty meter 0.1 / camera_estimate 0.3、luxAnchorMaxAgeDays=30；PPFD/GHI 上限 2.3 为代码常量。' },
    { id: 'mvp_knowledge_substrates', kind: 'knowledgeSource', col: 5, row: 6, name: '策略 v2/v3 §4 基质物性',
      description: '各材料容器持水量 containerCapacity 与可用水 availableWater 区间（v2、v3 同值）。' },
    { id: 'mvp_knowledge_amount', kind: 'knowledgeSource', col: 6, row: 0, name: '策略 v2/v3 §4 水量参数',
      description: 'depletion：keep_moist 0.15～0.25、surface_dry 0.25～0.35、dry_wet 0.45～0.55、full_dry 0.7～0.85；headspaceCm 1～3；leachingFraction 0.1～0.2。' },
    // ---------- 决策 ----------
    { id: 'mvp_decision_moisture_group', kind: 'decision', col: 2, row: 0, name: '湿度分组', requires: ['mvp_input_plant_baseline'],
      description: 'resolveMvpMoistureGroup：Tropicals tier＋trigger → 四类“浇水前允许干到什么程度”。无基线时 assessMvpWatering 直接返回 insufficient_evidence（plant_baseline）。未知 tier/trigger 抛 TypeError（无匹配规则）。合同 §3 已于 2026-10-09 按用户裁决与代码对齐：DROUGHT_SIGNAL 归 full_dry（必须干透）；TIER_DEFAULT 按来源 tier 映射，occasional/drought_tolerant 需看根区。§4 消耗比例按本决策输出的湿度分组查。',
      table: { hitPolicy: 'UNIQUE',
        inputs: [
          { label: '有基线', expr: 'plant_baseline != null', type: 'boolean' },
          { label: '来源 tier', expr: 'plant_baseline.tier', type: 'string' },
          { label: '触发语义 trigger', expr: 'plant_baseline.trigger', type: 'string' },
        ],
        outputs: [
          { name: 'moisture_group', label: '湿度分组', type: 'string' },
          { name: 'surface_sufficient', label: '表土即可判定目标', type: 'boolean' },
        ],
        rules: [
          [['false', '-', '-'], ['null', 'null'], '无基线：不解析分组，整体结果 insufficient_evidence'],
          [['true', '"constant_moisture","regular","occasional","drought_tolerant"', '"KEEP_WET","KEEP_MOIST"'], [S('keep_moist'), 'true'], '明确触发语义优先'],
          [['true', '"constant_moisture","regular","occasional","drought_tolerant"', '"SURFACE_DRY"'], [S('surface_dry'), 'true'], null],
          [['true', '"constant_moisture","regular","occasional","drought_tolerant"', '"DRY_WET"'], [S('dry_wet'), 'false'], null],
          [['true', '"constant_moisture","regular","occasional","drought_tolerant"', '"FULL_DRY","VERY_DRY","DROUGHT_SIGNAL"'], [S('full_dry'), 'false'], null],
          [['true', '"constant_moisture"', '"TIER_DEFAULT"'], [S('keep_moist'), 'true'], 'TIER_DEFAULT 按来源 tier 保守对应'],
          [['true', '"regular"', '"TIER_DEFAULT"'], [S('surface_dry'), 'true'], null],
          [['true', '"occasional"', '"TIER_DEFAULT"'], [S('dry_wet'), 'false'], null],
          [['true', '"drought_tolerant"', '"TIER_DEFAULT"'], [S('full_dry'), 'false'], null],
        ] } },
    { id: 'mvp_decision_light_response', kind: 'decision', col: 1, row: 6,
      name: '光响应', requires: ['mvp_decision_plant_light_anchor', 'mvp_knowledge_light_response'],
      description: '由 TypeScript 逐时段计算（assessMvpWatering.lightResponse）：L(q)=q/(q+k)，k=75；相对参考 L_rel=L(q)/L(qref)，qref=50 → L(qref)=0.4。夜间 q=0 时叶片项为 0。超出有效域的时段为缺段，不钳制。',
      table: { hitPolicy: 'FIRST',
        inputs: [
          { label: '时段 PPFD 有值', expr: 'segment.ppfd != null', type: 'boolean' },
          { label: 'PPFD 在 0～1500 内', expr: 'segment.ppfd.min >= 0 and segment.ppfd.max <= 1500', type: 'boolean' },
        ],
        outputs: [
          { name: 'light_segment_status', label: '时段状态', type: 'string' },
          { name: 'light_response_rule', label: '光响应（TypeScript 计算）', type: 'string' },
        ],
        rules: [
          [['false', '-'], [S('missing'), 'null'], '缺段'],
          [['true', 'false'], [S('missing'), 'null'], '超出 validPpfd：缺段，不钳制'],
          [['true', 'true'], [S('ok'), '"L_rel = [q.min/(q.min+75), q.max/(q.max+75)] ÷ 0.4"'], null],
        ] } },
    { id: 'mvp_decision_vpd_envelope', kind: 'decision', col: 2, row: 7,
      name: 'VPD 包络', requires: ['mvp_input_indoor_vpd', 'mvp_knowledge_vpd'],
      description: '由 TypeScript 逐时段计算（assessMvpWatering.vaporFlux / vaporEnvelope）：H(D)=r·max(0, 1−s·ln r)，r=D/Dref，Dref=1.4kPa，s=0.6；D=0 时 H=0。区间包络取两端点的最小、最大值；H 在 D*=Dref·e^(1/s−1)≈2.73kPa 处取峰值（≈1.169），D* 落在区间内时最大值必须计入峰值。兜底区间 0.7～2.2 不含峰值，包络 ≈[H(0.7)=0.708, H(2.2)=1.145]。',
      table: { hitPolicy: 'FIRST',
        inputs: [
          { label: '有室内实测 VPD', expr: 'indoor_vpd != null', type: 'boolean' },
          { label: '所用 VPD 在 0.1～4 内', expr: 'vpd.min >= 0.1 and vpd.max <= 4', type: 'boolean' },
        ],
        outputs: [
          { name: 'vpd_segment_status', label: '时段状态', type: 'string' },
          { name: 'vpd_range', label: '所用 VPD 区间', type: 'string' },
          { name: 'vapor_envelope_rule', label: 'H 包络（TypeScript 计算）', type: 'string' },
        ],
        rules: [
          [['-', 'false'], [S('missing'), 'null', 'null'], '超出 validVpdKpa：缺段，不钳制'],
          [['true', 'true'], [S('ok'), '"室内实测（点值）"', '"[min(H(D.min),H(D.max)), max(H(D.min),H(D.max), 区间含 2.73 时加 H(2.73))]"'], null],
          [['false', 'true'], [S('ok'), '"[0.7, 2.2]（策略兜底，estimate）"', '"[0.708, 1.145]（峰值不在区间内）"'], '无实测时用兜底区间'],
        ] } },
    { id: 'mvp_decision_environment_demand', kind: 'decision', col: 2, row: 6,
      name: '环境需水强度', requires: ['mvp_decision_light_response', 'mvp_decision_vpd_envelope', 'mvp_decision_cultivation_retention', 'mvp_knowledge_demand'],
      description: '由 TypeScript 逐时段计算（assessMvpWatering.environmentDemand）：每参考日的相对环境干燥需求区间（代理指标，不是实测耗水毫升数）；v3 起叶片项乘植物需求比 P、基质蒸发项乘蒸发面比 Ae（区间端点同向相乘；v1/v2 与缺证据时 P=Ae=1）。夜间蒸腾未建模（低估方向，已记录）。任一分量缺段 → 该时段从干燥时段清单中丢弃。',
      table: { hitPolicy: 'FIRST',
        inputs: [
          { label: '光响应时段状态', expr: 'light_segment_status', type: 'string' },
          { label: 'VPD 时段状态', expr: 'vpd_segment_status', type: 'string' },
        ],
        outputs: [
          { name: 'demand_segment_status', label: '时段状态', type: 'string' },
          { name: 'environment_demand_rule', label: '需水强度（TypeScript 计算）', type: 'string' },
        ],
        rules: [
          [['"missing"', '-'], [S('dropped'), 'null'], '时段丢弃'],
          [['-', '"missing"'], [S('dropped'), 'null'], '时段丢弃'],
          [['"ok"', '"ok"'], [S('ok'), '"Demand_pot = 0.8 × L_rel × H × P + 0.2 × D/1.4 × Ae（min 取各下端，max 取各上端）"'], '叶片蒸腾项 × 0.8 + 基质蒸发项（道尔顿关系 D/Dref）× 0.2'],
        ] } },
    { id: 'mvp_decision_pot_volume_ratio', kind: 'decision', col: 4, row: 4,
      name: '盆体积比', requires: ['mvp_input_measured_pot', 'mvp_knowledge_reference_pot'],
      description: '由 TypeScript 计算（deriveCultivationDrying + frustumFillGeometry，合同 §8.4）：对留空高度两端点 s∈{1, 3}cm，实际盆与参考盆用同一个 s。f=H−s，R_f=r+(R−r)·f/H，V(s)=π·f·(R_f²+R_f·r+r²)/3，A_top(s)=π·R_f²；体积比 v(s)=V/V_ref、土表面积比 A(s)=A_top/A_top,ref，各取两端点包络。排水条件不影响本推导（由盆器安全门独立裁决）。',
      table: { hitPolicy: 'FIRST',
        inputs: [
          { label: '实际内盆已确认', expr: 'measured_pot.actualInnerPotConfirmed = true', type: 'boolean' },
          { label: '三项尺寸齐全', expr: 'measured_pot.potTopDiameterCm != null and measured_pot.potBottomDiameterCm != null and measured_pot.potHeightCm != null', type: 'boolean' },
          { label: '盆高大于留空上限 3cm', expr: 'measured_pot.potHeightCm > 3', type: 'boolean' },
        ],
        outputs: [
          { name: 'pot_geometry_status', label: '几何状态', type: 'string' },
          { name: 'volume_ratio_rule', label: '体积比 v（TypeScript 计算）', type: 'string' },
          { name: 'surface_area_ratio_rule', label: '土表面积比 A（TypeScript 计算）', type: 'string' },
        ],
        rules: [
          [['false', '-', '-'], [S('fallback'), 'null', 'null'], '未确认实际内盆'],
          [['true', 'false', '-'], [S('fallback'), 'null', 'null'], '几何不全'],
          [['true', 'true', 'false'], [S('fallback'), 'null', 'null'], '装不了土：不猜装土高度'],
          [['true', 'true', 'true'], [S('measured'), '"[min_s V(s)/V_ref(s), max_s V(s)/V_ref(s)]，参考盆 15/11/13cm"', '"[min_s A_top(s)/A_top,ref(s), max_s A_top(s)/A_top,ref(s)]"'], null],
        ] } },
    { id: 'mvp_decision_substrate_available_water', kind: 'decision', col: 7, row: 6,
      name: '基质可用水（主要材料规则）', requires: ['mvp_decision_substrate_properties', 'mvp_input_substrate_materials', 'mvp_input_primary_material'],
      description: 'combineMvpSubstrateMix（合同 §8.10）：可用水（AW）采用 Bilderback 2005 口径 AW = 容器持水量 CC − θ(1500kPa)，不是 De Boodt 的易利用水 EAW。配比未知，按体积线性混合近似。主要材料 = 体积占比 ≥ 一半。同一规则同时用于干燥存量（可用水）与水量估算（可用水、容器持水量上限）。材料代码未知或主要材料不属于所选材料时拒绝（请求阶段已 400）。',
      table: { hitPolicy: 'FIRST',
        inputs: [
          { label: '已选材料', expr: 'count(substrate_materials) > 0', type: 'boolean' },
          { label: '策略为 v3 且标了主要材料', expr: 'policy.contractVersion = "care-watering-mvp/v3" and primary_material != null', type: 'boolean' },
          { label: '还有其余组分', expr: 'count(substrate_materials) > 1', type: 'boolean' },
        ],
        outputs: [
          { name: 'mix_rule', label: '混合规则', type: 'string' },
          { name: 'available_water_rule', label: '可用水（AW）区间（TypeScript 计算）', type: 'string' },
        ],
        rules: [
          [['false', '-', '-'], [S('none'), 'null'], '未选基质'],
          [['true', 'true', 'false'], [S('primary_only'), '"主材料区间"'], '只选一种：与未标相同'],
          [['true', 'true', 'true'], [S('primary_mix'), '"[min(p.min, ½·p.min + ½·O_min), max(p.max, ½·p.max + ½·O_max)]，O 为其余组分的最小下端 / 最大上端"'], '主材料区间 ∪ 主材料与最极端其余组分对半混合区间'],
          [['true', 'false', '-'], [S('union'), '"[min_i AW_i.min, max_i AW_i.max]"'], '未标主要材料（或 v1/v2）：各组分并集'],
        ] } },
    { id: 'mvp_decision_cultivation_retention', kind: 'decision', col: 3, row: 4,
      name: '栽培干燥倍率', requires: ['mvp_decision_pot_volume_ratio', 'mvp_decision_substrate_available_water', 'mvp_knowledge_cultivation'],
      description: 'cultivationDrying / deriveCultivationDrying（合同 §8.4～§8.6）：存量比 S 写入 DryingInterval.cultivationRetention（原“保水倍率”含义收窄为存量比）；植物需求比 P 只乘叶片项，蒸发面比 Ae 只乘基质蒸发项。参考盆＋泥炭：v=1、P=Ae=1、S≈[0.833, 1.167]。策略版本取活动策略快照 policy.contractVersion。',
      table: { hitPolicy: 'FIRST',
        inputs: [
          { label: '策略为 v3', expr: 'policy.contractVersion = "care-watering-mvp/v3"', type: 'boolean' },
          { label: '几何状态', expr: 'pot_geometry_status', type: 'string' },
          { label: '有可用水区间', expr: 'mix_rule != "none"', type: 'boolean' },
        ],
        outputs: [
          { name: 'storage_ratio', label: '存量比 S', type: 'string' },
          { name: 'plant_demand_scale', label: '植物需求比 P', type: 'string' },
          { name: 'evaporation_area_scale', label: '蒸发面比 Ae', type: 'string' },
          { name: 'cultivation_basis', label: '依据', type: 'string' },
        ],
        rules: [
          [['false', '-', '-'], ['"[0.8, 1.25]"', '"1"', '"1"', S('fallback')], 'v1/v2：固定保水带，需求不按盆伸缩'],
          [['true', '"fallback"', '-'], ['"[0.8, 1.25]"', '"1"', '"1"', S('fallback')], '几何不全、未确认内盆或装不了土'],
          [['true', '"measured"', 'false'], ['"[0.8, 1.25]"', '"1"', '"1"', S('fallback')], '未选基质：缺持水依据时不默认 S=1'],
          [['true', '"measured"', 'true'], ['"[v.min × AW.min ÷ 0.3, v.max × AW.max ÷ 0.3]"', '"包络{ v^b ：v ∈ {v.min, v.max}，b ∈ {0, 0.52} }"', '"[A.min, A.max]（土表面积比）"', S('measured')], null],
        ] } },
    { id: 'mvp_decision_gap_fill', kind: 'decision', col: 2, row: 5,
      name: '缺段补齐', requires: ['mvp_decision_environment_demand', 'mvp_knowledge_gap_fill'],
      description: 'fillMvpDryingGaps（合同 §8.11，v3 起）：缺段 = 两个有效时段之间的时间空洞（时段缺失，或 PPFD 缺失、PPFD/VPD 超出有效域被丢弃；连续的合并计时）。补齐用的保守需求 = 有效域 PPFD 0～1500、VPD 0.1～4（含 H 峰值）代入需求公式的全区间包络，同样乘 P/Ae。',
      table: { hitPolicy: 'FIRST',
        inputs: [
          { label: '策略为 v3', expr: 'policy.contractVersion = "care-watering-mvp/v3"', type: 'boolean' },
          { label: '缺口位置', expr: 'gap.position', type: 'string' },
          { label: '缺口总时长（小时）', expr: 'gap.durationHours', type: 'number' },
        ],
        outputs: [
          { name: 'gap_action', label: '处理', type: 'string' },
          { name: 'filled_demand_rule', label: '补齐需求（TypeScript 计算）', type: 'string' },
        ],
        rules: [
          [['false', '-', '-'], [S('keep_gap'), 'null'], 'v1/v2 不补，保持已发布语义可复算'],
          [['true', '"leading","trailing"', '-'], [S('keep_gap'), 'null'], '首个有效时段之前、最后一个之后（预报覆盖终点）不补'],
          [['true', '"internal"', '<= 6'], [S('fill'), '"Demand 取 PPFD [0, 1500]、VPD [0.1, 4] 上的最低～最高包络（× P / Ae）"'], '窗口变宽但不中断'],
          [['true', '"internal"', '> 6'], [S('keep_gap'), 'null'], '保持空洞：历史 → history_gap；未来 → 覆盖终点'],
        ] } },
    { id: 'mvp_decision_drying_progress', kind: 'decision', col: 2, row: 4,
      name: '逐时段干燥进度累积', requires: ['mvp_input_last_confirmed_watering', 'mvp_decision_gap_fill', 'mvp_decision_cultivation_retention', 'mvp_input_plant_baseline'],
      description: '由 TypeScript 计算（replayDryProgress / integrateDryingFromAnchor，积分内核不变）。每个时段的干燥速率 rate = Demand_pot × 个体校准 ÷ S = [Demand_pot.min ÷ S.max, Demand_pot.max ÷ S.min]（个体校准固定 [1,1]），进度 += rate × 时长 ÷ 24h，单位为等效干燥日；目标为基线 baselineDays（定义在参考盆下）。缺段先经“缺段补齐”：v3 起 ≤6h 的内部空洞已补上；仍留下的空洞（>6h、首段之前，或 v1/v2 的任一缺段）——起点到现在之间有空洞则整段进度为空（history_gap），未来方向遇空洞即停止（覆盖终点），窗口端点保持为空。同一组速率另用于：盆土有效期（湿/微湿最早离开状态时刻）和观察起点剩余量预测（replayObservedDryCycle）。',

      table: { hitPolicy: 'FIRST',
        inputs: [
          { label: '有基线', expr: 'plant_baseline != null', type: 'boolean' },
          { label: '有最近确认浇水', expr: 'last_confirmed_watering_at != null', type: 'boolean' },
          { label: '起点至今时段连续（补齐后）', expr: 'noGap(last_confirmed_watering_at, now)', type: 'boolean' },
        ],
        outputs: [
          { name: 'progress_status', label: '历史进度状态', type: 'string' },
          { name: 'progress_rule', label: '进度（TypeScript 计算）', type: 'string' },
          { name: 'window_rule', label: '预测窗口（TypeScript 计算）', type: 'string' },
        ],
        rules: [
          [['false', '-', '-'], [S('missing_baseline'), 'null', 'null'], '实际在 assessMvpWatering 前置出口已返回'],
          [['true', 'false', '-'], [S('missing_origin'), 'null', 'null'], '无起点不补今天、不补零'],
          [['true', 'true', 'false'], [S('history_gap'), 'null', 'null'], '补齐后仍有空洞（v3 >6h；v1/v2 任一缺段）：整段进度为空'],
          [['true', 'true', 'true'], [S('ready_candidate'), '"progress = Σ [Demand_pot.min ÷ S.max, Demand_pot.max ÷ S.min] × Δt ÷ 24h（自最近确认浇水）"', '"沿未来连续时段继续累积：进度上界 ≥ 基线下界 → 最早检查；进度下界 ≥ 基线上界 → 最晚检查；遇空洞停止（coverageEnd）"'], null],
        ] } },
    { id: 'mvp_decision_soil_validity', kind: 'decision', col: 1, row: 2,
      name: '盆土证据有效期', requires: ['mvp_input_soil_observation', 'mvp_input_last_confirmed_watering', 'mvp_decision_drying_progress', 'mvp_knowledge_soil_validity'],
      description: 'resolveMvpSoilEvidenceValidUntil（长期植物与临时案例同规则）。返回值严格晚于观察时刻；uncertain 或无观察不计算。结果作为 validUntil 进入盆土观察映射。',
      table: { hitPolicy: 'UNIQUE',
        inputs: [
          { label: '策略合同版本', expr: 'policy.contractVersion', type: 'string' },
          { label: '观察状态', expr: 'soil_observation.state', type: 'string' },
          { label: '能推出最早离开该状态时刻', expr: 'drying_progress.leaveStateAtComputable', type: 'boolean' },
          { label: '观察后有已确认浇水', expr: 'last_confirmed_watering_at > soil_observation.observedAt', type: 'boolean' },
        ],
        outputs: [{ name: 'soil_valid_until_rule', label: '有效截止时刻规则', type: 'string' }],
        rules: [
          [['-', '"uncertain",null', '-', '-'], ['null'], '不形成证据，不计算有效期'],
          [['"care-watering-mvp/v1"', '"wet","moist","dry"', '-', '-'], ['"observedAt + soilEvidenceTtlHours"'], 'v1 固定 TTL（已视为缺陷，仍兼容读取）'],
          [['"care-watering-mvp/v2","care-watering-mvp/v3"', '"wet","moist"', 'true', '-'], ['"min(最早离开状态时刻, observedAt + 72h)"'], '以最快干燥速率消耗 (剩余比例上界−下界)×基线下端 所需时间'],
          [['"care-watering-mvp/v2","care-watering-mvp/v3"', '"wet","moist"', 'false', '-'], ['"observedAt + 24h"'], '推不出（缺光照/环境段或不连续覆盖）→ 回退小时'],
          [['"care-watering-mvp/v2","care-watering-mvp/v3"', '"dry"', '-', 'true'], ['"min(该次浇水时刻, observedAt + 72h)"'], '干（含仅表土干）有效到晚于观察的已确认浇水'],
          [['"care-watering-mvp/v2","care-watering-mvp/v3"', '"dry"', '-', 'false'], ['"observedAt + 72h"'], '统一封顶'],
        ] } },
    { id: 'mvp_decision_soil_mapping', kind: 'decision', col: 2, row: 1,
      name: '盆土观察映射', requires: ['mvp_decision_moisture_group', 'mvp_input_soil_observation', 'mvp_decision_soil_validity', 'mvp_knowledge_soil_fraction'],
      description: 'mapMvpSoilObservation（合同 §3）：四态观察 → 安全门证据（state/scope/reliable/targetCriteriaConfirmed/collectedAt/validUntil）与观察时刻剩余等效干燥量 = 剩余比例 × 基线。不识别照片、不提升可靠性。',
      table: { hitPolicy: 'UNIQUE',
        inputs: [
          { label: '观察状态', expr: 'soil_observation.state', type: 'string' },
          { label: '观察范围', expr: 'soil_observation.scope', type: 'string' },
          { label: '表土即可判定目标', expr: 'surface_sufficient', type: 'boolean' },
        ],
        outputs: [
          { name: 'evidence_state', label: '证据状态', type: 'string' },
          { name: 'target_criteria_confirmed', label: '已达目标干燥', type: 'boolean' },
          { name: 'remaining_fraction_min', label: '剩余比例下界', type: 'number' },
          { name: 'remaining_fraction_max', label: '剩余比例上界', type: 'number' },
        ],
        rules: [
          [['null', '-', '-'], ['null', 'null', 'null', 'null'], '无观察'],
          [['"uncertain"', '-', '-'], ['null', 'null', 'null', 'null'], '不确定观察不形成证据'],
          [['"wet"', '-', '-'], [S('wet'), 'false', '0.6', '1.0'], '湿 → 安全门暂停浇水'],
          [['"moist"', '-', '-'], [S('unknown'), 'false', '0.25', '0.6'], null],
          [['"dry"', '"root_zone"', '-'], [S('target_dry'), 'true', 'null', 'null'], '根区干：达到目标，不生成剩余量'],
          [['"dry"', '"surface"', 'true'], [S('target_dry'), 'true', 'null', 'null'], '表土干且分组接受表土'],
          [['"dry"', '"surface"', 'false'], [S('unknown'), 'false', '0', '0.5'], '仅表土干但分组需要根区'],
        ] } },
    { id: 'mvp_decision_current_cycle_window', kind: 'decision', col: 3, row: 2,
      name: '本轮检查窗口来源', requires: ['mvp_decision_soil_mapping', 'mvp_input_last_confirmed_watering', 'mvp_decision_drying_progress'],
      description: 'resolveCurrentDryWindow＋replayWateringTiming：决定本轮窗口取自观察、历史预测还是被当前证据覆盖。“当前根区证据”= reliable 且 scope=root_zone 且 collectedAt ≤ now < validUntil。观察预测仅在根区、当前有效、晚于最近浇水且积分覆盖时可用（replayObservedDryCycle）。',
      table: { hitPolicy: 'FIRST',
        inputs: [
          { label: '观察不晚于最近确认浇水', expr: 'soil_observation.observedAt <= last_confirmed_watering_at', type: 'boolean' },
          { label: '当前根区证据', expr: 'evidence_scope = "root_zone" and now < soil_valid_until', type: 'boolean' },
          { label: '证据状态', expr: 'evidence_state', type: 'string' },
          { label: '已达目标干燥', expr: 'target_criteria_confirmed', type: 'boolean' },
          { label: '所用预测最早检查时刻已到', expr: 'drying_progress.earliestCheckReached', type: 'boolean' },
          { label: '观察预测可用', expr: 'drying_progress.observationPredictionReady', type: 'boolean' },
          { label: '历史预测窗口存在', expr: 'drying_progress.historyWindowAvailable', type: 'boolean' },
        ],
        outputs: [
          { name: 'current_window_status', label: '窗口来源', type: 'string' },
          { name: 'observation_ignored', label: '观察属上一轮（被忽略）', type: 'boolean' },
        ],
        rules: [
          [['true', '-', '-', '-', '-', '-', 'true'], [S('prediction_only'), 'true'], '观察早于最近浇水，不能证明本轮状态'],
          [['true', '-', '-', '-', '-', '-', 'false'], [S('insufficient_evidence'), 'true'], null],
          [['false', 'true', '"target_dry"', 'true', '-', '-', '-'], [S('target_observed'), 'false'], '根区已达目标：窗口=now（不等于已浇水）'],
          [['false', 'true', '"wet"', '-', 'true', '-', '-'], [S('prediction_conflict'), 'false'], '预测已到但当前根区仍湿：不输出猜测日期'],
          [['-', '-', '-', '-', '-', 'true', '-'], [S('observation_prediction'), 'false'], '从观察时刻独立积分'],
          [['-', '-', '-', '-', '-', '-', 'true'], [S('prediction_only'), 'false'], '仅历史预测'],
          [['-', '-', '-', '-', '-', '-', '-'], [S('insufficient_evidence'), 'false'], null],
        ] } },
    { id: 'mvp_decision_soil_gate', kind: 'decision', col: 4, row: 1,
      name: '盆土安全门', requires: ['mvp_decision_soil_mapping', 'mvp_decision_current_cycle_window'],
      description: 'evaluateWateringDecision 的 soilGate：可靠且未过期的湿土优先暂停；是否达到目标由上游映射按植物触发条件判定（用户 2026-10-08 裁决），安全门不再额外要求根区。观察属上一轮时 replayWateringTiming 以 soil=null 重新裁决。',
      table: { hitPolicy: 'FIRST',
        inputs: [
          { label: '观察属上一轮', expr: 'observation_ignored', type: 'boolean' },
          { label: '证据未过期', expr: 'now < soil_valid_until', type: 'boolean' },
          { label: '证据状态', expr: 'evidence_state', type: 'string' },
          { label: '已达目标干燥', expr: 'target_criteria_confirmed', type: 'boolean' },
        ],
        outputs: [{ name: 'soil_safety_gate', label: '盆土安全门', type: 'string' }],
        rules: [
          [['true', '-', '-', '-'], [S('unknown')], '上一轮观察不参与本轮裁决'],
          [['false', 'true', '"wet","waterlogged"', '-'], [S('pause_watering')], '可靠湿土或积水优先否决（MVP 映射只产生 wet）'],
          [['false', 'true', '"target_dry"', 'true'], [S('target_dry_confirmed')], null],
          [['-', '-', '-', '-'], [S('unknown')], '缺少可靠当前证据，不自动放行'],
        ] } },
    { id: 'mvp_decision_drying_window_state', kind: 'decision', col: 4, row: 3,
      name: '干燥窗口状态', requires: ['mvp_decision_current_cycle_window', 'mvp_decision_drying_progress'],
      description: 'evaluateWateringDecision 的 windowState：历史进度区间与基线区间比较；观察预测只看最早检查时刻；当前证据覆盖预测时不给窗口。',
      table: { hitPolicy: 'FIRST',
        inputs: [
          { label: '窗口来源', expr: 'current_window_status', type: 'string' },
          { label: '历史进度相对基线', expr: 'drying_progress.progressPosition', type: 'string' },
          { label: '观察预测最早检查时刻', expr: 'drying_progress.observationEarliest', type: 'string' },
        ],
        outputs: [{ name: 'drying_window_state', label: '窗口状态', type: 'string' }],
        rules: [
          [['"target_observed","prediction_conflict"', '-', '-'], ['null'], '当前证据覆盖预测'],
          [['"observation_prediction"', '-', '"none"'], ['null'], null],
          [['"observation_prediction"', '-', '"future"'], [S('before')], null],
          [['"observation_prediction"', '-', '"reached"'], [S('uncertain')], '最早端已到只意味着需要检查'],
          [['-', '"below_baseline"', '-'], [S('before')], 'progress.max < baseline.min'],
          [['-', '"above_baseline"', '-'], [S('overdue')], 'progress.min > baseline.max'],
          [['-', '"inside_baseline"', '-'], [S('within')], null],
          [['-', '"straddles_baseline"', '-'], [S('uncertain')], '跨阈值保留不确定'],
          [['-', '-', '-'], ['null'], '无起点或积分缺段：不猜测窗口'],
        ] } },
    { id: 'mvp_decision_pot_safety', kind: 'decision', col: 5, row: 4,
      name: '盆器安全', requires: ['mvp_input_measured_pot'],
      description: 'evaluatePotSafety（经 deriveMeasuredPot）：实际内盆三值安全判断。',
      table: { hitPolicy: 'UNIQUE',
        inputs: [
          { label: '实际内盆已确认', expr: 'measured_pot.actualInnerPotConfirmed', type: 'boolean' },
          { label: '尺寸合法', expr: 'potGeometryValid', type: 'boolean' },
          { label: '有排水', expr: 'measured_pot.drainageAvailable', type: 'boolean' },
        ],
        outputs: [{ name: 'pot_safety', label: '盆器安全', type: 'string' }],
        rules: [
          [['false,null', '-', '-'], [S('insufficient_evidence')], '装饰外盆不能替代实际内盆'],
          [['true', 'false,null', '-'], [S('insufficient_evidence')], '尺寸缺失或非法'],
          [['true', 'true', 'false'], [S('drainage_risk')], '无孔或排水受阻'],
          [['true', 'true', 'null'], [S('insufficient_evidence')], '排水证据缺失'],
          [['true', 'true', 'true'], [S('safe')], null],
        ] } },
    { id: 'mvp_decision_plant_light_anchor', kind: 'decision', col: 1, row: 7,
      name: '植物位置光照锚点与 PPFD 时段序列', requires: ['mvp_input_lux_reading', 'mvp_input_outdoor_radiation', 'mvp_knowledge_light'],
      description: 'deriveMvpPlantLightIntervals（合同 §2a 单通道比例法）：PPFD(h)=Lux 换算区间×GHI(h)÷GHI(测量时段)。可用时产出“植物位置 PPFD 时段序列”（每个 Open-Meteo 时段一个 PPFD 区间；GHI 缺失的时段不产出）及测量后 24 小时内的室内实测 VPD，交给光响应；不可用时环境时段为空。原因只写入内部 derivations，不进入公开结果。策略或辐射缺失时 buildWateringAdvice 不计算（not_computed）。',
      table: { hitPolicy: 'FIRST',
        inputs: [
          { label: '辐射序列可用', expr: 'outdoor_radiation != null', type: 'boolean' },
          { label: '有 Lux 读数', expr: 'lux_reading != null', type: 'boolean' },
          { label: '读数天龄', expr: '(now - lux_reading.measuredAt) / 1d', type: 'number' },
          { label: '测量时段 GHI(W/m²)', expr: 'anchorInterval.ghi', type: 'number' },
          { label: '换算 PPFD 下界超过 2.3×GHI', expr: 'measured.min > anchorGhi * 2.3', type: 'boolean' },
        ],
        outputs: [
          { name: 'plant_light_status', label: '光照状态', type: 'string' },
          { name: 'plant_light_reason', label: '不可用原因', type: 'string' },
        ],
        rules: [
          [['false', '-', '-', '-', '-'], [S('not_computed'), 'null'], 'Provider 不可用或无策略'],
          [['true', 'false', '-', '-', '-'], [S('insufficient_evidence'), S('light_reading')], null],
          [['true', 'true', '> 30', '-', '-'], [S('insufficient_evidence'), S('light_reading_stale')], '早于 luxAnchorMaxAgeDays'],
          [['true', 'true', '-', 'null', '-'], [S('insufficient_evidence'), S('anchor_radiation')], '测量时刻无 GHI 时段'],
          [['true', 'true', '-', '< 50', '-'], [S('insufficient_evidence'), S('anchor_too_dark')], '天色太暗，比例不可信'],
          [['true', 'true', '-', '-', 'true'], [S('insufficient_evidence'), S('anchor_inconsistent')], '读数不合理'],
          [['true', 'true', '-', '-', '-'], [S('available'), 'null'], '不确定度 meter ±10% / camera_estimate ±30%，换算 50～58 lux/PPFD'],
        ] } },
    { id: 'mvp_decision_watering_action', kind: 'decision', col: 5, row: 2,
      name: '浇水行动（是否可浇水门）', requires: ['mvp_input_policy_snapshot', 'mvp_decision_moisture_group', 'mvp_decision_soil_gate', 'mvp_decision_drying_window_state', 'mvp_decision_pot_safety'],
      description: 'assessMvpWatering 前置出口＋evaluateWateringDecision 最终行动（按顺序命中）。允许浇水不等于已发生浇水；不写计划、事实或提醒。',
      table: { hitPolicy: 'FIRST',
        inputs: [
          { label: '有活动策略', expr: 'policy_published != null', type: 'boolean' },
          { label: '湿度分组', expr: 'moisture_group', type: 'string' },
          { label: '盆土安全门', expr: 'soil_safety_gate', type: 'string' },
          { label: '盆器安全', expr: 'pot_safety', type: 'string' },
          { label: '窗口状态', expr: 'drying_window_state', type: 'string' },
        ],
        outputs: [
          { name: 'watering_action', label: '浇水行动', type: 'string' },
          { name: 'direct_missing_evidence', label: '前置缺失证据', type: 'string' },
        ],
        rules: [
          [['false', '-', '-', '-', '-'], [S('temporarily_unavailable'), S('published_watering_model')], '无发布：不启用旧算法'],
          [['true', 'null', '-', '-', '-'], [S('insufficient_evidence'), S('plant_baseline')], '无基线'],
          [['true', '-', '"pause_watering"', '-', '-'], [S('pause_watering'), 'null'], '湿土优先'],
          [['true', '-', '-', '"drainage_risk"', '-'], [S('review_drainage'), 'null'], null],
          [['true', '-', '-', '"insufficient_evidence"', '-'], [S('insufficient_evidence'), 'null'], '盆器证据不足'],
          [['true', '-', '"target_dry_confirmed"', '"safe"', '-'], [S('water_allowed'), 'null'], null],
          [['true', '-', '-', '-', '"before"'], [S('check_later'), 'null'], null],
          [['true', '-', '-', '-', '"overdue"'], [S('priority_check'), 'null'], '预测超窗不代表已缺水'],
          [['true', '-', '-', '-', '"within","uncertain"'], [S('check_now'), 'null'], null],
          [['true', '-', '-', '-', '-'], [S('insufficient_evidence'), 'null'], null],
        ] } },
    { id: 'mvp_decision_substrate_properties', kind: 'decision', col: 6, row: 6,
      name: '基质物性', requires: ['mvp_input_substrate_materials', 'mvp_knowledge_substrates'],
      description: '按单一材料查已发布物性（v2、v3 同值）；多材料的混合由“基质可用水（主要材料规则）”处理。策略须满足可用水上界 ≤ 持水量下界，否则拒绝。',
      table: { hitPolicy: 'UNIQUE',
        inputs: [{ label: '材料代码', expr: 'material', type: 'string' }],
        outputs: [
          { name: 'cc_min', label: '持水量下界', type: 'number' }, { name: 'cc_max', label: '持水量上界', type: 'number' },
          { name: 'aw_min', label: '可用水（AW）下界', type: 'number' }, { name: 'aw_max', label: '可用水（AW）上界', type: 'number' },
        ],
        rules: [
          [['"general"'], ['0.25', '0.4', '0.1', '0.17'], null],
          [['"coco"'], ['0.5', '0.8', '0.18', '0.35'], null],
          [['"ceramsite"'], ['0.08', '0.15', '0.02', '0.05'], null],
          [['"peat"'], ['0.52', '0.65', '0.25', '0.35'], null],
          [['"perlite"'], ['0.2', '0.3', '0.08', '0.15'], null],
          [['"bark"'], ['0.49', '0.7', '0.1', '0.37'], null],
          [['"sphagnum"'], ['0.55', '0.85', '0.25', '0.4'], null],
          [['"gritty"'], ['0.32', '0.45', '0.09', '0.31'], null],
          [['"coarse_sand"'], ['0.2', '0.3', '0.05', '0.12'], null],
        ] } },
    { id: 'mvp_decision_water_amount', kind: 'decision', col: 6, row: 1,
      name: '水量估算', requires: ['mvp_decision_watering_action', 'mvp_decision_moisture_group', 'mvp_decision_substrate_available_water', 'mvp_input_measured_pot', 'mvp_knowledge_amount'],
      description: 'estimateMvpWaterAmount（合同 §4），仅在行动为 water_allowed 时调用。V=截锥在“盆高−留空”处装土体积；净补水 N=[Vmin×dmin×AWmin, Vmax×dmax×AWmax]；建议浇入=[Nmin/(1−LFmin), Nmax/(1−LFmax)]，四舍五入到 10mL，且不超过 Vmax×CCmax/(1−LFmax)。AW 与 CCmax 按“基质可用水（主要材料规则）”同一混合规则（v3 才使用主要材料）。几何/排水分支在 MVP 路径中已被盆器安全门前置覆盖，代码保留为防御分支。',
      table: { hitPolicy: 'FIRST',
        inputs: [
          { label: '浇水行动', expr: 'watering_action', type: 'string' },
          { label: '内盆几何可用', expr: 'measured_pot.geometry != null', type: 'boolean' },
          { label: '有排水', expr: 'measured_pot.drainageAvailable', type: 'boolean' },
          { label: '已选材料', expr: 'mix_rule != "none"', type: 'boolean' },
          { label: '湿度分组', expr: 'moisture_group', type: 'string' },
        ],
        outputs: [
          { name: 'amount_status', label: '水量结论', type: 'string' },
          { name: 'amount_missing', label: '缺失证据', type: 'string' },
          { name: 'depletion_min', label: '消耗比例下界', type: 'number' },
          { name: 'depletion_max', label: '消耗比例上界', type: 'number' },
        ],
        rules: [
          [['not("water_allowed")', '-', '-', '-', '-'], [S('not_allowed_now'), 'null', 'null', 'null'], '不调用估算'],
          [['"water_allowed"', 'false', '-', '-', '-'], [S('insufficient_evidence'), S('inner_pot_geometry'), 'null', 'null'], null],
          [['"water_allowed"', 'true', 'false', '-', '-'], [S('unsupported_drainage'), S('drainage_conditions'), 'null', 'null'], '无排水孔不适用“浇到少量出水”'],
          [['"water_allowed"', 'true', 'null', '-', '-'], [S('insufficient_evidence'), S('drainage_conditions'), 'null', 'null'], null],
          [['"water_allowed"', 'true', 'true', 'false', '-'], [S('insufficient_evidence'), S('substrate_materials'), 'null', 'null'], '不以盆容积百分比兜底'],
          [['"water_allowed"', 'true', 'true', 'true', '"keep_moist"'], [S('candidate'), 'null', '0.15', '0.25'], null],
          [['"water_allowed"', 'true', 'true', 'true', '"surface_dry"'], [S('candidate'), 'null', '0.25', '0.35'], null],
          [['"water_allowed"', 'true', 'true', 'true', '"dry_wet"'], [S('candidate'), 'null', '0.45', '0.55'], null],
          [['"water_allowed"', 'true', 'true', 'true', '"full_dry"'], [S('candidate'), 'null', '0.7', '0.85'], null],
        ] } },
    { id: 'mvp_decision_public_result', kind: 'decision', col: 7, row: 2,
      name: '公开浇水结果', requires: ['mvp_decision_watering_action', 'mvp_decision_water_amount'],
      description: 'projectWateringReplayResult 的 candidate 出口（MVP 不使用 publicResult），assessMvpWatering 再固定 confidence=low。代码按 soilGate=pause 判断，与 watering_action=pause_watering 等价。conflicting_evidence / no_safe_single_application / not_required 三个供水分支在 MVP 中不会产生，未建模。存在检查窗口但时区缺失时另加 plant_timezone；validUntil=min(盆土有效期, 窗口覆盖终点)。',
      table: { hitPolicy: 'FIRST',
        inputs: [
          { label: '浇水行动', expr: 'watering_action', type: 'string' },
          { label: '水量结论', expr: 'amount_status', type: 'string' },
        ],
        outputs: [
          { name: 'result_status', label: '结果状态', type: 'string' },
          { name: 'public_action', label: '公开行动', type: 'string' },
          { name: 'missing_evidence', label: '缺失证据', type: 'string' },
          { name: 'confidence', label: '置信度', type: 'string' },
        ],
        rules: [
          [['"temporarily_unavailable"', '-'], [S('temporarily_unavailable'), S('temporarily_unavailable'), S('published_watering_model'), S('low')], null],
          [['"pause_watering"', '-'], [S('ready'), S('pause_watering'), 'null', S('low')], null],
          [['"review_drainage"', '-'], [S('insufficient_evidence'), S('review_drainage'), S('drainage_conditions'), S('low')], null],
          [['-', '"unsupported_drainage"'], [S('insufficient_evidence'), S('review_drainage'), S('drainage_conditions'), S('low')], null],
          [['"insufficient_evidence"', '-'], [S('insufficient_evidence'), S('insufficient_evidence'), 'direct_missing_evidence', S('low')], '无基线为 plant_baseline，否则 current_soil_or_pot_evidence'],
          [['"water_allowed"', '"candidate"'], [S('ready'), S('water_allowed'), 'null', S('low')], 'amountMl=建议浇入区间，netDeficitMl=净补水'],
          [['"water_allowed"', '-'], [S('ready'), S('water_allowed'), S('application_reference'), S('low')], '可定性浇水但无水量'],
          [['-', '-'], [S('ready'), 'watering_action', 'null', S('low')], 'check_later / check_now / priority_check：附检查盆土窗口'],
        ] } },
  ],
}

export const longTermRules = {
  id: 'long_term_care_rules',
  name: '长期养护规则（long-term-care/v1）',
  description: '只读可视化：反映 src/care/domain/long-term-care-rules.ts 中建议确认、检查计划时刻与浇水补记三条规则。未接入规则引擎。',
  nodes: [
    { id: 'ltc_input_watering_result', kind: 'inputData', col: 0, row: 0, name: '公开浇水结果', variable: 'watering_result',
      description: '来自 mvp_watering_decisions 的公开结果（status、details.action、checkWindow、generatedAt）。长期植物建议的事务内同时写结果与建议。' },
    { id: 'ltc_knowledge_rules', kind: 'knowledgeSource', col: 1, row: 1, name: 'long-term-care/v1 硬规则',
      description: 'U3 浇水补记 ≤7 天；U5 检查计划最多推迟 7 天；U7 无最晚端建议有效 24 小时；Q1/Q5 主代理裁决；§12 计划过期宽限 care.plans.expiry_grace_hours=72（与 soilEvidenceMaxHours=72 对齐）。均为代码常量，不可运营配置。' },
    { id: 'ltc_input_care_plan', kind: 'inputData', col: 3, row: 2, name: '待扫描计划（状态与计划时刻）', variable: 'care_plan',
      description: 'care_plans 行的 status、scheduled_at_ms；比较时刻为本次扫描运行开始时刻（单次运行内所有批次相同）。' },
    { id: 'ltc_input_confirm_request', kind: 'inputData', col: 2, row: 0, name: '确认请求（schedule_check）', variable: 'confirm_request',
      description: '{ decision: "schedule_check", scheduledAt? }；窗口端点取自锁定建议中保存的结果。' },
    { id: 'ltc_input_watering_fact_request', kind: 'inputData', col: 0, row: 2, name: '浇水事实请求', variable: 'watering_fact_request',
      description: 'occurredAt、amountMl?；来自 POST facts、确认 record_watering 或完成计划附带浇水。' },
    { id: 'ltc_decision_proposal', kind: 'decision', col: 1, row: 0, name: '是否生成可确认建议', requires: ['ltc_input_watering_result', 'ltc_knowledge_rules'],
      description: 'isConfirmableWateringResult＋resolveProposalValidUntil：只对长期植物写 care_proposals（proposed）。',
      table: { hitPolicy: 'FIRST',
        inputs: [
          { label: '结果状态', expr: 'watering_result.status', type: 'string' },
          { label: '公开行动', expr: 'watering_result.details.action', type: 'string' },
          { label: '窗口最晚端晚于生成时刻', expr: 'checkWindow.latestAt > generatedAt', type: 'boolean' },
        ],
        outputs: [
          { name: 'proposal_created', label: '生成建议', type: 'boolean' },
          { name: 'proposal_valid_until_rule', label: '建议有效截止', type: 'string' },
        ],
        rules: [
          [['"ready"', '"water_allowed","check_later","check_now","priority_check"', 'true'], ['true', '"checkWindow.latestAt"'], null],
          [['"ready"', '"water_allowed","check_later","check_now","priority_check"', '-'], ['true', '"generatedAt + 24h"'], '无最晚端或不晚于生成时刻（Q1）'],
          [['-', '-', '-'], ['false', 'null'], 'pause_watering、review_drainage、insufficient_evidence、暂不可用：只返回结果，proposalRef=null'],
        ] } },
    { id: 'ltc_decision_check_schedule', kind: 'decision', col: 2, row: 1, name: '检查计划时刻', requires: ['ltc_input_confirm_request', 'ltc_knowledge_rules', 'ltc_decision_proposal'],
      description: 'resolveCheckScheduledAt（U5/Q5）：下界 = max(最早端 ?? now, now)；上界 = 最晚端（晚于建议生成时刻时）否则（最早端 ?? now）+ 7 天。',
      table: { hitPolicy: 'FIRST',
        inputs: [
          { label: '用户自选时刻', expr: 'confirm_request.scheduledAt != null', type: 'boolean' },
          { label: '自选时刻在允许范围内', expr: 'scheduledAt in [下界..上界]', type: 'boolean' },
        ],
        outputs: [
          { name: 'schedule_accepted', label: '接受', type: 'boolean' },
          { name: 'scheduled_at_rule', label: '计划时刻', type: 'string' },
        ],
        rules: [
          [['false', '-'], ['true', '"max(checkWindow.earliestAt ?? now, now)"'], '缺省避免落在过去'],
          [['true', 'true'], ['true', '"scheduledAt"'], null],
          [['true', 'false'], ['false', 'null'], '400 VALIDATION_FAILED：检查时间须在建议的检查窗口内'],
        ] } },
    { id: 'ltc_decision_plan_expired', kind: 'decision', col: 2, row: 2, name: '计划是否过期', requires: ['ltc_input_care_plan', 'ltc_knowledge_rules'],
      description: '§12.1：只有 planned 可过期；运行开始时刻 − scheduledAt 严格大于 72 小时才过期，恰好 72 小时不过期。由每小时定时事件函数 care-plan-expiry 以条件更新 status=planned AND scheduled_at_ms < 开始时刻−72h 执行（version+1）；请求路径不做读时过期。',
      table: { hitPolicy: 'FIRST',
        inputs: [
          { label: '计划状态', expr: 'care_plan.status', type: 'string' },
          { label: '距计划时刻小时数', expr: '(runStartedAt - care_plan.scheduledAt) / 1h', type: 'number' },
        ],
        outputs: [{ name: 'plan_expired', label: '标记为 expired', type: 'boolean' }],
        rules: [
          [['"planned"', '> 72'], ['true'], '写 status=expired、version+1；日历与 completedFactRef 不变'],
          [['-', '-'], ['false'], 'completed、cancelled、expired 永不改写；恰好 72 小时不过期'],
        ] } },
    { id: 'ltc_decision_watering_occurred_at', kind: 'decision', col: 1, row: 2, name: '浇水时刻补记校验', requires: ['ltc_input_watering_fact_request', 'ltc_knowledge_rules'],
      description: 'validateWateringOccurredAt（U3）。',
      table: { hitPolicy: 'FIRST',
        inputs: [
          { label: '不晚于现在', expr: 'occurredAt <= now', type: 'boolean' },
          { label: '不早于 7 天前', expr: 'occurredAt >= now - 7d', type: 'boolean' },
          { label: '不早于植物加入花园', expr: 'occurredAt >= plantCreatedAt', type: 'boolean' },
        ],
        outputs: [{ name: 'occurred_at_valid', label: '合法', type: 'boolean' }],
        rules: [
          [['true', 'true', 'true'], ['true'], null],
          [['-', '-', '-'], ['false'], '400 VALIDATION_FAILED：浇水时间须在最近 7 天内、不晚于现在且不早于植物加入花园'],
        ] } },
  ],
}
