CREATE TABLE IF NOT EXISTS `diagnosis_follow_up_answer_events` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `event_id` VARCHAR(64) NOT NULL,
  `_openid` VARCHAR(64) NOT NULL DEFAULT '',
  `diagnosis_id` VARCHAR(64) NOT NULL,
  `answer_revision_before` INT NOT NULL DEFAULT 0,
  `answer_revision_after` INT NOT NULL DEFAULT 0,
  `dirty_question_key` VARCHAR(255) NOT NULL DEFAULT '',
  `dirty_round_index` INT NOT NULL DEFAULT 1,
  `event_type` VARCHAR(32) NOT NULL,
  `question_row_id` BIGINT UNSIGNED NULL,
  `question_key` VARCHAR(255) NOT NULL DEFAULT '',
  `question_text` TEXT NULL,
  `question_round_index` INT NOT NULL DEFAULT 1,
  `previous_option_key` VARCHAR(128) NOT NULL DEFAULT '',
  `previous_status` VARCHAR(64) NOT NULL DEFAULT '',
  `previous_asked` TINYINT NOT NULL DEFAULT 0,
  `new_option_key` VARCHAR(128) NOT NULL DEFAULT '',
  `new_status` VARCHAR(64) NOT NULL DEFAULT '',
  `new_asked` TINYINT NOT NULL DEFAULT 0,
  `reason` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_follow_up_answer_event_id` (`event_id`),
  KEY `idx_follow_up_answer_events_diagnosis_created` (`diagnosis_id`, `created_at`),
  KEY `idx_follow_up_answer_events_diagnosis_revision` (`diagnosis_id`, `answer_revision_after`),
  KEY `idx_follow_up_answer_events_dirty_question` (`diagnosis_id`, `dirty_question_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
