CREATE TABLE IF NOT EXISTS question_queue (
  question_queue_id VARCHAR(64) PRIMARY KEY COMMENT '追问队列ID',
  _openid VARCHAR(64) NOT NULL DEFAULT '' COMMENT '云开发用户标识',
  session_id VARCHAR(64) NOT NULL COMMENT '会话ID',
  diagnosis_id VARCHAR(64) NOT NULL COMMENT '诊断ID（当前与session_id同值）',
  round_id VARCHAR(64) NOT NULL COMMENT '轮次ID',
  round_index INT NOT NULL DEFAULT 1 COMMENT '轮次序号',
  route_primary_action VARCHAR(64) NOT NULL DEFAULT '' COMMENT '当前主路由动作',
  queue_status VARCHAR(64) NOT NULL DEFAULT 'active' COMMENT '队列状态',
  service_target VARCHAR(64) NOT NULL DEFAULT '' COMMENT '主要服务对象',
  exhausted_reason VARCHAR(128) NULL COMMENT '队列耗尽/阻断原因',
  question_items_json JSON NOT NULL COMMENT '问题项快照JSON',
  active_item_count INT NOT NULL DEFAULT 0 COMMENT '当前有效问题数',
  asked_item_count INT NOT NULL DEFAULT 0 COMMENT '已提问问题数',
  answered_item_count INT NOT NULL DEFAULT 0 COMMENT '已回答问题数',
  invalidated_item_count INT NOT NULL DEFAULT 0 COMMENT '已失效问题数',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY uk_question_queue_round (session_id, round_id),
  KEY idx_question_queue_openid (_openid),
  KEY idx_question_queue_round_index (session_id, round_index),
  KEY idx_question_queue_status (queue_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='诊断追问队列表';

CREATE TABLE IF NOT EXISTS stop_state (
  stop_state_id VARCHAR(64) PRIMARY KEY COMMENT '停止状态ID',
  _openid VARCHAR(64) NOT NULL DEFAULT '' COMMENT '云开发用户标识',
  session_id VARCHAR(64) NOT NULL COMMENT '会话ID',
  diagnosis_id VARCHAR(64) NOT NULL COMMENT '诊断ID（当前与session_id同值）',
  round_id VARCHAR(64) NOT NULL COMMENT '轮次ID',
  round_index INT NOT NULL DEFAULT 1 COMMENT '轮次序号',
  is_stopped TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已停止',
  stop_reason_type VARCHAR(64) NOT NULL DEFAULT '' COMMENT '停止原因类型',
  stop_reason VARCHAR(128) NULL COMMENT '停止原因键',
  stop_reason_text TEXT NULL COMMENT '停止说明',
  final_output_ref VARCHAR(128) NULL COMMENT '最终输出引用',
  allow_more_questions TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否允许继续追问',
  output_eligible TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否具备输出资格',
  output_judgment VARCHAR(64) NOT NULL DEFAULT '' COMMENT '输出资格判定',
  conclusion_type VARCHAR(64) NOT NULL DEFAULT '' COMMENT '结论类型',
  conclusion_status VARCHAR(64) NOT NULL DEFAULT '' COMMENT '结论状态',
  output_conservatism VARCHAR(64) NOT NULL DEFAULT '' COMMENT '输出保守等级',
  key_evidence_summary TEXT NULL COMMENT '关键证据摘要',
  unresolved_risks_json JSON NULL COMMENT '未解决风险JSON',
  next_step_hints_json JSON NULL COMMENT '下一步建议JSON',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY uk_stop_state_round (session_id, round_id),
  KEY idx_stop_state_openid (_openid),
  KEY idx_stop_state_round_index (session_id, round_index),
  KEY idx_stop_state_reason_type (stop_reason_type),
  KEY idx_stop_state_output_eligible (output_eligible)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='诊断停止状态与输出资格表';
