CREATE TABLE IF NOT EXISTS outcome_route_groups (
  route_group_key VARCHAR(128) PRIMARY KEY COMMENT '分流路径组键',
  route_group_name_cn VARCHAR(255) NOT NULL DEFAULT '' COMMENT '分流路径组中文名',
  entry_scene_cn TEXT NULL COMMENT '入口场景中文说明',
  entry_symptom_keys_json JSON NOT NULL COMMENT '入口症状 keys JSON',
  candidate_outcome_keys_json JSON NOT NULL COMMENT '候选 outcome keys JSON',
  default_split_question_key VARCHAR(128) NOT NULL DEFAULT '' COMMENT '默认分流问题 key',
  max_visible_outcomes INT NOT NULL DEFAULT 3 COMMENT '最多前端可见 outcome 数',
  visible_question_purpose_cn TEXT NULL COMMENT '提问目的说明',
  enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否启用',
  review_status VARCHAR(64) NOT NULL DEFAULT 'draft' COMMENT '审核状态',
  data_status VARCHAR(64) NOT NULL DEFAULT 'active' COMMENT '数据状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  KEY idx_outcome_route_groups_enabled (enabled),
  KEY idx_outcome_route_groups_review (review_status),
  KEY idx_outcome_route_groups_data (data_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='诊断 outcome 分流路径组表';

CREATE TABLE IF NOT EXISTS outcome_routes (
  route_key VARCHAR(128) PRIMARY KEY COMMENT '路径键',
  route_group_key VARCHAR(128) NOT NULL DEFAULT '' COMMENT '所属分流路径组键',
  outcome_key VARCHAR(128) NOT NULL DEFAULT '' COMMENT '目标 outcome 键',
  route_name_cn VARCHAR(255) NOT NULL DEFAULT '' COMMENT '路径中文名',
  route_entry_type VARCHAR(64) NOT NULL DEFAULT '' COMMENT '路径入口类型',
  entry_symptom_keys_json JSON NOT NULL COMMENT '入口症状 keys JSON',
  entry_direction_keys_json JSON NOT NULL COMMENT '入口方向 keys JSON',
  entry_symptom_class_keys_json JSON NOT NULL COMMENT '入口症状模式 keys JSON',
  host_profile_condition_json JSON NULL COMMENT '植物基线条件 JSON',
  entry_priority INT NOT NULL DEFAULT 0 COMMENT '入口优先级',
  max_questions INT NOT NULL DEFAULT 1 COMMENT '该路径最大追问数',
  fallback_policy VARCHAR(64) NOT NULL DEFAULT '' COMMENT '兜底策略',
  action_profile_key VARCHAR(128) NOT NULL DEFAULT '' COMMENT '行动建议模板键',
  action_conflict_group VARCHAR(128) NOT NULL DEFAULT '' COMMENT '行动冲突组',
  enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否启用',
  review_status VARCHAR(64) NOT NULL DEFAULT 'draft' COMMENT '审核状态',
  data_status VARCHAR(64) NOT NULL DEFAULT 'active' COMMENT '数据状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  KEY idx_outcome_routes_group (route_group_key),
  KEY idx_outcome_routes_outcome (outcome_key),
  KEY idx_outcome_routes_action_profile (action_profile_key),
  KEY idx_outcome_routes_enabled (enabled),
  KEY idx_outcome_routes_review (review_status),
  KEY idx_outcome_routes_data (data_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='诊断 outcome 可达路径表';

CREATE TABLE IF NOT EXISTS outcome_route_gates (
  gate_key VARCHAR(128) PRIMARY KEY COMMENT '路径 gate 键',
  route_key VARCHAR(128) NOT NULL DEFAULT '' COMMENT '所属路径键',
  gate_role VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'gate 角色',
  required_evidence_json JSON NOT NULL COMMENT '必需证据 JSON',
  required_answer_effects_json JSON NOT NULL COMMENT '必需回答效果 JSON',
  blocker_evidence_json JSON NOT NULL COMMENT '阻断证据 JSON',
  conflict_outcome_keys_json JSON NOT NULL COMMENT '冲突 outcome keys JSON',
  closure_level VARCHAR(64) NOT NULL DEFAULT '' COMMENT '闭合级别',
  on_pass VARCHAR(64) NOT NULL DEFAULT '' COMMENT '通过动作',
  on_fail VARCHAR(64) NOT NULL DEFAULT '' COMMENT '失败动作',
  on_unknown VARCHAR(64) NOT NULL DEFAULT '' COMMENT '未知动作',
  decision_cause_key VARCHAR(128) NOT NULL DEFAULT '' COMMENT '决策原因键',
  decision_cause_text_cn TEXT NULL COMMENT '中文决策说明',
  gate_priority INT NOT NULL DEFAULT 0 COMMENT 'gate 优先级',
  enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否启用',
  review_status VARCHAR(64) NOT NULL DEFAULT 'draft' COMMENT '审核状态',
  data_status VARCHAR(64) NOT NULL DEFAULT 'active' COMMENT '数据状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  KEY idx_outcome_route_gates_route (route_key),
  KEY idx_outcome_route_gates_role (gate_role),
  KEY idx_outcome_route_gates_enabled (enabled),
  KEY idx_outcome_route_gates_review (review_status),
  KEY idx_outcome_route_gates_data (data_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='诊断 outcome 路径 gate 表';

CREATE TABLE IF NOT EXISTS outcome_route_questions (
  outcome_route_question_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '路径问题自增ID',
  route_key VARCHAR(128) NOT NULL DEFAULT '' COMMENT '路径键',
  step_no INT NOT NULL DEFAULT 1 COMMENT '路径步骤号',
  question_key VARCHAR(128) NOT NULL DEFAULT '' COMMENT '问题键',
  gate_key VARCHAR(128) NOT NULL DEFAULT '' COMMENT '服务的 gate 键',
  question_role VARCHAR(64) NOT NULL DEFAULT '' COMMENT '问题角色',
  required_for_closure TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否闭合必需',
  ask_priority INT NOT NULL DEFAULT 0 COMMENT '提问优先级',
  skip_if_evidence_json JSON NOT NULL COMMENT '已存在证据时跳过规则 JSON',
  repeat_policy VARCHAR(64) NOT NULL DEFAULT '' COMMENT '重复策略',
  enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否启用',
  review_status VARCHAR(64) NOT NULL DEFAULT 'draft' COMMENT '审核状态',
  data_status VARCHAR(64) NOT NULL DEFAULT 'active' COMMENT '数据状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (outcome_route_question_id),
  UNIQUE KEY uk_outcome_route_questions_unique (route_key, step_no, question_key),
  KEY idx_outcome_route_questions_gate (gate_key),
  KEY idx_outcome_route_questions_question (question_key),
  KEY idx_outcome_route_questions_enabled (enabled),
  KEY idx_outcome_route_questions_review (review_status),
  KEY idx_outcome_route_questions_data (data_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='诊断 outcome 路径问题表';

CREATE TABLE IF NOT EXISTS outcome_answer_effects (
  outcome_answer_effect_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '回答效果自增ID',
  question_key VARCHAR(128) NOT NULL DEFAULT '' COMMENT '问题键',
  option_key VARCHAR(128) NOT NULL DEFAULT '' COMMENT '选项键',
  outcome_key VARCHAR(128) NOT NULL DEFAULT '' COMMENT '影响的 outcome 键',
  route_key VARCHAR(128) NOT NULL DEFAULT '' COMMENT '影响的路径键',
  effect_type VARCHAR(64) NOT NULL DEFAULT 'neutral' COMMENT '影响类型',
  effect_strength DECIMAL(6,4) NOT NULL DEFAULT 0.0000 COMMENT '影响强度',
  redirect_outcome_key VARCHAR(128) NOT NULL DEFAULT '' COMMENT '转向 outcome 键',
  evidence_dimension VARCHAR(128) NOT NULL DEFAULT '' COMMENT '证据维度',
  effect_note_cn TEXT NULL COMMENT '中文影响说明',
  enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否启用',
  review_status VARCHAR(64) NOT NULL DEFAULT 'draft' COMMENT '审核状态',
  data_status VARCHAR(64) NOT NULL DEFAULT 'active' COMMENT '数据状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (outcome_answer_effect_id),
  UNIQUE KEY uk_outcome_answer_effects_unique (question_key, option_key, outcome_key, route_key),
  KEY idx_outcome_answer_effects_route (route_key),
  KEY idx_outcome_answer_effects_outcome (outcome_key),
  KEY idx_outcome_answer_effects_enabled (enabled),
  KEY idx_outcome_answer_effects_review (review_status),
  KEY idx_outcome_answer_effects_data (data_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='诊断回答对 outcome/route 影响表';

CREATE TABLE IF NOT EXISTS outcome_action_profiles (
  action_profile_key VARCHAR(128) PRIMARY KEY COMMENT '行动建议模板键',
  title_cn VARCHAR(255) NOT NULL DEFAULT '' COMMENT '建议标题',
  today_actions_json JSON NOT NULL COMMENT '今天行动建议 JSON',
  three_day_actions_json JSON NOT NULL COMMENT '三天内行动建议 JSON',
  seven_day_observe_json JSON NOT NULL COMMENT '七天观察建议 JSON',
  avoid_actions_json JSON NOT NULL COMMENT '避免动作 JSON',
  retake_or_escalate_json JSON NOT NULL COMMENT '补拍或升级建议 JSON',
  plant_baseline_merge_policy VARCHAR(128) NOT NULL DEFAULT '' COMMENT '植物基线合并策略',
  review_status VARCHAR(64) NOT NULL DEFAULT 'draft' COMMENT '审核状态',
  data_status VARCHAR(64) NOT NULL DEFAULT 'active' COMMENT '数据状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  KEY idx_outcome_action_profiles_review (review_status),
  KEY idx_outcome_action_profiles_data (data_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='诊断 outcome 行动建议模板表';

CREATE TABLE IF NOT EXISTS diagnosis_outcomes (
  outcome_key VARCHAR(128) PRIMARY KEY COMMENT 'outcome 键',
  legacy_problem_key VARCHAR(128) NOT NULL DEFAULT '' COMMENT '兼容旧 problem_key',
  outcome_name_cn VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'outcome 中文名',
  outcome_type VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'outcome 类型',
  outcome_category VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'outcome 分类',
  display_name_cn VARCHAR(255) NOT NULL DEFAULT '' COMMENT '前端展示名',
  user_definition_cn TEXT NULL COMMENT '用户侧解释',
  action_profile_key VARCHAR(128) NOT NULL DEFAULT '' COMMENT '行动建议模板键',
  risk_level VARCHAR(64) NOT NULL DEFAULT '' COMMENT '风险等级',
  is_final_output TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否最终输出',
  is_intermediate_node TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否中间节点',
  allow_direct_close TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否允许直接闭合',
  allow_uncertain_close TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否允许不确定闭合',
  priority INT NOT NULL DEFAULT 0 COMMENT '默认优先级',
  review_status VARCHAR(64) NOT NULL DEFAULT 'draft' COMMENT '审核状态',
  data_status VARCHAR(64) NOT NULL DEFAULT 'active' COMMENT '数据状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  KEY idx_diagnosis_outcomes_legacy_problem (legacy_problem_key),
  KEY idx_diagnosis_outcomes_action_profile (action_profile_key),
  KEY idx_diagnosis_outcomes_type (outcome_type),
  KEY idx_diagnosis_outcomes_review (review_status),
  KEY idx_diagnosis_outcomes_data (data_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='诊断 outcome 定义表';
