CREATE TABLE IF NOT EXISTS `visual_out_of_pool_candidate_reviews` (
  `visual_out_of_pool_review_id` VARCHAR(64) NOT NULL,
  `_openid` VARCHAR(128) NULL DEFAULT '',
  `session_id` VARCHAR(64) NOT NULL,
  `visual_call_batch_id` VARCHAR(64) NOT NULL,
  `visual_raw_image_record_id` VARCHAR(64) NOT NULL,
  `visual_normalized_image_result_id` VARCHAR(64) NOT NULL,
  `candidate_index` INT NOT NULL,
  `raw_visual_name_cn` VARCHAR(255) NOT NULL DEFAULT '',
  `raw_visual_name_en` VARCHAR(255) NOT NULL DEFAULT '',
  `closest_symptom_key_hint` VARCHAR(128) NOT NULL DEFAULT '',
  `reason` TEXT NULL,
  `review_action` VARCHAR(32) NOT NULL,
  `reviewed_by_openid` VARCHAR(128) NOT NULL DEFAULT '',
  `reviewed_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`visual_out_of_pool_review_id`),
  UNIQUE KEY `uk_visual_out_of_pool_candidate` (`visual_normalized_image_result_id`, `candidate_index`),
  KEY `idx_visual_out_of_pool_review_action` (`review_action`, `reviewed_at`),
  KEY `idx_visual_out_of_pool_session` (`session_id`, `visual_call_batch_id`),
  KEY `idx_visual_out_of_pool_raw_record` (`visual_raw_image_record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `visual_out_of_pool_candidate_groups` (
  `group_id` VARCHAR(64) NOT NULL,
  `canonical_fingerprint` VARCHAR(64) NOT NULL,
  `canonical_text` VARCHAR(512) NOT NULL DEFAULT '',
  `normalized_text` VARCHAR(512) NOT NULL DEFAULT '',
  `alias_texts_json` JSON NULL,
  `representative_visual_normalized_image_result_id` VARCHAR(64) NOT NULL DEFAULT '',
  `representative_candidate_index` INT NOT NULL DEFAULT 0,
  `review_action` VARCHAR(32) NOT NULL DEFAULT '',
  `reviewed_by_openid` VARCHAR(128) NOT NULL DEFAULT '',
  `reviewed_at` DATETIME NULL,
  `possible_duplicate_group_id` VARCHAR(64) NOT NULL DEFAULT '',
  `possible_duplicate_score` DECIMAL(6,4) NOT NULL DEFAULT 0,
  `last_seen_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`group_id`),
  UNIQUE KEY `uk_visual_out_of_pool_group_fingerprint` (`canonical_fingerprint`),
  KEY `idx_visual_out_of_pool_group_review` (`review_action`, `reviewed_at`),
  KEY `idx_visual_out_of_pool_group_duplicate` (`possible_duplicate_group_id`, `possible_duplicate_score`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
