-- Move yellowing synthetic follow-up copy into governed data-layer templates.
-- Run after checking the three added column groups are absent; MySQL in this project
-- should not rely on ADD COLUMN IF NOT EXISTS.

ALTER TABLE `question_library_v5_real`
  ADD COLUMN `default_option_key` VARCHAR(128) NULL COMMENT '默认选项 key，用于 gate 类题默认选中' AFTER `why_this_question_cn`,
  ADD COLUMN `ui_variant` VARCHAR(64) NULL COMMENT '前端展示形态，例如 single_select_accordion' AFTER `default_option_key`,
  ADD COLUMN `render_mode` VARCHAR(64) NULL COMMENT 'static|data_template|runtime_fallback' AFTER `ui_variant`,
  ADD COLUMN `template_engine_rule_key` VARCHAR(128) NULL COMMENT '关联 question_generation_engine.engine_rule_key' AFTER `render_mode`;

ALTER TABLE `question_option_mapping_v5_real`
  ADD COLUMN `option_description_user_cn` TEXT NULL COMMENT '用户可见选项说明，允许 {{variable}} 模板变量' AFTER `answer_effect_cn`,
  ADD COLUMN `display_order` INT NULL COMMENT '选项展示顺序' AFTER `option_description_user_cn`,
  ADD COLUMN `is_default` TINYINT(1) NULL DEFAULT 0 COMMENT '是否为默认选项' AFTER `display_order`;

ALTER TABLE `question_generation_engine`
  ADD COLUMN `help_template_user_cn` TEXT NULL COMMENT '用户可见帮助模板' AFTER `template_user_cn`,
  ADD COLUMN `template_variables_json` TEXT NULL COMMENT '模板变量声明 JSON 文本' AFTER `help_template_user_cn`,
  ADD COLUMN `fallback_values_json` TEXT NULL COMMENT '变量缺失时的兜底值 JSON 文本' AFTER `template_variables_json`,
  ADD COLUMN `render_policy` VARCHAR(32) NULL COMMENT 'strict|fallback' AFTER `fallback_values_json`,
  ADD COLUMN `option_template_json` TEXT NULL COMMENT '动态选项模板声明 JSON 文本' AFTER `render_policy`;

INSERT INTO `question_library_v5_real` (
  `question_key`,
  `question_text_cn`,
  `question_type`,
  `target_symptom_key`,
  `question_group_key`,
  `question_level`,
  `observability`,
  `target_dimension`,
  `routing_scope`,
  `question_role`,
  `effect_mode`,
  `allow_unknown`,
  `priority`,
  `data_status`,
  `data_source`,
  `note`,
  `question_text_user_cn`,
  `help_text_cn`,
  `why_this_question_cn`,
  `default_option_key`,
  `ui_variant`,
  `render_mode`,
  `template_engine_rule_key`,
  `source_type`,
  `source_batch_id`,
  `version_tag`,
  `review_status`,
  `review_note`,
  `is_active`,
  `created_at`,
  `updated_at`,
  `published_at`,
  `published_batch_id`
) VALUES
('q_observed_probe__leaf_yellowing__yellowing_primary_clue_gate',
 '黄叶原因较复杂，先选你最明显看到的一类线索。这样后面会按方向继续问，避免问很多无关问题。',
 'single_choice','leaf_yellowing','observed_probe__leaf_yellowing__yellowing_primary_clue_gate',1,'high','yellowing_primary_clue_gate','differential_probe','gate','route_gate',1,260,'audited','data_layer_template','runtime must not hardcode this yellowing gate copy',
 '黄叶原因较复杂，先选你最明显看到的一类线索。这样后面会按方向继续问，避免问很多无关问题。',
 '只选最明显的一类；如果看不准，可以先选日常养护或不确定。',
 '黄叶需要先分流养护、虫害、病斑或单纯黄叶，避免后续问题全部偏向单一路径。',
 'care_context','single_select_accordion','data_template','qge_yellowing_primary_clue_gate','manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','黄叶首层 gate 由数据层治理，默认进入养护方向。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_care_area_gate',
 '为了判断黄叶是否和日常养护有关，先选最近两周最可疑的一项。每个选项下面有参考说明，选最接近你实际情况的即可。',
 'single_choice','leaf_yellowing','observed_probe__leaf_yellowing__yellowing_care_area_gate',1,'high','yellowing_care_area_gate','context_probe','gate','route_gate',1,250,'audited','data_layer_template','runtime must not hardcode this yellowing care gate copy',
 '为了判断黄叶是否和日常养护有关，先选最近两周最可疑的一项。每个选项下面有参考说明，选最接近你实际情况的即可。',
 '这题不是让你直接判断病因，而是先决定继续查浇水、光照、施肥还是通风湿度。',
 '养护方向需要先细分到具体行为，再进入对应的频率或环境问题。',
 'watering_area','single_select_accordion','data_template','qge_yellowing_care_area_gate','manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','黄叶养护 gate 由数据层治理，默认从浇水方向开始。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__watering_frequency_context',
 '最近 2 周，你的浇水间隔更接近哪一种？',
 'single_choice','leaf_yellowing','observed_probe__leaf_yellowing__watering_frequency_context',1,'medium','watering_frequency_context','context_probe','context_metric','context_feature',1,240,'audited','data_layer_template','uses {{watering_reference}} variables from genus care profile and weather humidity',
 '最近 2 周，你的浇水间隔更接近哪一种？',
 '{{watering_help}}',
 '浇水频率用于判断黄叶是否可能和根区长期偏湿或偏干有关。',
 '','single_select_accordion','data_template','qge_yellowing_watering_frequency_context','manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','浇水周期题由数据层模板治理，选项文字由变量渲染。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__light_change_context',
 '最近 1-2 周，这盆植物每天大概能晒到多久的直射太阳？',
 'single_choice','leaf_yellowing','observed_probe__leaf_yellowing__light_change_context',1,'medium','light_change_context','context_probe','context_metric','context_feature',1,230,'audited','data_layer_template','light question template is governed in data layer',
 '最近 1-2 周，这盆植物每天大概能晒到多久的直射太阳？',
 '这里问的是直射太阳时长，不是室内亮不亮；后续会结合植物本身的耐光情况判断是否偏强或偏弱。',
 '光照时长用于判断黄叶是否可能和突然暴晒、弱光或位置变化有关。',
 '','single_select_accordion','data_template','qge_yellowing_light_change_context','manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','光照题由数据层治理。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__fertilization_growth_context',
 '最近 1 个月，你大概施肥几次？',
 'single_choice','leaf_yellowing','observed_probe__leaf_yellowing__fertilization_growth_context',1,'medium','fertilization_growth_context','context_probe','context_metric','context_feature',1,220,'audited','data_layer_template','fertilization question template is governed in data layer',
 '最近 1 个月，你大概施肥几次？',
 '这题只记录供肥背景；长期没补肥、近期重肥、换土或换盆，对黄叶的意义不同。',
 '施肥频率用于区分缺肥、肥害或换盆刺激等方向。',
 '','single_select_accordion','data_template','qge_yellowing_fertilization_growth_context','manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','施肥题由数据层治理。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__pest_trace_type',
 '除了发黄，叶片或叶背有没有更直接的虫害线索？请选择最明显的一种。',
 'single_choice','leaf_yellowing','observed_probe__leaf_yellowing__pest_trace_type',1,'medium','pest_trace_type','differential_probe','differential_probe','score_adjustment',1,210,'audited','data_layer_template','pest trace branch copy is governed in data layer',
 '除了发黄，叶片或叶背有没有更直接的虫害线索？请选择最明显的一种。',
 '这题是为了确认有没有更直接的虫子活动线索，避免只凭黄点或发黄就判断成虫害。',
 '虫害分流需要优先确认虫体、虫卵、细网、蜜露、黑色排泄点等更直接线索。',
 '','single_select_accordion','data_template','qge_yellowing_pest_trace_type','manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','虫害分流题由数据层治理。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_disease_trace_gate',
 '除了发黄，叶片上是否还伴随斑点、烂斑、发软或霉粉？请选择最明显的一种。',
 'single_choice','leaf_yellowing','observed_probe__leaf_yellowing__yellowing_disease_trace_gate',1,'medium','yellowing_disease_trace_gate','differential_probe','gate','route_gate',1,205,'audited','data_layer_template','disease trace gate copy is governed in data layer',
 '除了发黄，叶片上是否还伴随斑点、烂斑、发软或霉粉？请选择最明显的一种。',
 '不需要区分真菌或细菌，只按肉眼能看到的斑点、水渍感、软烂或粉霉层来选。',
 '病害方向需要先确认黄叶是否伴随叶斑、水渍、软烂或霉粉等线索。',
 '','single_select_accordion','data_template','qge_yellowing_disease_trace_gate','manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','病害 gate 由数据层治理。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_leaf_age_pattern',
 '发黄最先、最明显出现在新叶，还是老叶/下部叶？',
 'single_choice','leaf_yellowing','observed_probe__leaf_yellowing__yellowing_leaf_age_pattern',1,'medium','yellowing_leaf_age_pattern','differential_probe','differential_probe','score_adjustment',1,200,'audited','data_layer_template','leaf age yellowing branch copy is governed in data layer',
 '发黄最先、最明显出现在新叶，还是老叶/下部叶？',
 '新叶和老叶的先后顺序，可帮助区分营养、光照和根区压力等方向。',
 '黄叶位置用于区分新叶问题、老叶问题或全株性压力。',
 '','single_select_accordion','data_template','qge_yellowing_leaf_age_pattern','manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','黄叶新老叶分流题由数据层治理。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_distribution_pattern',
 '发黄的分布更接近哪一种？',
 'single_choice','leaf_yellowing','observed_probe__leaf_yellowing__yellowing_distribution_pattern',1,'medium','yellowing_distribution_pattern','differential_probe','differential_probe','score_adjustment',1,190,'audited','data_layer_template','yellowing distribution branch copy is governed in data layer',
 '发黄的分布更接近哪一种？',
 '分布方式比“是否发黄”更能区分营养、光照、水分和虫害弱线索。',
 '黄叶分布用于区分均匀黄化、脉间黄化、斑驳黄化或局部灼伤样黄化。',
 '','single_select_accordion','data_template','qge_yellowing_distribution_pattern','manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','黄叶分布题由数据层治理。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_progression_speed',
 '最近 7 天，黄叶变化速度更接近哪一种？',
 'single_choice','leaf_yellowing','observed_probe__leaf_yellowing__yellowing_progression_speed',1,'medium','yellowing_progression_speed','context_probe','context_metric','context_feature',1,180,'audited','data_layer_template','yellowing progression branch copy is governed in data layer',
 '最近 7 天，黄叶变化速度更接近哪一种？',
 '变化速度会影响是否进入根区压力、急性环境变化或较稳定旧问题方向。',
 '黄叶进展速度用于判断是否存在急性压力或持续恶化。',
 '','single_select_accordion','data_template','qge_yellowing_progression_speed','manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','黄叶进展题由数据层治理。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429')
ON DUPLICATE KEY UPDATE
  `question_text_cn` = VALUES(`question_text_cn`),
  `question_text_user_cn` = VALUES(`question_text_user_cn`),
  `help_text_cn` = VALUES(`help_text_cn`),
  `why_this_question_cn` = VALUES(`why_this_question_cn`),
  `target_dimension` = VALUES(`target_dimension`),
  `routing_scope` = VALUES(`routing_scope`),
  `question_role` = VALUES(`question_role`),
  `effect_mode` = VALUES(`effect_mode`),
  `default_option_key` = VALUES(`default_option_key`),
  `ui_variant` = VALUES(`ui_variant`),
  `render_mode` = VALUES(`render_mode`),
  `template_engine_rule_key` = VALUES(`template_engine_rule_key`),
  `priority` = VALUES(`priority`),
  `data_status` = VALUES(`data_status`),
  `review_status` = VALUES(`review_status`),
  `note` = VALUES(`note`),
  `review_note` = VALUES(`review_note`),
  `is_active` = 1,
  `updated_at` = NOW(),
  `published_at` = NOW(),
  `published_batch_id` = VALUES(`published_batch_id`);

INSERT INTO `question_option_mapping_v5_real` (
  `question_key`,
  `option_key`,
  `option_text_cn`,
  `maps_to_symptom_key`,
  `value`,
  `association_strength`,
  `data_status`,
  `data_source`,
  `note`,
  `option_text_user_cn`,
  `answer_effect_cn`,
  `option_description_user_cn`,
  `display_order`,
  `is_default`,
  `source_type`,
  `source_batch_id`,
  `version_tag`,
  `review_status`,
  `review_note`,
  `is_active`,
  `created_at`,
  `updated_at`,
  `published_at`,
  `published_batch_id`
) VALUES
('q_observed_probe__leaf_yellowing__yellowing_primary_clue_gate','care_context','先看日常养护','',0,0,'audited','data_layer_template','route to care gate','先看日常养护','进入浇水、光照、施肥、通风湿度分流。',CONCAT('先快速对照这类植物的日常养护：', CHAR(10), '- {{watering_reference}}', CHAR(10), '- {{light_reference}}', CHAR(10), '- {{fertilization_reference}}', CHAR(10), '- {{humidity_reference}}', CHAR(10), '如果最近两周和其中任一项差得比较多，先选这个，下一题会继续细分是哪一项。'),10,1,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','默认进入养护方向，并在首层 gate 直接展示属级养护参考。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_primary_clue_gate','pest_trace','看到虫子或虫害痕迹','',0,0,'audited','data_layer_template','route to pest trace branch','看到虫子或虫害痕迹','进入虫害线索分流。','例如小虫、虫卵、细网、黑点、叶面发黏，或叶背有活动点。',20,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','黄叶虫害方向。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_primary_clue_gate','disease_trace','还有斑点、烂斑或霉粉','',0,0,'audited','data_layer_template','route to disease trace branch','还有斑点、烂斑或霉粉','进入病害线索分流。','例如褐斑、黑斑、水渍感、软烂、霉层或粉状物。',30,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','黄叶病害方向。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_primary_clue_gate','yellowing_only','只是发黄，没看到其他异常','',0,0,'audited','data_layer_template','route to yellowing pattern branch','只是发黄，没看到其他异常','进入黄叶位置和分布分流。','如果主要就是叶色变黄，暂时没看到虫子、病斑或明显养护变化，选这个。',40,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','单纯黄叶方向。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_primary_clue_gate','unknown','不确定，继续帮我排查','',0,0,'audited','data_layer_template','route to conservative yellowing branch','不确定，继续帮我排查','进入保守分流。','如果看不出最明显的方向，选这个，系统会继续从黄叶分布和新老叶位置排查。',50,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','黄叶不确定方向。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_care_area_gate','watering_area','浇水可能不合适','',0,0,'audited','data_layer_template','route to watering frequency context','浇水可能不合适','进入浇水频率问题。',CONCAT('- {{watering_reference}}', CHAR(10), '- 如果最近浇得更勤、更少，或土长期偏湿/偏干，先选这个。'),10,1,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','养护 gate 浇水选项，默认选中。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_care_area_gate','light_area','光照变化明显','',0,0,'audited','data_layer_template','route to light context','光照变化明显','进入光照问题。',CONCAT('- {{light_reference}}', CHAR(10), '- 如果最近直射太阳、遮阴程度或摆放位置变化明显，先选这个。'),20,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','养护 gate 光照选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_care_area_gate','fertilization_area','施肥或换盆变化','',0,0,'audited','data_layer_template','route to fertilization context','施肥或换盆变化','进入施肥问题。',CONCAT('- {{fertilization_reference}}', CHAR(10), '- 如果最近长期没补肥、补肥偏多，或刚换土换盆，先选这个。'),30,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','养护 gate 施肥选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_care_area_gate','airflow_humidity_area','通风或空气湿度变化','',0,0,'audited','data_layer_template','route to humidity progression context','通风或空气湿度变化','进入通风湿度问题。',CONCAT('- {{humidity_reference}}', CHAR(10), '- 如果最近环境更闷、更湿或更干，先选这个。'),40,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','养护 gate 通风湿度选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_care_area_gate','unknown','没有明显变化 / 不确定','',0,0,'audited','data_layer_template','route back to yellowing pattern','没有明显变化 / 不确定','进入黄叶位置和分布分流。',CONCAT('- 如果看不出哪项最可疑，选这个。', CHAR(10), '- 系统会回到黄叶本身的新老叶和分布线索继续排查。'),50,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','养护 gate 不确定选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__watering_frequency_context','often_wet','{{watering_too_often}}','',0,0,'audited','data_layer_template','watering too frequent context','{{watering_too_often}}','记录浇水偏勤或盆土偏湿背景。','',10,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','浇水偏勤选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__watering_frequency_context','normal_or_stable','{{watering_normal}}','',0,0,'audited','data_layer_template','watering near reference context','{{watering_normal}}','记录浇水接近参考范围。','',20,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','浇水接近参考选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__watering_frequency_context','often_dry','{{watering_too_rare}}','',0,0,'audited','data_layer_template','watering too rare context','{{watering_too_rare}}','记录浇水偏少或盆土长期偏干背景。','',30,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','浇水偏少选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__watering_frequency_context','unknown','不确定','',0,0,'audited','data_layer_template','unknown watering context','不确定','暂不记录明确浇水背景。','',40,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','浇水不确定选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__light_change_context','stronger_direct_light','每天直射 3 小时以上，或最近突然晒得更多','',0,0,'audited','data_layer_template','stronger direct light context','每天直射 3 小时以上，或最近突然晒得更多','记录直射光偏强或突然增多。','',10,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','强光选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__light_change_context','no_clear_change','每天直射约 1-3 小时，且最近基本没变','',0,0,'audited','data_layer_template','stable light context','每天直射约 1-3 小时，且最近基本没变','记录光照变化不明显。','',20,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','光照稳定选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__light_change_context','weaker_light','每天直射 0-1 小时，或最近明显更阴','',0,0,'audited','data_layer_template','weaker light context','每天直射 0-1 小时，或最近明显更阴','记录光照偏弱或突然变阴。','',30,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','弱光选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__light_change_context','unknown','不确定 / 没留意','',0,0,'audited','data_layer_template','unknown light context','不确定 / 没留意','暂不记录明确光照背景。','',40,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','光照不确定选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__fertilization_growth_context','low_or_no_fertilizer','近 2 个月 0 次，或明显少于平时','',0,0,'audited','data_layer_template','low fertilizer context','近 2 个月 0 次，或明显少于平时','记录长期没补肥或明显少于平时。','',10,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','低施肥选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__fertilization_growth_context','normal_light_fertilizer','近 1 个月 1 次薄肥，或按平时少量补肥','',0,0,'audited','data_layer_template','normal fertilizer context','近 1 个月 1 次薄肥，或按平时少量补肥','记录施肥接近平时节奏。','',20,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','正常施肥选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__fertilization_growth_context','recent_heavy_fertilizer_or_repot','近 1 个月 2 次以上、重肥，或刚换盆/换土','',0,0,'audited','data_layer_template','heavy fertilizer or repot context','近 1 个月 2 次以上、重肥，或刚换盆/换土','记录近期重肥、频繁施肥或换土换盆刺激。','',30,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','重肥换盆选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__fertilization_growth_context','unknown','不确定','',0,0,'audited','data_layer_template','unknown fertilizer context','不确定','暂不记录明确施肥背景。','',40,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','施肥不确定选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__pest_trace_type','mite_webbing','叶背或叶柄附近有细网、蜕皮，或极小活动点','',0,0,'audited','data_layer_template','pest mite trace','叶背或叶柄附近有细网、蜕皮，或极小活动点','记录螨类/红蜘蛛方向线索。','',10,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','虫害细网活动点选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__pest_trace_type','thrips_silver_black','有银白擦伤样痕迹，并伴很小的黑色排泄点','',0,0,'audited','data_layer_template','pest thrips trace','有银白擦伤样痕迹，并伴很小的黑色排泄点','记录蓟马方向线索。','',20,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','蓟马痕迹选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__pest_trace_type','sticky_honeydew','表面发黏，或附近有蜜露/煤灰样黑层','',0,0,'audited','data_layer_template','pest honeydew trace','表面发黏，或附近有蜜露/煤灰样黑层','记录蜜露类刺吸害虫方向线索。','',30,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','蜜露发黏选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__pest_trace_type','no_pest_trace','没有这些虫害痕迹，更像晒伤、肥害、旧伤或普通变色','',0,0,'audited','data_layer_template','no pest trace','没有这些虫害痕迹，更像晒伤、肥害、旧伤或普通变色','记录未见直接虫害线索。','',40,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','无虫害痕迹选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__pest_trace_type','unknown','看不出 / 不确定','',0,0,'audited','data_layer_template','unknown pest trace','看不出 / 不确定','暂不记录明确虫害线索。','',50,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','虫害不确定选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_disease_trace_gate','halo_spots','有褐色或黑色斑点，周围还有一圈发黄','',0,0,'audited','data_layer_template','halo spots trace','有褐色或黑色斑点，周围还有一圈发黄','记录叶斑带黄晕线索。','',10,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','病斑黄晕选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_disease_trace_gate','water_soaked_soft','斑点像被水浸过，发暗、半透明或偏软','',0,0,'audited','data_layer_template','water soaked trace','斑点像被水浸过，发暗、半透明或偏软','记录水渍感或湿软线索。','',20,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','水渍软斑选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_disease_trace_gate','powder_mold_surface','表面像有粉、霉、灰尘或脏层','',0,0,'audited','data_layer_template','powder mold trace','表面像有粉、霉、灰尘或脏层','记录粉层、霉层或表面附着线索。','',30,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','粉霉表层选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_disease_trace_gate','yellowing_only_no_lesion','只是颜色发黄，没有明显斑点或烂斑','',0,0,'audited','data_layer_template','yellowing without lesion','只是颜色发黄，没有明显斑点或烂斑','记录未见病斑或霉层线索。','',40,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','无病斑选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_disease_trace_gate','unknown','不确定','',0,0,'audited','data_layer_template','unknown disease trace','不确定','暂不记录明确病斑线索。','',50,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','病斑不确定选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_leaf_age_pattern','new_leaves_first','新叶更明显','',0,0,'audited','data_layer_template','new leaves first','新叶更明显','记录新叶先黄。','',10,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','新叶选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_leaf_age_pattern','old_lower_leaves_first','老叶或下部叶更明显','',0,0,'audited','data_layer_template','old lower leaves first','老叶或下部叶更明显','记录老叶或下部叶先黄。','',20,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','老叶选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_leaf_age_pattern','no_clear_age_bias','新老叶差不多，或看不出先后','',0,0,'audited','data_layer_template','no age bias','新老叶差不多，或看不出先后','记录新老叶先后不明显。','',30,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','无叶龄差异选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_leaf_age_pattern','unknown','不确定','',0,0,'audited','data_layer_template','unknown age bias','不确定','暂不记录明确叶龄分布。','',40,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','叶龄不确定选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_distribution_pattern','uniform_whole_leaf','整片叶比较均匀地发黄','',0,0,'audited','data_layer_template','uniform yellowing','整片叶比较均匀地发黄','记录均匀黄化。','',10,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','均匀黄化选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_distribution_pattern','interveinal','叶脉附近还绿，叶脉之间更黄','',0,0,'audited','data_layer_template','interveinal yellowing','叶脉附近还绿，叶脉之间更黄','记录脉间黄化。','',20,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','脉间黄化选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_distribution_pattern','patchy_or_speckled','一块块、斑驳，或很多小黄点','',0,0,'audited','data_layer_template','patchy speckled yellowing','一块块、斑驳，或很多小黄点','记录斑驳或黄点。','',30,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','斑驳黄化选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_distribution_pattern','edge_or_scorch_patch','主要是叶边或局部一块发黄发浅，像晒后留下的伤斑','',0,0,'audited','data_layer_template','edge scorch yellowing','主要是叶边或局部一块发黄发浅，像晒后留下的伤斑','记录叶边或晒伤样局部黄化。','',40,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','叶边晒伤样选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_distribution_pattern','unknown','不确定','',0,0,'audited','data_layer_template','unknown distribution','不确定','暂不记录明确黄叶分布。','',50,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','分布不确定选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_progression_speed','rapid_spreading','几天到一两周内明显变多/变重','',0,0,'audited','data_layer_template','rapid yellowing progression','几天到一两周内明显变多/变重','记录黄叶快速加重。','',10,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','快速进展选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_progression_speed','slow_stable','变化较慢，基本稳定','',0,0,'audited','data_layer_template','slow stable yellowing','变化较慢，基本稳定','记录黄叶变化较慢。','',20,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','慢速稳定选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_progression_speed','with_wilting_or_drop','同时明显萎蔫、掉叶或软塌','',0,0,'audited','data_layer_template','yellowing with wilting or drop','同时明显萎蔫、掉叶或软塌','记录黄叶伴随萎蔫、掉叶或软塌。','',30,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','萎蔫掉叶选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429'),
('q_observed_probe__leaf_yellowing__yellowing_progression_speed','unknown','不确定','',0,0,'audited','data_layer_template','unknown yellowing progression','不确定','暂不记录明确进展速度。','',40,0,'manual','question_data_layer_templates_20260429','v20260429_data_layer_templates','audited','进展不确定选项。',1,NOW(),NOW(),NOW(),'question_data_layer_templates_20260429')
ON DUPLICATE KEY UPDATE
  `option_text_cn` = VALUES(`option_text_cn`),
  `option_text_user_cn` = VALUES(`option_text_user_cn`),
  `answer_effect_cn` = VALUES(`answer_effect_cn`),
  `option_description_user_cn` = VALUES(`option_description_user_cn`),
  `display_order` = VALUES(`display_order`),
  `is_default` = VALUES(`is_default`),
  `data_status` = VALUES(`data_status`),
  `review_status` = VALUES(`review_status`),
  `note` = VALUES(`note`),
  `review_note` = VALUES(`review_note`),
  `is_active` = 1,
  `updated_at` = NOW(),
  `published_at` = NOW(),
  `published_batch_id` = VALUES(`published_batch_id`);
