ALTER TABLE `question_library_v5_real`
  ADD COLUMN IF NOT EXISTS `target_dimension` VARCHAR(64) NULL COMMENT '问题要确认或分流的事实维度' AFTER `observability`,
  ADD COLUMN IF NOT EXISTS `routing_scope` VARCHAR(64) NULL COMMENT 'symptom_confirmation|differential_probe|context_probe' AFTER `target_dimension`;

ALTER TABLE `question_generation_engine`
  ADD COLUMN IF NOT EXISTS `target_dimension_default` VARCHAR(64) NULL COMMENT '生成规则默认目标维度' AFTER `observability_default`,
  ADD COLUMN IF NOT EXISTS `routing_scope_default` VARCHAR(64) NULL COMMENT '生成规则默认分流范围' AFTER `target_dimension_default`;

UPDATE `question_library_v5_real`
SET
  `target_dimension` = COALESCE(`target_dimension`, 'visual_presence'),
  `routing_scope` = COALESCE(`routing_scope`, 'symptom_confirmation')
WHERE `data_status` = 'audited'
  AND `review_status` = 'audited';

UPDATE `question_library_v5_real`
SET
  `target_dimension` = CASE `question_key`
    WHEN 'q_bacterial_water_soaked' THEN 'tissue_moisture'
    WHEN 'q_sooty_mold_confirm' THEN 'surface_residue'
    WHEN 'q_aphids_sooty_mold' THEN 'surface_residue'
    WHEN 'q_scale_sooty_mold' THEN 'surface_residue'
    WHEN 'q_whiteflies_sooty_mold' THEN 'surface_residue'
    ELSE `target_dimension`
  END,
  `routing_scope` = CASE `question_key`
    WHEN 'q_bacterial_water_soaked' THEN 'differential_probe'
    WHEN 'q_sooty_mold_confirm' THEN 'differential_probe'
    WHEN 'q_aphids_sooty_mold' THEN 'differential_probe'
    WHEN 'q_scale_sooty_mold' THEN 'differential_probe'
    WHEN 'q_whiteflies_sooty_mold' THEN 'differential_probe'
    ELSE `routing_scope`
  END
WHERE `question_key` IN (
  'q_bacterial_water_soaked',
  'q_sooty_mold_confirm',
  'q_aphids_sooty_mold',
  'q_scale_sooty_mold',
  'q_whiteflies_sooty_mold'
);

INSERT INTO `question_library_v5_real` (
  `question_key`,
  `question_text_cn`,
  `question_type`,
  `target_symptom_key`,
  `question_group_key`,
  `question_level`,
  `observability`,
  `target_dimension`,
  `routing_scope`,
  `allow_unknown`,
  `priority`,
  `data_status`,
  `data_source`,
  `note`,
  `question_text_user_cn`,
  `help_text_cn`,
  `why_this_question_cn`,
  `source_type`,
  `source_batch_id`,
  `version_tag`,
  `row_hash`,
  `review_status`,
  `review_note`,
  `is_active`,
  `created_at`,
  `updated_at`,
  `published_at`,
  `published_batch_id`
) VALUES
(
  'q_black_spots_surface_layer_check',
  '这些黑斑更像长在叶组织里面，还是像浮在表面的脏层、轻擦会蹭开？',
  'single_choice',
  'black_spots_spreading',
  'leaf_surface_residue_group',
  1,
  'high',
  'surface_residue',
  'differential_probe',
  1,
  95,
  'audited',
  'https://extension.umn.edu/disease-management/alternaria-leaf-blight | https://www.rhs.org.uk/advice/profile?pid=270 | https://www.rhs.org.uk/disease/escallonia-leaf-spot | https://extension.umd.edu/resource/honeydew-and-sooty-mold | https://ipm.ucanr.edu/home-and-landscape/sooty-mold/',
  'black_spots_spreading / differential_probe / source-backed audited dimension upgrade',
  '这些黑斑更像长在叶组织里面，还是像浮在表面的脏层、轻擦会蹭开？',
  '可以轻轻擦拭叶面；若像浮灰或煤污附着在表面并能被蹭开，更像表面附着层，而不是嵌入叶组织的坏死斑。',
  '用于区分嵌入叶组织的坏死性黑斑与表面附着层，避免把煤污、脏层和扩散性黑斑混成同一视觉事实。',
  'manual',
  'batch_20260413_question_dimension_upgrade',
  'v20260413_question_dimension_v1',
  '3fcddff0aa36c15b161c6cd48602655e4e87b8f442ba7eff31b63450fd65d75a',
  'audited',
  'source-backed manual audit (2026-04-13): leaf spot vs sooty mold differential probe',
  1,
  '2026-04-13 23:55:00',
  '2026-04-13 23:55:00',
  '2026-04-13 23:55:00',
  'batch_20260413_question_dimension_upgrade'
),
(
  'q_black_spots_tissue_moisture_check',
  '斑点附近叶组织更像干硬坏死，还是发软、带水渍感？',
  'single_choice',
  'black_spots_spreading',
  'leaf_spot_texture_group',
  1,
  'high',
  'tissue_moisture',
  'differential_probe',
  1,
  94,
  'audited',
  'https://extension.umn.edu/disease-management/alternaria-leaf-blight | https://www.rhs.org.uk/advice/profile?pid=270 | https://www.rhs.org.uk/disease/escallonia-leaf-spot | https://content.ces.ncsu.edu/leaf-spotting-bacteria-on-ornamentals | https://extension.umn.edu/disease-management/bacterial-spot-tomato-and-pepper',
  'black_spots_spreading / differential_probe / source-backed audited dimension upgrade',
  '斑点附近叶组织更像干硬坏死，还是发软、带水渍感？',
  '可结合手感和病斑边缘判断；若病斑区域发软、湿润或半透明，更像水渍样组织受损，不是典型干性坏死斑。',
  '用于区分干性坏死黑斑与水渍样病斑，避免继续围绕“有没有黑斑”做同维度重复确认。',
  'manual',
  'batch_20260413_question_dimension_upgrade',
  'v20260413_question_dimension_v1',
  '86bc9162f0b8a6a694be5be6f4149c9ef1c004f68b3e34691f818975e7bb3182',
  'audited',
  'source-backed manual audit (2026-04-13): necrotic dry spot vs water-soaked tissue differential probe',
  1,
  '2026-04-13 23:55:00',
  '2026-04-13 23:55:00',
  '2026-04-13 23:55:00',
  'batch_20260413_question_dimension_upgrade'
)
ON DUPLICATE KEY UPDATE
  `question_text_cn` = VALUES(`question_text_cn`),
  `question_type` = VALUES(`question_type`),
  `target_symptom_key` = VALUES(`target_symptom_key`),
  `question_group_key` = VALUES(`question_group_key`),
  `question_level` = VALUES(`question_level`),
  `observability` = VALUES(`observability`),
  `target_dimension` = VALUES(`target_dimension`),
  `routing_scope` = VALUES(`routing_scope`),
  `allow_unknown` = VALUES(`allow_unknown`),
  `priority` = VALUES(`priority`),
  `data_status` = VALUES(`data_status`),
  `data_source` = VALUES(`data_source`),
  `note` = VALUES(`note`),
  `question_text_user_cn` = VALUES(`question_text_user_cn`),
  `help_text_cn` = VALUES(`help_text_cn`),
  `why_this_question_cn` = VALUES(`why_this_question_cn`),
  `source_type` = VALUES(`source_type`),
  `source_batch_id` = VALUES(`source_batch_id`),
  `version_tag` = VALUES(`version_tag`),
  `row_hash` = VALUES(`row_hash`),
  `review_status` = VALUES(`review_status`),
  `review_note` = VALUES(`review_note`),
  `is_active` = VALUES(`is_active`),
  `created_at` = VALUES(`created_at`),
  `updated_at` = VALUES(`updated_at`),
  `published_at` = VALUES(`published_at`),
  `published_batch_id` = VALUES(`published_batch_id`);

INSERT INTO `question_option_mapping_v5_real` (
  `question_key`,
  `option_key`,
  `option_text_cn`,
  `maps_to_symptom_key`,
  `value`,
  `association_strength`,
  `data_status`,
  `data_source`,
  `note`,
  `option_text_user_cn`,
  `answer_effect_cn`,
  `source_type`,
  `source_batch_id`,
  `version_tag`,
  `row_hash`,
  `review_status`,
  `review_note`,
  `is_active`,
  `created_at`,
  `updated_at`,
  `published_at`,
  `published_batch_id`
) VALUES
(
  'q_black_spots_surface_layer_check',
  'embedded',
  '像长在叶子里面，擦不掉',
  'black_spots_spreading',
  1,
  1,
  'audited',
  'https://extension.umn.edu/disease-management/alternaria-leaf-blight | https://www.rhs.org.uk/advice/profile?pid=270 | https://www.rhs.org.uk/disease/escallonia-leaf-spot | https://extension.umd.edu/resource/honeydew-and-sooty-mold | https://ipm.ucanr.edu/home-and-landscape/sooty-mold/',
  'surface residue differential / positive black spot support',
  '像长在叶子里面，擦不掉',
  '更支持这是嵌入叶组织的黑斑扩散，而不是表面附着层。',
  'manual',
  'batch_20260413_question_dimension_upgrade',
  'v20260413_question_dimension_v1',
  '9ac46d2cf52c9e5e72d4ff0ad4db55b51af8d7ef4e94c9a94ea9a63616f0db8a',
  'audited',
  'source-backed manual audit (2026-04-13)',
  1,
  '2026-04-13 23:55:00',
  '2026-04-13 23:55:00',
  '2026-04-13 23:55:00',
  'batch_20260413_question_dimension_upgrade'
),
(
  'q_black_spots_surface_layer_check',
  'surface',
  '更像浮在表面，轻擦会蹭开',
  'black_spots_spreading',
  -1,
  1,
  'audited',
  'https://extension.umd.edu/resource/honeydew-and-sooty-mold | https://ipm.ucanr.edu/home-and-landscape/sooty-mold/ | https://extension.umn.edu/disease-management/alternaria-leaf-blight',
  'surface residue differential / negative black spot support',
  '更像浮在表面，轻擦会蹭开',
  '会削弱“黑斑扩散”这一嵌入式坏死斑解释，提示进一步考虑表面附着层方向。',
  'manual',
  'batch_20260413_question_dimension_upgrade',
  'v20260413_question_dimension_v1',
  'f0becd9f56c98e756c16dbfdf866655f87fb50d36baadba892c18ab28a5c30a8',
  'audited',
  'source-backed manual audit (2026-04-13)',
  1,
  '2026-04-13 23:55:00',
  '2026-04-13 23:55:00',
  '2026-04-13 23:55:00',
  'batch_20260413_question_dimension_upgrade'
),
(
  'q_black_spots_surface_layer_check',
  'unknown',
  '看不出/不确定',
  'black_spots_spreading',
  0,
  0,
  'audited',
  'https://extension.umn.edu/disease-management/alternaria-leaf-blight | https://extension.umd.edu/resource/honeydew-and-sooty-mold',
  'surface residue differential / neutral',
  '看不出/不确定',
  '暂不把表面附着/嵌入组织这一维度作为正式证据。',
  'manual',
  'batch_20260413_question_dimension_upgrade',
  'v20260413_question_dimension_v1',
  '115e335cf528fe6e5f785f00d3370ca2bddfc2f213a1eb3207a314e71f7f5577',
  'audited',
  'source-backed manual audit (2026-04-13)',
  1,
  '2026-04-13 23:55:00',
  '2026-04-13 23:55:00',
  '2026-04-13 23:55:00',
  'batch_20260413_question_dimension_upgrade'
),
(
  'q_black_spots_tissue_moisture_check',
  'dry_firm',
  '更像干硬坏死，不发软',
  'black_spots_spreading',
  1,
  1,
  'audited',
  'https://extension.umn.edu/disease-management/alternaria-leaf-blight | https://www.rhs.org.uk/advice/profile?pid=270 | https://content.ces.ncsu.edu/leaf-spotting-bacteria-on-ornamentals',
  'tissue moisture differential / positive black spot support',
  '更像干硬坏死，不发软',
  '更支持干性坏死黑斑，而不是水渍样组织损伤。',
  'manual',
  'batch_20260413_question_dimension_upgrade',
  'v20260413_question_dimension_v1',
  '8940a173a67dc1ba33cd61d5cf3dde6864cc1575d7911edb649ef79e2636fa46',
  'audited',
  'source-backed manual audit (2026-04-13)',
  1,
  '2026-04-13 23:55:00',
  '2026-04-13 23:55:00',
  '2026-04-13 23:55:00',
  'batch_20260413_question_dimension_upgrade'
),
(
  'q_black_spots_tissue_moisture_check',
  'soft_wet',
  '发软、湿润或带水渍感',
  'black_spots_spreading',
  -1,
  1,
  'audited',
  'https://content.ces.ncsu.edu/leaf-spotting-bacteria-on-ornamentals | https://extension.umn.edu/disease-management/bacterial-spot-tomato-and-pepper | https://extension.umn.edu/disease-management/alternaria-leaf-blight',
  'tissue moisture differential / negative black spot support',
  '发软、湿润或带水渍感',
  '会削弱“黑斑扩散”的干性坏死解释，提示进一步考虑水渍样病斑方向。',
  'manual',
  'batch_20260413_question_dimension_upgrade',
  'v20260413_question_dimension_v1',
  '85307c40ac2d95ce224fb471666915f9228b6bbf0633123ab70457e947576d90',
  'audited',
  'source-backed manual audit (2026-04-13)',
  1,
  '2026-04-13 23:55:00',
  '2026-04-13 23:55:00',
  '2026-04-13 23:55:00',
  'batch_20260413_question_dimension_upgrade'
),
(
  'q_black_spots_tissue_moisture_check',
  'unknown',
  '看不出/不确定',
  'black_spots_spreading',
  0,
  0,
  'audited',
  'https://extension.umn.edu/disease-management/alternaria-leaf-blight | https://content.ces.ncsu.edu/leaf-spotting-bacteria-on-ornamentals',
  'tissue moisture differential / neutral',
  '看不出/不确定',
  '暂不把组织干硬/湿软这一维度作为正式证据。',
  'manual',
  'batch_20260413_question_dimension_upgrade',
  'v20260413_question_dimension_v1',
  'cf73dd603ed0c7e22169a5ff8b7930ca3d38c8694f2d376cf6ff91f771e99f06',
  'audited',
  'source-backed manual audit (2026-04-13)',
  1,
  '2026-04-13 23:55:00',
  '2026-04-13 23:55:00',
  '2026-04-13 23:55:00',
  'batch_20260413_question_dimension_upgrade'
)
ON DUPLICATE KEY UPDATE
  `option_text_cn` = VALUES(`option_text_cn`),
  `maps_to_symptom_key` = VALUES(`maps_to_symptom_key`),
  `value` = VALUES(`value`),
  `association_strength` = VALUES(`association_strength`),
  `data_status` = VALUES(`data_status`),
  `data_source` = VALUES(`data_source`),
  `note` = VALUES(`note`),
  `option_text_user_cn` = VALUES(`option_text_user_cn`),
  `answer_effect_cn` = VALUES(`answer_effect_cn`),
  `source_type` = VALUES(`source_type`),
  `source_batch_id` = VALUES(`source_batch_id`),
  `version_tag` = VALUES(`version_tag`),
  `row_hash` = VALUES(`row_hash`),
  `review_status` = VALUES(`review_status`),
  `review_note` = VALUES(`review_note`),
  `is_active` = VALUES(`is_active`),
  `created_at` = VALUES(`created_at`),
  `updated_at` = VALUES(`updated_at`),
  `published_at` = VALUES(`published_at`),
  `published_batch_id` = VALUES(`published_batch_id`);

UPDATE `question_generation_engine`
SET
  `target_dimension_default` = COALESCE(`target_dimension_default`, 'visual_presence'),
  `routing_scope_default` = COALESCE(`routing_scope_default`, 'symptom_confirmation');
