-- Ensure route-planned yellowing follow-up questions have SQL-owned titles/options.
-- Scope: schema columns required by current runtime + user-facing copy only.
-- Keep option_key and route semantics unchanged.

ALTER TABLE question_library_v5_real
  ADD COLUMN question_role VARCHAR(64) NULL COMMENT 'gate|differential_probe|context_metric|symptom_confirmation|visual_fact_review' AFTER routing_scope,
  ADD COLUMN effect_mode VARCHAR(64) NULL COMMENT 'route_gate|score_adjustment|evidence_admission|context_feature|visual_fact_review' AFTER question_role;

ALTER TABLE question_library_v5_real
  ADD COLUMN default_option_key VARCHAR(128) NULL COMMENT '默认选项 key，用于 gate 类题默认选中' AFTER why_this_question_cn,
  ADD COLUMN ui_variant VARCHAR(64) NULL COMMENT '前端展示形态，例如 single_select_accordion' AFTER default_option_key,
  ADD COLUMN render_mode VARCHAR(64) NULL COMMENT 'static|data_template|runtime_fallback' AFTER ui_variant,
  ADD COLUMN template_engine_rule_key VARCHAR(128) NULL COMMENT '关联 question_generation_engine.engine_rule_key' AFTER render_mode;

ALTER TABLE question_option_mapping_v5_real
  ADD COLUMN option_description_user_cn TEXT NULL COMMENT '用户可见选项说明' AFTER answer_effect_cn,
  ADD COLUMN display_order INT NULL COMMENT '选项展示顺序' AFTER option_description_user_cn,
  ADD COLUMN is_default TINYINT(1) NULL DEFAULT 0 COMMENT '是否为默认选项' AFTER display_order;

INSERT INTO question_library_v5_real (
  question_key, question_text_cn, question_type, target_symptom_key, question_group_key,
  question_level, observability, target_dimension, routing_scope, question_role, effect_mode,
  allow_unknown, priority, data_status, data_source, note, question_text_user_cn,
  help_text_cn, why_this_question_cn, default_option_key, ui_variant, render_mode,
  template_engine_rule_key, source_type, source_batch_id, version_tag, review_status,
  review_note, is_active, created_at, updated_at, published_at, published_batch_id
) VALUES
  ('q_observed_probe__leaf_yellowing__yellowing_primary_clue_gate', '这次黄叶，最明显的线索更接近哪一类？', 'single_choice', 'leaf_yellowing', 'observed_probe__leaf_yellowing__yellowing_primary_clue_gate', 1, 'high', 'yellowing_primary_clue_gate', 'differential_probe', 'gate', 'route_gate', 1, 260, 'audited', 'data_layer_template', 'yellowing primary clue gate copy owned by SQL', '这次黄叶，最明显的线索更接近哪一类？', '只选最明显的一类；如果看不准，可以选不确定。', '黄叶先分流到养护、虫害、病斑或单纯黄叶方向。', 'care_context', 'single_select_accordion', 'data_template', 'qge_yellowing_primary_clue_gate', 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '题干和选项由 SQL 治理。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__yellowing_care_area_gate', '最近 2 周，哪类养护变化最明显？', 'single_choice', 'leaf_yellowing', 'observed_probe__leaf_yellowing__yellowing_care_area_gate', 1, 'high', 'yellowing_care_area_gate', 'context_probe', 'gate', 'route_gate', 1, 250, 'audited', 'data_layer_template', 'yellowing care area gate copy owned by SQL', '最近 2 周，哪类养护变化最明显？', '不用先判断病因，只选最近最明显的实际变化。', '养护方向先细分到浇水、光照、施肥或通风湿度。', 'watering_area', 'single_select_accordion', 'data_template', 'qge_yellowing_care_area_gate', 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '题干和选项由 SQL 治理。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__watering_frequency_context', '最近 2 周，浇水频率更接近哪一种？', 'single_choice', 'leaf_yellowing', 'observed_probe__leaf_yellowing__watering_frequency_context', 1, 'medium', 'watering_frequency_context', 'context_probe', 'context_metric', 'context_feature', 1, 240, 'audited', 'data_layer_template', 'watering frequency copy owned by SQL', '最近 2 周，浇水频率更接近哪一种？', '只按实际频率选择；系统会结合植物养护基线判断偏多或偏少。', '浇水频率用于判断黄叶是否可能和根区长期偏湿或偏干有关。', '', 'single_select_accordion', 'data_template', 'qge_yellowing_watering_frequency_context', 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '题干和选项由 SQL 治理。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__light_change_context', '最近 1-2 周，光照更接近哪一种？', 'single_choice', 'leaf_yellowing', 'observed_probe__leaf_yellowing__light_change_context', 1, 'medium', 'light_change_context', 'context_probe', 'context_metric', 'context_feature', 1, 230, 'audited', 'data_layer_template', 'light copy owned by SQL', '最近 1-2 周，光照更接近哪一种？', '按直射、散光、全阴或离窗远近选择。', '光照用于判断黄叶是否可能和强光、弱光或摆放变化有关。', '', 'single_select_accordion', 'data_template', 'qge_yellowing_light_change_context', 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '题干和选项由 SQL 治理。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__fertilization_growth_context', '最近 1 个月，施肥或换盆更接近哪一种？', 'single_choice', 'leaf_yellowing', 'observed_probe__leaf_yellowing__fertilization_growth_context', 1, 'medium', 'fertilization_growth_context', 'context_probe', 'context_metric', 'context_feature', 1, 220, 'audited', 'data_layer_template', 'fertilization copy owned by SQL', '最近 1 个月，施肥或换盆更接近哪一种？', '只记录近期供肥和换盆背景，不直接等同于缺肥或肥害。', '施肥频率用于区分缺肥、重肥或换盆刺激等方向。', '', 'single_select_accordion', 'data_template', 'qge_yellowing_fertilization_growth_context', 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '题干和选项由 SQL 治理。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__yellowing_leaf_age_pattern', '黄叶最先、最明显出现在新叶还是老叶？', 'single_choice', 'leaf_yellowing', 'observed_probe__leaf_yellowing__yellowing_leaf_age_pattern', 1, 'medium', 'yellowing_leaf_age_pattern', 'differential_probe', 'differential_probe', 'score_adjustment', 1, 200, 'audited', 'data_layer_template', 'leaf age copy owned by SQL', '黄叶最先、最明显出现在新叶还是老叶？', '新叶和老叶的先后顺序，可帮助区分营养、光照和根区压力。', '黄叶位置用于区分新叶问题、老叶问题或全株性压力。', '', 'single_select_accordion', 'data_template', 'qge_yellowing_leaf_age_pattern', 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '题干和选项由 SQL 治理。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__yellowing_progression_speed', '最近 7 天，黄叶变化速度更接近哪一种？', 'single_choice', 'leaf_yellowing', 'observed_probe__leaf_yellowing__yellowing_progression_speed', 1, 'medium', 'yellowing_progression_speed', 'context_probe', 'context_metric', 'context_feature', 1, 180, 'audited', 'data_layer_template', 'progression copy owned by SQL', '最近 7 天，黄叶变化速度更接近哪一种？', '变化速度会影响是否进入根区压力、急性环境变化或稳定旧问题方向。', '黄叶进展速度用于判断是否存在急性压力或持续恶化。', '', 'single_select_accordion', 'data_template', 'qge_yellowing_progression_speed', 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '题干和选项由 SQL 治理。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515')
ON DUPLICATE KEY UPDATE
  question_text_cn = VALUES(question_text_cn),
  question_text_user_cn = VALUES(question_text_user_cn),
  help_text_cn = VALUES(help_text_cn),
  why_this_question_cn = VALUES(why_this_question_cn),
  question_role = VALUES(question_role),
  effect_mode = VALUES(effect_mode),
  default_option_key = VALUES(default_option_key),
  ui_variant = VALUES(ui_variant),
  render_mode = VALUES(render_mode),
  template_engine_rule_key = VALUES(template_engine_rule_key),
  data_status = VALUES(data_status),
  review_status = VALUES(review_status),
  is_active = 1,
  updated_at = NOW(),
  published_at = NOW(),
  published_batch_id = VALUES(published_batch_id);

INSERT INTO question_option_mapping_v5_real (
  question_key, option_key, option_text_cn, maps_to_symptom_key, value,
  association_strength, data_status, data_source, note, option_text_user_cn,
  answer_effect_cn, option_description_user_cn, display_order, is_default,
  source_type, source_batch_id, version_tag, review_status, review_note,
  is_active, created_at, updated_at, published_at, published_batch_id
) VALUES
  ('q_observed_probe__leaf_yellowing__yellowing_primary_clue_gate', 'care_context', '日常养护变化明显', '', 0, 0, 'audited', 'data_layer_template', 'route to care gate', '日常养护变化明显', '进入浇水、光照、施肥、通风湿度分流。', '例如最近浇水、光照、施肥、摆放位置或通风湿度有明显变化。', 10, 1, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__yellowing_primary_clue_gate', 'pest_trace', '看到虫子或虫害痕迹', '', 0, 0, 'audited', 'data_layer_template', 'route to pest trace branch', '看到虫子或虫害痕迹', '进入虫害线索分流。', '例如小虫、虫卵、细网、黑点、叶面发黏，或叶背有活动点。', 20, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__yellowing_primary_clue_gate', 'disease_trace', '还有斑点、烂斑或霉粉', '', 0, 0, 'audited', 'data_layer_template', 'route to disease trace branch', '还有斑点、烂斑或霉粉', '进入病斑线索分流。', '例如褐斑、黑斑、水渍感、软烂、霉层或粉状物。', 30, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__yellowing_primary_clue_gate', 'yellowing_only', '只是发黄，没看到其他异常', '', 0, 0, 'audited', 'data_layer_template', 'route to yellowing pattern branch', '只是发黄，没看到其他异常', '进入黄叶位置和分布分流。', '如果主要就是叶色变黄，暂时没看到虫子、病斑或明显养护变化，选这个。', 40, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__yellowing_primary_clue_gate', 'unknown', '不确定，继续帮我排查', '', 0, 0, 'audited', 'data_layer_template', 'route to conservative yellowing branch', '不确定，继续帮我排查', '进入保守分流。', '如果看不出最明显的方向，系统会继续从黄叶分布和新老叶位置排查。', 50, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__yellowing_care_area_gate', 'watering_area', '浇水变化明显', '', 0, 0, 'audited', 'data_layer_template', 'route to watering frequency context', '浇水变化明显', '进入浇水频率问题。', '最近浇得更勤、更少，或盆土经常偏湿/偏干。', 10, 1, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__yellowing_care_area_gate', 'light_area', '光照或摆放位置变化明显', '', 0, 0, 'audited', 'data_layer_template', 'route to light context', '光照或摆放位置变化明显', '进入光照问题。', '最近直射太阳、遮阴程度或离窗远近变化明显。', 20, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__yellowing_care_area_gate', 'fertilization_area', '施肥或换盆变化明显', '', 0, 0, 'audited', 'data_layer_template', 'route to fertilization context', '施肥或换盆变化明显', '进入施肥问题。', '最近长期没补肥、补肥偏多，或刚换土换盆。', 30, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__yellowing_care_area_gate', 'airflow_humidity_area', '通风或空气湿度变化明显', '', 0, 0, 'audited', 'data_layer_template', 'route to humidity progression context', '通风或空气湿度变化明显', '进入通风湿度问题。', '最近更闷、更潮、更干，或从靠近窗户改到远离窗户。', 40, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__yellowing_care_area_gate', 'unknown', '没有明显变化 / 不确定', '', 0, 0, 'audited', 'data_layer_template', 'route back to yellowing pattern', '没有明显变化 / 不确定', '进入黄叶位置和分布分流。', '看不出哪项最可疑时，回到黄叶本身的新老叶和分布继续排查。', 50, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__watering_frequency_context', 'often_wet', '每 1-2 天浇一次，或土没干就浇', '', 0, 0, 'audited', 'data_layer_template', 'watering too frequent context', '每 1-2 天浇一次，或土没干就浇', '记录浇水偏勤或盆土偏湿背景。', '', 10, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__watering_frequency_context', 'normal_or_stable', '每周 1-2 次，基本等土表干了再浇', '', 0, 0, 'audited', 'data_layer_template', 'watering near reference context', '每周 1-2 次，基本等土表干了再浇', '记录浇水接近参考范围。', '', 20, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__watering_frequency_context', 'often_dry', '近 2 周 0-1 次，或经常干透很久才浇', '', 0, 0, 'audited', 'data_layer_template', 'watering too rare context', '近 2 周 0-1 次，或经常干透很久才浇', '记录浇水偏少或盆土长期偏干背景。', '', 30, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__watering_frequency_context', 'unknown', '说不清 / 没留意', '', 0, 0, 'audited', 'data_layer_template', 'unknown watering context', '说不清 / 没留意', '暂不记录明确浇水背景。', '', 40, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__light_change_context', 'stronger_direct_light', '全日光，或每天直射 3 小时以上', '', 0, 0, 'audited', 'data_layer_template', 'stronger direct light context', '全日光，或每天直射 3 小时以上', '记录直射光偏强或突然增多。', '', 10, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__light_change_context', 'no_clear_change', '散光为主，最近位置基本没变', '', 0, 0, 'audited', 'data_layer_template', 'stable light context', '散光为主，最近位置基本没变', '记录光照变化不明显。', '', 20, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__light_change_context', 'weaker_light', '全阴、离窗较远，或最近明显更暗', '', 0, 0, 'audited', 'data_layer_template', 'weaker light context', '全阴、离窗较远，或最近明显更暗', '记录光照偏弱或突然变阴。', '', 30, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__light_change_context', 'unknown', '说不清 / 没留意', '', 0, 0, 'audited', 'data_layer_template', 'unknown light context', '说不清 / 没留意', '暂不记录明确光照背景。', '', 40, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__fertilization_growth_context', 'low_or_no_fertilizer', '近 1 个月 0 次，或已经很久没补肥', '', 0, 0, 'audited', 'data_layer_template', 'low fertilizer context', '近 1 个月 0 次，或已经很久没补肥', '记录长期没补肥或明显少于平时。', '', 10, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__fertilization_growth_context', 'normal_light_fertilizer', '每 2 周 1 次左右薄肥', '', 0, 0, 'audited', 'data_layer_template', 'normal fertilizer context', '每 2 周 1 次左右薄肥', '记录施肥接近平时节奏。', '', 20, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__fertilization_growth_context', 'recent_heavy_fertilizer_or_repot', '近 1 个月 2 次以上、重肥，或刚换盆/换土', '', 0, 0, 'audited', 'data_layer_template', 'heavy fertilizer or repot context', '近 1 个月 2 次以上、重肥，或刚换盆/换土', '记录近期重肥、频繁施肥或换土换盆刺激。', '', 30, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__fertilization_growth_context', 'unknown', '说不清 / 没留意', '', 0, 0, 'audited', 'data_layer_template', 'unknown fertilizer context', '说不清 / 没留意', '暂不记录明确施肥背景。', '', 40, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__yellowing_leaf_age_pattern', 'new_leaves_first', '新叶更明显', '', 0, 0, 'audited', 'data_layer_template', 'new leaves first', '新叶更明显', '记录新叶先黄。', '', 10, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__yellowing_leaf_age_pattern', 'old_lower_leaves_first', '老叶或下部叶更明显', '', 0, 0, 'audited', 'data_layer_template', 'old lower leaves first', '老叶或下部叶更明显', '记录老叶或下部叶先黄。', '', 20, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__yellowing_leaf_age_pattern', 'no_clear_age_bias', '新老叶差不多，或看不出先后', '', 0, 0, 'audited', 'data_layer_template', 'no age bias', '新老叶差不多，或看不出先后', '记录新老叶先后不明显。', '', 30, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__yellowing_leaf_age_pattern', 'unknown', '不确定', '', 0, 0, 'audited', 'data_layer_template', 'unknown age bias', '不确定', '暂不记录明确叶龄分布。', '', 40, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__yellowing_progression_speed', 'rapid_spreading', '几天到一两周内明显变多/变重', '', 0, 0, 'audited', 'data_layer_template', 'rapid yellowing progression', '几天到一两周内明显变多/变重', '记录黄叶快速加重。', '', 10, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__yellowing_progression_speed', 'slow_stable', '变化较慢，基本稳定', '', 0, 0, 'audited', 'data_layer_template', 'slow stable yellowing', '变化较慢，基本稳定', '记录黄叶变化较慢。', '', 20, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__yellowing_progression_speed', 'with_wilting_or_drop', '同时明显萎蔫、掉叶或软塌', '', 0, 0, 'audited', 'data_layer_template', 'yellowing with wilting or drop', '同时明显萎蔫、掉叶或软塌', '记录黄叶伴随萎蔫、掉叶或软塌。', '', 30, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515'),
  ('q_observed_probe__leaf_yellowing__yellowing_progression_speed', 'unknown', '不确定', '', 0, 0, 'audited', 'data_layer_template', 'unknown yellowing progression', '不确定', '暂不记录明确进展速度。', '', 40, 0, 'manual', 'question_copy_title_options_hardening_20260515', 'v20260515_q_copy_hard', 'audited', '自然化文案。', 1, NOW(), NOW(), NOW(), 'question_copy_title_options_hardening_20260515')
ON DUPLICATE KEY UPDATE
  option_text_cn = VALUES(option_text_cn),
  option_text_user_cn = VALUES(option_text_user_cn),
  answer_effect_cn = VALUES(answer_effect_cn),
  option_description_user_cn = VALUES(option_description_user_cn),
  display_order = VALUES(display_order),
  is_default = VALUES(is_default),
  data_status = VALUES(data_status),
  review_status = VALUES(review_status),
  is_active = 1,
  updated_at = NOW(),
  published_at = NOW(),
  published_batch_id = VALUES(published_batch_id);
