-- 青花植后端 v2 / identity 域空库 DDL。
-- `_openid` 仅满足 CloudBase 表结构兼容要求，固定为空，不参与统一用户归属。

CREATE TABLE `users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '统一用户内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `public_user_id` VARCHAR(64) NOT NULL COMMENT '高熵公开用户引用，格式 usr_...',
  `status` VARCHAR(24) NOT NULL COMMENT '用户状态：active、suspended、deleting、deleted',
  `session_version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '会话撤销版本',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_users_public_ref` (`public_user_id`),
  UNIQUE KEY `uq_user_id_created_at` (`id`, `created_at_ms`),
  KEY `idx_users_status` (`status`),
  CONSTRAINT `ck_users_status` CHECK (`status` IN ('active', 'suspended', 'deleting', 'deleted')),
  CONSTRAINT `ck_users_session_version` CHECK (`session_version` > 0),
  CONSTRAINT `ck_users_public_ref` CHECK (REGEXP_LIKE(`public_user_id`, '^usr_[A-Za-z0-9_-]{8,}$', 'c')),
  CONSTRAINT `ck_users_time` CHECK (`updated_at_ms` >= `created_at_ms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 统一用户主体';

CREATE TABLE `platform_identities` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '平台身份内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '关联统一用户内部主键',
  `platform` VARCHAR(24) NOT NULL COMMENT '平台：wechat、douyin、xiaohongshu、phone',
  `platform_subject_hash` CHAR(64) NOT NULL COMMENT '规范化平台主体标识的 HMAC-SHA-256 检索摘要；禁止使用无密钥摘要',
  `subject_hash_algorithm` VARCHAR(24) NOT NULL DEFAULT 'HMAC-SHA-256' COMMENT '主体检索摘要算法，当前固定 HMAC-SHA-256',
  `subject_hash_key_version` VARCHAR(64) NOT NULL COMMENT '受控 HMAC 密钥版本引用，不含密钥材料',
  `platform_subject_ciphertext` TEXT NULL COMMENT '需要回调时保存的服务端密文，禁止公开',
  `app_scope` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '平台应用范围，避免不同应用主体混淆',
  `binding_status` VARCHAR(24) NOT NULL COMMENT '绑定状态：active、revoked、conflicted',
  `active_slot` TINYINT GENERATED ALWAYS AS (CASE WHEN `binding_status` = 'active' THEN 1 ELSE NULL END) STORED COMMENT 'active 时占用唯一槽；其他状态为空，允许保留历史记录',
  `bound_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '绑定时间，UTC 毫秒',
  `revoked_at_ms` BIGINT UNSIGNED NULL COMMENT '撤销时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_platform_subject` (`platform`, `app_scope`, `platform_subject_hash`),
  UNIQUE KEY `uq_platform_identity_owner_platform` (`id`, `user_internal_id`, `platform`),
  UNIQUE KEY `uq_platform_identity_active_slot` (`user_internal_id`, `platform`, `app_scope`, `active_slot`),
  KEY `idx_platform_identity_user` (`user_internal_id`, `binding_status`),
  CONSTRAINT `ck_platform_identity_platform` CHECK (`platform` IN ('wechat', 'douyin', 'xiaohongshu', 'phone')),
  CONSTRAINT `ck_platform_identity_binding_status` CHECK (`binding_status` IN ('active', 'revoked', 'conflicted')),
  CONSTRAINT `ck_platform_identity_subject_hash` CHECK (REGEXP_LIKE(`platform_subject_hash`, '^[0-9a-f]{64}$', 'c')),
  CONSTRAINT `ck_platform_identity_hash_algorithm` CHECK (`subject_hash_algorithm` = 'HMAC-SHA-256'),
  CONSTRAINT `ck_platform_identity_key_version` CHECK (REGEXP_LIKE(`subject_hash_key_version`, '^[A-Za-z0-9._-]{1,64}$', 'c')),
  CONSTRAINT `ck_platform_identity_time` CHECK (`bound_at_ms` >= `created_at_ms` AND `updated_at_ms` >= `created_at_ms` AND (`revoked_at_ms` IS NULL OR `revoked_at_ms` >= `bound_at_ms`)),
  CONSTRAINT `ck_platform_identity_revocation` CHECK ((`binding_status` = 'active' AND `revoked_at_ms` IS NULL) OR (`binding_status` = 'revoked' AND `revoked_at_ms` IS NOT NULL) OR (`binding_status` = 'conflicted' AND `revoked_at_ms` IS NULL)),
  CONSTRAINT `fk_platform_identity_user` FOREIGN KEY (`user_internal_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 平台身份绑定';

CREATE TABLE `user_sessions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户会话内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `session_ref_hash` CHAR(64) NOT NULL COMMENT '高熵 bearer 会话令牌的 SHA-256 摘要；禁止保存原始令牌',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '关联统一用户内部主键',
  `platform_identity_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '本次会话所验证的平台身份绑定',
  `rotated_from_session_internal_id` BIGINT UNSIGNED NULL COMMENT '轮换前会话内部主键，用于审计与单向撤销链',
  `session_version` INT UNSIGNED NOT NULL COMMENT '签发时的用户会话版本',
  `authenticated_via` VARCHAR(24) NOT NULL COMMENT '本次验证平台，不保存平台主体标识',
  `status` VARCHAR(24) NOT NULL COMMENT '会话状态：active、revoked、expired',
  `issued_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '签发时间，UTC 毫秒',
  `expires_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '失效时间，UTC 毫秒',
  `revoked_at_ms` BIGINT UNSIGNED NULL COMMENT '撤销时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_session_ref_hash` (`session_ref_hash`),
  UNIQUE KEY `uq_user_session_owner` (`id`, `user_internal_id`),
  KEY `idx_user_session_active` (`user_internal_id`, `status`, `expires_at_ms`),
  CONSTRAINT `ck_user_session_platform` CHECK (`authenticated_via` IN ('wechat', 'douyin', 'xiaohongshu', 'phone')),
  CONSTRAINT `ck_user_session_status` CHECK (`status` IN ('active', 'revoked', 'expired')),
  CONSTRAINT `ck_user_session_hash` CHECK (REGEXP_LIKE(`session_ref_hash`, '^[0-9a-f]{64}$', 'c')),
  CONSTRAINT `ck_user_session_version` CHECK (`session_version` > 0),
  CONSTRAINT `ck_user_session_time` CHECK (`expires_at_ms` > `issued_at_ms`),
  CONSTRAINT `ck_user_session_time_order` CHECK (`issued_at_ms` >= `created_at_ms` AND `updated_at_ms` >= `created_at_ms`),
  CONSTRAINT `ck_user_session_revocation` CHECK ((`status` = 'revoked' AND `revoked_at_ms` IS NOT NULL) OR (`status` IN ('active', 'expired') AND `revoked_at_ms` IS NULL)),
  CONSTRAINT `ck_user_session_revoked_time` CHECK (`revoked_at_ms` IS NULL OR (`revoked_at_ms` >= `issued_at_ms` AND `revoked_at_ms` < `expires_at_ms`)),
  CONSTRAINT `fk_user_session_user` FOREIGN KEY (`user_internal_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_user_session_platform_identity` FOREIGN KEY (`platform_identity_internal_id`, `user_internal_id`, `authenticated_via`) REFERENCES `platform_identities` (`id`, `user_internal_id`, `platform`),
  CONSTRAINT `fk_user_session_rotated_from` FOREIGN KEY (`rotated_from_session_internal_id`, `user_internal_id`) REFERENCES `user_sessions` (`id`, `user_internal_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 用户登录会话';

CREATE TABLE `service_replay_nonces` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '服务防重放记录内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `service_name` VARCHAR(64) NOT NULL COMMENT '已注册内部服务名',
  `key_id` VARCHAR(64) NOT NULL COMMENT '已注册签名密钥版本标识，不含密钥材料',
  `nonce_hash` CHAR(64) NOT NULL COMMENT '请求 nonce 的 SHA-256 摘要',
  `signature_version` VARCHAR(32) NOT NULL COMMENT '内部签名合同版本',
  `request_timestamp_ms` BIGINT UNSIGNED NOT NULL COMMENT '签名请求时间，UTC 毫秒；用于限制时间窗',
  `body_sha256` CHAR(64) NOT NULL COMMENT '规范化请求体 SHA-256，防止签名后篡改',
  `scope_code` VARCHAR(100) NOT NULL COMMENT '本次签名允许的最小服务能力范围',
  `verified_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '完成验签并原子登记 nonce 的时间，UTC 毫秒',
  `expires_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '防重放记录失效时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_service_nonce` (`service_name`, `nonce_hash`),
  KEY `idx_service_nonce_expiry` (`expires_at_ms`),
  CONSTRAINT `ck_service_nonce_hash` CHECK (REGEXP_LIKE(`nonce_hash`, '^[0-9a-f]{64}$', 'c')),
  CONSTRAINT `ck_service_nonce_body_hash` CHECK (REGEXP_LIKE(`body_sha256`, '^[0-9a-f]{64}$', 'c')),
  CONSTRAINT `ck_service_nonce_time` CHECK (`expires_at_ms` > `verified_at_ms` AND `verified_at_ms` >= `created_at_ms` AND `updated_at_ms` >= `created_at_ms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 内部服务签名防重放';
