-- 青花植后端 v2 / user-plant 域空库 DDL。
-- 用户植物是长期养护、诊断、事实、计划与时间线的一等公民。

CREATE TABLE `user_plants` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户植物内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `public_user_plant_id` VARCHAR(64) NOT NULL COMMENT '高熵用户植物公开引用，格式 upl_...',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '所属统一用户内部主键',
  `lifecycle_status` VARCHAR(24) NOT NULL COMMENT '生命周期：active、archived、deleting、deleted',
  `current_identity_status` VARCHAR(24) NOT NULL COMMENT '当前身份：unidentified、candidate_pending、confirmed',
  `confirmed_identity_internal_id` BIGINT UNSIGNED NULL COMMENT '已确认的发布产品身份内部主键',
  `version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '乐观并发版本',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_plant_public_ref` (`public_user_plant_id`),
  UNIQUE KEY `uq_user_plant_owner_pair` (`user_internal_id`, `id`),
  KEY `idx_user_plant_list` (`user_internal_id`, `lifecycle_status`, `updated_at_ms`),
  CONSTRAINT `ck_user_plant_lifecycle_status` CHECK (`lifecycle_status` IN ('active', 'archived', 'deleting', 'deleted')),
  CONSTRAINT `ck_user_plant_current_identity_status` CHECK (`current_identity_status` IN ('unidentified', 'candidate_pending', 'confirmed')),
  CONSTRAINT `ck_user_plant_identity_projection` CHECK ((`current_identity_status` = 'confirmed' AND `confirmed_identity_internal_id` IS NOT NULL) OR (`current_identity_status` <> 'confirmed' AND `confirmed_identity_internal_id` IS NULL)),
  CONSTRAINT `fk_user_plant_user` FOREIGN KEY (`user_internal_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_user_plant_identity` FOREIGN KEY (`confirmed_identity_internal_id`) REFERENCES `plant_identities` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 用户植物聚合根';

CREATE TABLE `user_plant_profiles` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户植物档案内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '所属统一用户内部主键',
  `user_plant_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '所属用户植物内部主键',
  `nickname` VARCHAR(80) NOT NULL DEFAULT '' COMMENT '用户设置的植物昵称',
  `pot_profile_json` JSON NOT NULL COMMENT '盆器与介质结构化档案',
  `profile_completeness_version` VARCHAR(32) NOT NULL COMMENT '档案完整度规则版本',
  `profile_completed_at_ms` BIGINT UNSIGNED NULL COMMENT '首次满足完整档案时间，UTC 毫秒',
  `version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '乐观并发版本',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_plant_profile` (`user_plant_internal_id`),
  KEY `idx_user_plant_profile_owner` (`user_internal_id`, `user_plant_internal_id`),
  CONSTRAINT `fk_profile_owner_plant` FOREIGN KEY (`user_internal_id`, `user_plant_internal_id`) REFERENCES `user_plants` (`user_internal_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 用户植物个体档案';

CREATE TABLE `user_plant_care_contexts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '养护环境内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '所属统一用户内部主键',
  `user_plant_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '所属用户植物内部主键',
  `location_json` JSON NOT NULL COMMENT '脱敏位置与天气绑定配置',
  `cultivation_method` VARCHAR(32) NOT NULL COMMENT '栽培方式',
  `light_environment_json` JSON NOT NULL COMMENT '用户植物光照环境',
  `ventilation_environment_json` JSON NOT NULL COMMENT '空气交换、空间开放度、局部风源与直吹风险',
  `version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '乐观并发版本',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_plant_care_context` (`user_plant_internal_id`),
  KEY `idx_care_context_owner` (`user_internal_id`, `user_plant_internal_id`),
  CONSTRAINT `fk_care_context_owner_plant` FOREIGN KEY (`user_internal_id`, `user_plant_internal_id`) REFERENCES `user_plants` (`user_internal_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 用户植物养护环境';

CREATE TABLE `user_plant_identity_history` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '植物身份历史内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '所属统一用户内部主键',
  `user_plant_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '所属用户植物内部主键',
  `plant_identity_internal_id` BIGINT UNSIGNED NULL COMMENT '候选或确认产品身份内部主键',
  `history_status` VARCHAR(24) NOT NULL COMMENT '历史状态：candidate、confirmed、superseded、rejected',
  `source_type` VARCHAR(32) NOT NULL COMMENT '来源：user、baidu_candidate、admin_correction',
  `source_ref` VARCHAR(64) NOT NULL COMMENT '来源对象公开引用',
  `decided_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '状态决定时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_identity_history_source` (`user_plant_internal_id`, `source_type`, `source_ref`),
  KEY `idx_identity_history_owner` (`user_internal_id`, `user_plant_internal_id`, `decided_at_ms`),
  CONSTRAINT `fk_identity_history_owner_plant` FOREIGN KEY (`user_internal_id`, `user_plant_internal_id`) REFERENCES `user_plants` (`user_internal_id`, `id`),
  CONSTRAINT `fk_identity_history_identity` FOREIGN KEY (`plant_identity_internal_id`) REFERENCES `plant_identities` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 用户植物身份历史';

CREATE TABLE `user_plant_assets` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户植物资产内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `asset_ref` VARCHAR(64) NOT NULL COMMENT '高熵资产公开引用',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '所属统一用户内部主键',
  `user_plant_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '所属用户植物内部主键',
  `storage_file_id` VARCHAR(512) NOT NULL COMMENT 'CloudBase 私有文件标识，不是公开 URL',
  `asset_purpose` VARCHAR(32) NOT NULL COMMENT '用途：profile、growth、care_evidence、diagnosis_evidence',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：active、pending_cleanup、removed',
  `content_hash` CHAR(64) NOT NULL COMMENT '文件内容 SHA-256',
  `cleanup_after_ms` BIGINT UNSIGNED NULL COMMENT '允许清理时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_plant_asset_ref` (`asset_ref`),
  UNIQUE KEY `uq_user_plant_storage_file` (`storage_file_id`),
  KEY `idx_user_plant_asset_owner` (`user_internal_id`, `user_plant_internal_id`, `status`),
  CONSTRAINT `fk_asset_owner_plant` FOREIGN KEY (`user_internal_id`, `user_plant_internal_id`) REFERENCES `user_plants` (`user_internal_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 用户植物私有资产';

CREATE TABLE `user_plant_timeline_projection` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '时间线投影内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `timeline_item_ref` VARCHAR(64) NOT NULL COMMENT '高熵时间线项目公开引用',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '所属统一用户内部主键',
  `user_plant_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '所属用户植物内部主键',
  `source_domain` VARCHAR(32) NOT NULL COMMENT '来源业务域',
  `source_ref` VARCHAR(64) NOT NULL COMMENT '不可变来源对象公开引用',
  `item_type` VARCHAR(32) NOT NULL COMMENT '时间线展示类型',
  `occurred_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '业务发生时间，UTC 毫秒',
  `summary_json` JSON NOT NULL COMMENT '脱敏展示摘要',
  `projection_version` INT UNSIGNED NOT NULL COMMENT '来源聚合投影版本',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_timeline_source` (`source_domain`, `source_ref`),
  KEY `idx_timeline_owner_time` (`user_internal_id`, `user_plant_internal_id`, `occurred_at_ms`),
  CONSTRAINT `fk_timeline_owner_plant` FOREIGN KEY (`user_internal_id`, `user_plant_internal_id`) REFERENCES `user_plants` (`user_internal_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 用户植物时间线投影';

CREATE TABLE `guest_sessions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '游客会话内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `guest_session_ref` VARCHAR(64) NOT NULL COMMENT '高熵游客会话公开引用',
  `anonymous_subject_hash` CHAR(64) NOT NULL COMMENT 'CloudBase 匿名主体不可逆摘要',
  `possession_proof_hash` CHAR(64) NOT NULL COMMENT '服务端持有证明摘要',
  `possession_proof_version` INT UNSIGNED NOT NULL COMMENT '当前持有证明版本；每次安全轮换单调递增',
  `previous_possession_proof_hash` CHAR(64) NULL COMMENT '轮换宽限期内允许使用的上一版持有证明摘要',
  `previous_proof_valid_until_ms` BIGINT UNSIGNED NULL COMMENT '上一版持有证明宽限期截止时间，UTC 毫秒',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：active、completed、failed、expired',
  `issued_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '签发时间，UTC 毫秒',
  `expires_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '失效时间，UTC 毫秒',
  `failed_retention_until_ms` BIGINT UNSIGNED NULL COMMENT '失败或隔离记录最晚清理时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_guest_session_ref` (`guest_session_ref`),
  KEY `idx_guest_session_subject` (`anonymous_subject_hash`, `status`, `expires_at_ms`),
  CONSTRAINT `ck_guest_session_status` CHECK (`status` IN ('active', 'completed', 'failed', 'expired')),
  CONSTRAINT `ck_guest_session_time` CHECK (`expires_at_ms` > `issued_at_ms`),
  CONSTRAINT `ck_guest_session_proof_version` CHECK (`possession_proof_version` > 0),
  CONSTRAINT `ck_guest_session_previous_proof` CHECK ((`previous_possession_proof_hash` IS NULL AND `previous_proof_valid_until_ms` IS NULL) OR (`previous_possession_proof_hash` IS NOT NULL AND `previous_proof_valid_until_ms` IS NOT NULL AND `previous_proof_valid_until_ms` > `issued_at_ms` AND `previous_proof_valid_until_ms` <= `expires_at_ms`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 游客匿名会话';

CREATE TABLE `guest_plant_cases` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '游客植物案例内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `guest_plant_case_ref` VARCHAR(64) NOT NULL COMMENT '高熵单株游客案例公开引用',
  `guest_session_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '所属游客会话内部主键',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：active、completed、failed、expired、claimed',
  `completed_at_ms` BIGINT UNSIGNED NULL COMMENT '案例完成时间，UTC 毫秒',
  `expires_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '未认领案例失效时间，UTC 毫秒',
  `claimed_user_internal_id` BIGINT UNSIGNED NULL COMMENT '认领后的统一用户内部主键；仅为成功事实的当前投影',
  `claimed_user_plant_internal_id` BIGINT UNSIGNED NULL COMMENT '认领后的用户植物内部主键；仅为成功事实的当前投影',
  `version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '并发状态版本',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_guest_plant_case_ref` (`guest_plant_case_ref`),
  UNIQUE KEY `uq_guest_case_claim_projection_owner` (`id`, `claimed_user_internal_id`, `claimed_user_plant_internal_id`),
  KEY `idx_guest_case_session` (`guest_session_internal_id`, `status`, `expires_at_ms`),
  KEY `idx_guest_case_claimed_owner` (`claimed_user_internal_id`, `claimed_user_plant_internal_id`),
  CONSTRAINT `ck_guest_case_claim_projection` CHECK ((`status` = 'claimed' AND `claimed_user_internal_id` IS NOT NULL AND `claimed_user_plant_internal_id` IS NOT NULL) OR (`status` <> 'claimed' AND `claimed_user_internal_id` IS NULL AND `claimed_user_plant_internal_id` IS NULL)),
  CONSTRAINT `fk_guest_case_session` FOREIGN KEY (`guest_session_internal_id`) REFERENCES `guest_sessions` (`id`),
  CONSTRAINT `fk_guest_case_claim_user` FOREIGN KEY (`claimed_user_internal_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_guest_case_claim_plant` FOREIGN KEY (`claimed_user_internal_id`, `claimed_user_plant_internal_id`) REFERENCES `user_plants` (`user_internal_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 单株游客植物案例';

CREATE TABLE `guest_claim_commands` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '游客案例认领命令内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `claim_ref` VARCHAR(64) NOT NULL COMMENT '高熵认领结果公开引用',
  `guest_plant_case_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '待认领游客植物案例',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '执行认领的统一用户',
  `target_type` VARCHAR(32) NOT NULL COMMENT '目标：new_user_plant、existing_user_plant',
  `requested_user_plant_internal_id` BIGINT UNSIGNED NULL COMMENT '选择已有植物时的请求目标；新建目标时必须为空',
  `target_user_plant_internal_id` BIGINT UNSIGNED NULL COMMENT '认领成功后的目标用户植物',
  `idempotency_key` VARCHAR(128) NOT NULL COMMENT '规范化幂等键',
  `request_hash` CHAR(64) NOT NULL COMMENT '规范化请求 SHA-256，用于识别同键异参',
  `proof_version` INT UNSIGNED NOT NULL COMMENT '认领时已验证的游客持有证明版本；不保存原始证明',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：requested、processing、completed、failed',
  `processing_lease_owner_hash` CHAR(64) NULL COMMENT '处理租约持有者不可逆摘要；仅 processing 状态存在',
  `processing_lease_expires_at_ms` BIGINT UNSIGNED NULL COMMENT '处理租约失效时间，UTC 毫秒；用于崩溃恢复',
  `attempt_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '已开始处理次数；每次取得租约后递增',
  `failure_code` VARCHAR(64) NULL COMMENT '脱敏失败代码',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_guest_claim_ref` (`claim_ref`),
  UNIQUE KEY `uq_guest_claim_idempotency` (`user_internal_id`, `guest_plant_case_internal_id`, `idempotency_key`),
  UNIQUE KEY `uq_guest_claim_success_link` (`id`, `guest_plant_case_internal_id`, `user_internal_id`, `target_user_plant_internal_id`),
  KEY `idx_guest_claim_status` (`status`, `updated_at_ms`),
  KEY `idx_guest_claim_lease` (`status`, `processing_lease_expires_at_ms`),
  CONSTRAINT `ck_guest_claim_status` CHECK (`status` IN ('requested', 'processing', 'completed', 'failed')),
  CONSTRAINT `ck_guest_claim_target_type` CHECK (`target_type` IN ('new_user_plant', 'existing_user_plant')),
  CONSTRAINT `ck_guest_claim_requested_target` CHECK ((`target_type` = 'new_user_plant' AND `requested_user_plant_internal_id` IS NULL) OR (`target_type` = 'existing_user_plant' AND `requested_user_plant_internal_id` IS NOT NULL)),
  CONSTRAINT `ck_guest_claim_target_consistency` CHECK ((`target_type` = 'new_user_plant' AND `requested_user_plant_internal_id` IS NULL) OR (`target_type` = 'existing_user_plant' AND `requested_user_plant_internal_id` IS NOT NULL AND (`status` <> 'completed' OR `target_user_plant_internal_id` = `requested_user_plant_internal_id`))),
  CONSTRAINT `ck_guest_claim_proof_version` CHECK (`proof_version` > 0),
  CONSTRAINT `ck_guest_claim_processing_lease` CHECK ((`status` = 'processing' AND `processing_lease_owner_hash` IS NOT NULL AND `processing_lease_expires_at_ms` IS NOT NULL) OR (`status` <> 'processing' AND `processing_lease_owner_hash` IS NULL AND `processing_lease_expires_at_ms` IS NULL)),
  CONSTRAINT `ck_guest_claim_processing_lease_time` CHECK ((`status` = 'processing' AND `processing_lease_expires_at_ms` > `updated_at_ms`) OR (`status` <> 'processing' AND `processing_lease_expires_at_ms` IS NULL)),
  CONSTRAINT `ck_guest_claim_attempt_count` CHECK ((`status` = 'requested' AND `attempt_count` = 0) OR (`status` <> 'requested' AND `attempt_count` > 0)),
  CONSTRAINT `ck_guest_claim_completed_target` CHECK ((`status` = 'completed' AND `target_user_plant_internal_id` IS NOT NULL AND `failure_code` IS NULL) OR (`status` <> 'completed' AND `target_user_plant_internal_id` IS NULL)),
  CONSTRAINT `ck_guest_claim_failure_code` CHECK ((`status` = 'failed' AND `failure_code` IS NOT NULL) OR (`status` <> 'failed' AND `failure_code` IS NULL)),
  CONSTRAINT `fk_guest_claim_case` FOREIGN KEY (`guest_plant_case_internal_id`) REFERENCES `guest_plant_cases` (`id`),
  CONSTRAINT `fk_guest_claim_user` FOREIGN KEY (`user_internal_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_guest_claim_requested_target` FOREIGN KEY (`user_internal_id`, `requested_user_plant_internal_id`) REFERENCES `user_plants` (`user_internal_id`, `id`),
  CONSTRAINT `fk_guest_claim_target` FOREIGN KEY (`user_internal_id`, `target_user_plant_internal_id`) REFERENCES `user_plants` (`user_internal_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 游客案例一次性认领命令';

CREATE TABLE `guest_case_claims` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '游客案例成功认领投影内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `guest_plant_case_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '已成功认领的游客植物案例；每个案例只有一条不可变成功事实',
  `claim_command_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '产生本不可变成功事实的认领命令；claim_ref 必须从命令回读',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '认领统一用户内部主键',
  `user_plant_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '认领目标用户植物内部主键',
  `claimed_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '认领事务提交时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_guest_case_claim_once` (`guest_plant_case_internal_id`),
  UNIQUE KEY `uq_guest_case_claim_command` (`claim_command_internal_id`),
  UNIQUE KEY `uq_guest_case_claim_fact_identity` (`id`, `guest_plant_case_internal_id`, `user_internal_id`, `user_plant_internal_id`),
  KEY `idx_guest_case_claim_owner` (`user_internal_id`, `user_plant_internal_id`),
  CONSTRAINT `fk_guest_case_claim_case` FOREIGN KEY (`guest_plant_case_internal_id`) REFERENCES `guest_plant_cases` (`id`),
  CONSTRAINT `fk_guest_case_claim_command_success` FOREIGN KEY (`claim_command_internal_id`, `guest_plant_case_internal_id`, `user_internal_id`, `user_plant_internal_id`) REFERENCES `guest_claim_commands` (`id`, `guest_plant_case_internal_id`, `user_internal_id`, `target_user_plant_internal_id`),
  CONSTRAINT `fk_guest_case_claim_projection` FOREIGN KEY (`guest_plant_case_internal_id`, `user_internal_id`, `user_plant_internal_id`) REFERENCES `guest_plant_cases` (`id`, `claimed_user_internal_id`, `claimed_user_plant_internal_id`),
  CONSTRAINT `fk_guest_case_claim_owner_plant` FOREIGN KEY (`user_internal_id`, `user_plant_internal_id`) REFERENCES `user_plants` (`user_internal_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 游客案例唯一不可变成功认领事实';
