-- 青花植后端 v2 / subscription 域空库 DDL。
-- 积分与 AI 额度分别使用不可变账本；账户表只是可重建投影。

CREATE TABLE `capability_snapshots` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '能力裁决快照内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `snapshot_ref` VARCHAR(64) NOT NULL COMMENT '高熵内部快照引用，格式 cps_...；禁止进入公开响应',
  `subject_type` VARCHAR(16) NOT NULL COMMENT '主体类型：guest、user',
  `user_internal_id` BIGINT UNSIGNED NULL COMMENT '登录用户内部主键；游客必须为空',
  `tier` VARCHAR(16) NOT NULL COMMENT '能力级别：guest、free、trial、member',
  `allowed_capabilities_json` JSON NOT NULL COMMENT '本次请求允许调用的业务能力代码数组',
  `rewarded_ai_scopes_json` JSON NOT NULL COMMENT '允许消费奖励 AI 额度的生成式能力范围数组',
  `active_user_plant_limit` INT UNSIGNED NOT NULL COMMENT '允许拥有的活跃用户植物数量；游客固定为 0',
  `capability_policy_release_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '已发布能力策略内部主键；仅用于关联',
  `capability_policy_domain_code` VARCHAR(40) NOT NULL COMMENT '已发布能力策略所属领域，固定为 subscription',
  `capability_policy_code` VARCHAR(80) NOT NULL COMMENT '已发布能力策略代码，固定为 capability_catalog',
  `capability_policy_release_ref` VARCHAR(64) NOT NULL COMMENT '已发布能力策略高熵发布引用，用于审计回放',
  `capability_policy_release_version` VARCHAR(64) NOT NULL COMMENT '已发布能力策略版本；映射内部合同的 policyVersion',
  `capability_policy_content_sha256` CHAR(64) NOT NULL COMMENT '已发布能力策略规范化内容 SHA-256，用于读回核验',
  `snapshot_sha256` CHAR(64) NOT NULL COMMENT '规范化快照内容 SHA-256，用于审计读回',
  `generated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '生成时间，UTC 毫秒',
  `valid_until_ms` BIGINT UNSIGNED NOT NULL COMMENT '本次快照最晚有效时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_capability_snapshot_ref` (`snapshot_ref`),
  KEY `idx_capability_snapshot_user_time` (`user_internal_id`, `generated_at_ms`),
  KEY `idx_capability_snapshot_expiry` (`valid_until_ms`),
  KEY `idx_capability_snapshot_policy_release` (`capability_policy_release_internal_id`),
  CONSTRAINT `ck_capability_snapshot_subject` CHECK ((`subject_type` = 'guest' AND `user_internal_id` IS NULL AND `tier` = 'guest' AND `active_user_plant_limit` = 0) OR (`subject_type` = 'user' AND `user_internal_id` IS NOT NULL AND `tier` IN ('free', 'trial', 'member'))),
  CONSTRAINT `ck_capability_snapshot_time` CHECK (`valid_until_ms` > `generated_at_ms`),
  CONSTRAINT `ck_capability_snapshot_policy_kind` CHECK (`capability_policy_domain_code` = 'subscription' AND `capability_policy_code` = 'capability_catalog'),
  CONSTRAINT `fk_capability_snapshot_user` FOREIGN KEY (`user_internal_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_capability_snapshot_policy_release` FOREIGN KEY (`capability_policy_release_internal_id`, `capability_policy_domain_code`, `capability_policy_code`, `capability_policy_release_ref`, `capability_policy_release_version`, `capability_policy_content_sha256`) REFERENCES `business_policy_releases` (`id`, `domain_code`, `policy_code`, `release_ref`, `release_version`, `content_sha256`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 请求级内部能力裁决快照';

CREATE TABLE `trial_entitlements` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '试用权益内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `trial_ref` VARCHAR(64) NOT NULL COMMENT '高熵试用权益引用',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '统一用户内部主键',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：eligible、active、expired、denied',
  `starts_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '试用起算时间，必须等于统一用户创建时间，UTC 毫秒',
  `expires_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '绝对失效时间，固定为起算时间后 24 小时，UTC 毫秒',
  `policy_version` VARCHAR(64) NOT NULL COMMENT '试用策略版本',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_trial_ref` (`trial_ref`),
  UNIQUE KEY `uq_trial_user_once` (`user_internal_id`),
  KEY `idx_trial_expiry` (`status`, `expires_at_ms`),
  CONSTRAINT `ck_trial_status` CHECK (`status` IN ('eligible', 'active', 'expired', 'denied')),
  CONSTRAINT `ck_trial_window` CHECK (`expires_at_ms` = `starts_at_ms` + 86400000),
  CONSTRAINT `fk_trial_user_created_at` FOREIGN KEY (`user_internal_id`, `starts_at_ms`) REFERENCES `users` (`id`, `created_at_ms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 每用户一次的 24 小时试用';

CREATE TABLE `subscriptions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '会员订阅内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `subscription_ref` VARCHAR(64) NOT NULL COMMENT '高熵会员订阅引用',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '统一用户内部主键',
  `plan_code` VARCHAR(32) NOT NULL COMMENT '会员套餐代码',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：pending、active、cancelled、expired、failed',
  `current_period_internal_id` BIGINT UNSIGNED NULL COMMENT '当前生效周期内部主键',
  `version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '乐观并发版本',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_subscription_ref` (`subscription_ref`),
  KEY `idx_subscription_user_status` (`user_internal_id`, `status`),
  CONSTRAINT `ck_subscription_status` CHECK (`status` IN ('pending', 'active', 'cancelled', 'expired', 'failed')),
  CONSTRAINT `fk_subscription_user` FOREIGN KEY (`user_internal_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 会员订阅';

CREATE TABLE `subscription_periods` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '会员周期内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `period_ref` VARCHAR(64) NOT NULL COMMENT '高熵会员周期引用',
  `subscription_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '所属会员订阅',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '统一用户内部主键',
  `starts_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '周期开始时间，UTC 毫秒',
  `ends_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '周期结束时间，UTC 毫秒',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：pending、active、expired、failed',
  `payment_order_internal_id` BIGINT UNSIGNED NULL COMMENT '支付订单内部主键',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_subscription_period_ref` (`period_ref`),
  UNIQUE KEY `uq_subscription_period_range` (`subscription_internal_id`, `starts_at_ms`, `ends_at_ms`),
  KEY `idx_subscription_period_user` (`user_internal_id`, `status`, `ends_at_ms`),
  CONSTRAINT `ck_subscription_period_status` CHECK (`status` IN ('pending', 'active', 'expired', 'failed')),
  CONSTRAINT `ck_subscription_period_window` CHECK (`ends_at_ms` > `starts_at_ms`),
  CONSTRAINT `fk_period_subscription` FOREIGN KEY (`subscription_internal_id`) REFERENCES `subscriptions` (`id`),
  CONSTRAINT `fk_period_user` FOREIGN KEY (`user_internal_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 会员订阅周期';

CREATE TABLE `payment_orders` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '支付订单内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `payment_order_ref` VARCHAR(64) NOT NULL COMMENT '高熵支付订单公开引用',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '下单统一用户内部主键',
  `provider` VARCHAR(24) NOT NULL COMMENT '支付提供方：wechat_pay',
  `merchant_order_no` VARCHAR(64) NOT NULL COMMENT '商户订单号',
  `provider_order_no_ciphertext` TEXT NULL COMMENT '供应商订单号受控密文',
  `amount_fen` INT UNSIGNED NOT NULL COMMENT '订单金额，人民币分',
  `currency` CHAR(3) NOT NULL DEFAULT 'CNY' COMMENT '货币代码',
  `status` VARCHAR(32) NOT NULL COMMENT '订单状态',
  `idempotency_key` VARCHAR(128) NOT NULL COMMENT '下单幂等键',
  `request_hash` CHAR(64) NOT NULL COMMENT '规范化下单请求 SHA-256',
  `paid_at_ms` BIGINT UNSIGNED NULL COMMENT '支付完成时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_payment_order_ref` (`payment_order_ref`),
  UNIQUE KEY `uq_payment_merchant_order` (`merchant_order_no`),
  UNIQUE KEY `uq_payment_idempotency` (`user_internal_id`, `idempotency_key`),
  KEY `idx_payment_user_status` (`user_internal_id`, `status`, `created_at_ms`),
  CONSTRAINT `fk_payment_order_user` FOREIGN KEY (`user_internal_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 微信支付订单';

CREATE TABLE `payment_callback_inbox` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '支付回调收件内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `provider` VARCHAR(24) NOT NULL COMMENT '支付提供方',
  `provider_event_id` VARCHAR(128) NOT NULL COMMENT '供应商回调事件稳定标识',
  `payment_order_internal_id` BIGINT UNSIGNED NULL COMMENT '解析后的支付订单内部主键',
  `body_hash` CHAR(64) NOT NULL COMMENT '验签后规范化回调体 SHA-256',
  `signature_key_id` VARCHAR(128) NOT NULL COMMENT '验签平台证书或密钥标识',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：received、applied、rejected',
  `failure_code` VARCHAR(64) NULL COMMENT '脱敏失败代码',
  `received_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '接收时间，UTC 毫秒',
  `applied_at_ms` BIGINT UNSIGNED NULL COMMENT '事务生效时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_payment_callback_event` (`provider`, `provider_event_id`),
  KEY `idx_payment_callback_status` (`status`, `received_at_ms`),
  CONSTRAINT `fk_payment_callback_order` FOREIGN KEY (`payment_order_internal_id`) REFERENCES `payment_orders` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 支付回调幂等收件箱';

CREATE TABLE `care_point_ledger` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '积分账本内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `ledger_ref` VARCHAR(64) NOT NULL COMMENT '高熵积分账本引用',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '统一用户内部主键',
  `entry_type` VARCHAR(16) NOT NULL COMMENT '账本类型：grant、spend、reverse',
  `amount` INT NOT NULL COMMENT '整数积分变化，正负方向由类型约束',
  `source_type` VARCHAR(32) NOT NULL COMMENT '积分来源类型',
  `source_ref` VARCHAR(128) NOT NULL COMMENT '来源业务唯一引用',
  `business_unique_key` VARCHAR(191) NOT NULL COMMENT '跨重放业务唯一键',
  `original_ledger_internal_id` BIGINT UNSIGNED NULL COMMENT '冲正所引用的原账本记录',
  `policy_version` VARCHAR(64) NOT NULL COMMENT '积分策略版本',
  `occurred_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '业务发生时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_care_point_ledger_ref` (`ledger_ref`),
  UNIQUE KEY `uq_care_point_business` (`business_unique_key`),
  KEY `idx_care_point_user_time` (`user_internal_id`, `occurred_at_ms`),
  CONSTRAINT `ck_care_point_ledger_entry` CHECK ((`entry_type` = 'grant' AND `amount` > 0 AND `original_ledger_internal_id` IS NULL) OR (`entry_type` = 'spend' AND `amount` < 0 AND `original_ledger_internal_id` IS NULL) OR (`entry_type` = 'reverse' AND `amount` <> 0 AND `original_ledger_internal_id` IS NOT NULL)),
  CONSTRAINT `fk_care_point_user` FOREIGN KEY (`user_internal_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_care_point_original` FOREIGN KEY (`original_ledger_internal_id`) REFERENCES `care_point_ledger` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 不可变养护积分账本';

CREATE TABLE `care_point_accounts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '积分账户投影内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '统一用户内部主键',
  `available_points` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当前可用积分',
  `lifetime_net_earned` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '累计净获得积分，用于等级',
  `level_code` VARCHAR(16) NOT NULL DEFAULT 'L0' COMMENT '养护等级代码',
  `version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '乐观并发版本',
  `last_ledger_internal_id` BIGINT UNSIGNED NULL COMMENT '投影已处理的最后账本记录',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_care_point_account_user` (`user_internal_id`),
  CONSTRAINT `fk_care_point_account_user` FOREIGN KEY (`user_internal_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_care_point_account_ledger` FOREIGN KEY (`last_ledger_internal_id`) REFERENCES `care_point_ledger` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 养护积分账户投影';

CREATE TABLE `care_level_grants` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '等级奖励内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `grant_ref` VARCHAR(64) NOT NULL COMMENT '高熵等级奖励引用',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '统一用户内部主键',
  `level_code` VARCHAR(16) NOT NULL COMMENT '首次达到的养护等级',
  `qualifying_ledger_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '触发等级的积分账本记录',
  `ai_quota_grant_internal_id` BIGINT UNSIGNED NULL COMMENT '对应 AI 奖励额度批次',
  `granted_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '奖励时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_care_level_grant_ref` (`grant_ref`),
  UNIQUE KEY `uq_care_level_once` (`user_internal_id`, `level_code`),
  CONSTRAINT `fk_care_level_user` FOREIGN KEY (`user_internal_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_care_level_ledger` FOREIGN KEY (`qualifying_ledger_internal_id`) REFERENCES `care_point_ledger` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 每等级终身一次奖励';

CREATE TABLE `care_redemptions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '积分兑换内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `redemption_ref` VARCHAR(64) NOT NULL COMMENT '高熵兑换公开引用',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '统一用户内部主键',
  `catalog_item_code` VARCHAR(64) NOT NULL COMMENT '已发布兑换目录项目代码',
  `catalog_version` VARCHAR(64) NOT NULL COMMENT '兑换目录版本',
  `point_cost` INT UNSIGNED NOT NULL COMMENT '服务端策略计算的积分成本',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：requested、committed、rejected、reversed',
  `idempotency_key` VARCHAR(128) NOT NULL COMMENT '兑换幂等键',
  `request_hash` CHAR(64) NOT NULL COMMENT '规范化兑换请求 SHA-256',
  `point_ledger_internal_id` BIGINT UNSIGNED NULL COMMENT '兑换积分账本记录',
  `reversal_ledger_internal_id` BIGINT UNSIGNED NULL COMMENT '兑换冲正账本记录',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_redemption_ref` (`redemption_ref`),
  UNIQUE KEY `uq_redemption_idempotency` (`user_internal_id`, `idempotency_key`),
  KEY `idx_redemption_user_status` (`user_internal_id`, `status`, `created_at_ms`),
  CONSTRAINT `ck_redemption_status` CHECK (`status` IN ('requested', 'committed', 'rejected', 'reversed')),
  CONSTRAINT `ck_redemption_terminal_links` CHECK ((`status` = 'committed' AND `point_ledger_internal_id` IS NOT NULL AND `reversal_ledger_internal_id` IS NULL) OR (`status` = 'reversed' AND `point_ledger_internal_id` IS NOT NULL AND `reversal_ledger_internal_id` IS NOT NULL) OR (`status` IN ('requested', 'rejected') AND `point_ledger_internal_id` IS NULL AND `reversal_ledger_internal_id` IS NULL)),
  CONSTRAINT `fk_redemption_user` FOREIGN KEY (`user_internal_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_redemption_point_ledger` FOREIGN KEY (`point_ledger_internal_id`) REFERENCES `care_point_ledger` (`id`),
  CONSTRAINT `fk_redemption_reversal_ledger` FOREIGN KEY (`reversal_ledger_internal_id`) REFERENCES `care_point_ledger` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 积分兑换命令';

CREATE TABLE `ai_provider_tariff_snapshots` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'AI 供应商价目快照内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `tariff_ref` VARCHAR(64) NOT NULL COMMENT '高熵价目快照引用',
  `provider_code` VARCHAR(40) NOT NULL COMMENT '供应商代码，例如 bailian',
  `model_code` VARCHAR(80) NOT NULL COMMENT '供应商精确模型代码',
  `currency` CHAR(3) NOT NULL DEFAULT 'CNY' COMMENT '价目币种，当前固定 CNY',
  `input_micros_per_million_tokens` BIGINT UNSIGNED NOT NULL COMMENT '每百万输入 Token 成本，人民币微元',
  `output_micros_per_million_tokens` BIGINT UNSIGNED NOT NULL COMMENT '每百万输出 Token 成本，人民币微元',
  `cached_input_micros_per_million_tokens` BIGINT UNSIGNED NULL COMMENT '每百万缓存命中输入 Token 成本，人民币微元',
  `pricing_rules_json` JSON NOT NULL COMMENT '供应商公开价目中额外阶梯和多模态计价规则',
  `tariff_snapshot_sha256` CHAR(64) NOT NULL COMMENT '规范化价目内容 SHA-256',
  `source_evidence_ref` VARCHAR(255) NOT NULL COMMENT '脱敏权威价目证据引用',
  `effective_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '价目生效时间，UTC 毫秒',
  `expires_at_ms` BIGINT UNSIGNED NULL COMMENT '价目失效时间，UTC 毫秒；空表示供应商未声明',
  `captured_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '价目采集时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ai_tariff_ref` (`tariff_ref`),
  UNIQUE KEY `uq_ai_tariff_sha` (`tariff_snapshot_sha256`),
  KEY `idx_ai_tariff_lookup` (`provider_code`, `model_code`, `effective_at_ms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 AI 供应商不可变价目快照';

CREATE TABLE `ai_cost_policies` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'AI 成本策略内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `policy_ref` VARCHAR(64) NOT NULL COMMENT '高熵成本策略引用',
  `policy_version` VARCHAR(64) NOT NULL COMMENT '不可变成本策略版本',
  `tariff_snapshot_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '绑定的供应商价目快照内部主键',
  `safety_factor_basis_points` INT UNSIGNED NOT NULL COMMENT '成本安全系数，基点；12500 表示 1.25 倍',
  `rounding_mode` VARCHAR(24) NOT NULL COMMENT '额度换算舍入方式，当前为向上取整',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：draft、verified、active、retired',
  `release_sha256` CHAR(64) NOT NULL COMMENT '规范化成本策略发布 SHA-256',
  `effective_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '策略生效时间，UTC 毫秒',
  `expires_at_ms` BIGINT UNSIGNED NULL COMMENT '策略失效时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ai_cost_policy_ref` (`policy_ref`),
  UNIQUE KEY `uq_ai_cost_policy_version` (`policy_version`),
  UNIQUE KEY `uq_ai_cost_policy_sha` (`release_sha256`),
  KEY `idx_ai_cost_policy_status` (`status`, `effective_at_ms`),
  CONSTRAINT `ck_ai_cost_policy_factor` CHECK (`safety_factor_basis_points` >= 10000),
  CONSTRAINT `fk_ai_cost_policy_tariff` FOREIGN KEY (`tariff_snapshot_internal_id`) REFERENCES `ai_provider_tariff_snapshots` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 不可变 AI 成本换算策略';

CREATE TABLE `ai_cost_policy_actions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'AI 产品动作成本策略内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `cost_policy_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '所属 AI 成本策略内部主键',
  `product_action_code` VARCHAR(64) NOT NULL COMMENT '产品动作代码：小青文本、问诊文本、单图或多图视觉',
  `capability_scope` VARCHAR(40) NOT NULL COMMENT '允许消费的生成式能力范围',
  `max_input_tokens` INT UNSIGNED NOT NULL COMMENT '单次动作最大输入 Token',
  `max_output_tokens` INT UNSIGNED NOT NULL COMMENT '单次动作最大输出 Token',
  `max_image_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '单次动作最大图片数',
  `max_model_loops` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '单次动作最大模型循环数',
  `max_cost_micros` BIGINT UNSIGNED NOT NULL COMMENT '单次动作最大第三方成本，人民币微元',
  `estimated_amount` INT UNSIGNED NOT NULL COMMENT '按策略计算的最大预占 AI 额度',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ai_cost_policy_action` (`cost_policy_internal_id`, `product_action_code`),
  CONSTRAINT `ck_ai_cost_action_positive` CHECK (`max_cost_micros` > 0 AND `estimated_amount` > 0),
  CONSTRAINT `fk_ai_cost_action_policy` FOREIGN KEY (`cost_policy_internal_id`) REFERENCES `ai_cost_policies` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 AI 产品动作成本上限';

CREATE TABLE `ai_quota_grants` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'AI 额度批次内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `grant_ref` VARCHAR(64) NOT NULL COMMENT '高熵 AI 额度批次引用',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '统一用户内部主键',
  `source_type` VARCHAR(32) NOT NULL COMMENT '来源：TRIAL、MEMBER、CMS_IDENTITY、CMS_CONTENT、CARE_LEVEL、CARE_REDEMPTION',
  `source_ref` VARCHAR(128) NOT NULL COMMENT '来源业务唯一引用',
  `granted_amount` INT UNSIGNED NOT NULL COMMENT '发放总额度',
  `available_amount` INT UNSIGNED NOT NULL COMMENT '尚未预占的可用额度',
  `reserved_amount` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '进行中动作已预占额度',
  `consumed_amount` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '已完成结算额度',
  `capability_scope_json` JSON NOT NULL COMMENT '允许消费的三类生成式能力范围',
  `policy_version` VARCHAR(64) NOT NULL COMMENT '额度策略版本',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：active、partially_used、used、expired、reversed',
  `granted_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '发放时间，UTC 毫秒',
  `expires_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '绝对失效时间，UTC 毫秒；试用、会员、CMS、等级和未来兑换额度均须在发放时锁定',
  `version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '乐观并发版本',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ai_grant_ref` (`grant_ref`),
  UNIQUE KEY `uq_ai_grant_source` (`user_internal_id`, `source_type`, `source_ref`),
  KEY `idx_ai_grant_consume` (`user_internal_id`, `status`, `expires_at_ms`, `granted_at_ms`, `grant_ref`),
  CONSTRAINT `ck_ai_grant_positive` CHECK (`granted_amount` > 0),
  CONSTRAINT `ck_ai_grant_source_type` CHECK (`source_type` IN ('TRIAL', 'MEMBER', 'CMS_IDENTITY', 'CMS_CONTENT', 'CARE_LEVEL', 'CARE_REDEMPTION')),
  CONSTRAINT `ck_ai_grant_status` CHECK (`status` IN ('active', 'partially_used', 'used', 'expired', 'reversed')),
  CONSTRAINT `ck_ai_grant_conservation` CHECK (`granted_amount` = `available_amount` + `reserved_amount` + `consumed_amount`),
  CONSTRAINT `ck_ai_grant_expiry_after_grant` CHECK (`expires_at_ms` > `granted_at_ms`),
  CONSTRAINT `fk_ai_grant_user` FOREIGN KEY (`user_internal_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 分来源 AI 额度批次';

CREATE TABLE `ai_quota_accounts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'AI 额度账户投影内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '统一用户内部主键',
  `available_amount` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '所有有效批次可用额度合计',
  `reserved_amount` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '所有有效批次已预占额度合计',
  `consumed_amount` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '历史已结算额度累计',
  `version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '乐观并发版本',
  `last_ledger_internal_id` BIGINT UNSIGNED NULL COMMENT '投影已处理的最后额度账本记录',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ai_quota_account_user` (`user_internal_id`),
  CONSTRAINT `fk_ai_quota_account_user` FOREIGN KEY (`user_internal_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 AI 额度账户投影';

CREATE TABLE `ai_quota_reservations` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'AI 额度预占内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `reservation_ref` VARCHAR(64) NOT NULL COMMENT '高熵预占公开引用',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '统一用户内部主键',
  `product_action_id` VARCHAR(100) NOT NULL COMMENT '一次用户产品动作稳定标识',
  `cost_policy_version` VARCHAR(64) NOT NULL COMMENT '不可变成本策略版本',
  `capability` VARCHAR(40) NOT NULL COMMENT '受控生成式能力',
  `estimated_amount` INT UNSIGNED NOT NULL COMMENT '服务端计算的最大预占额度',
  `settled_amount` INT UNSIGNED NULL COMMENT '最终结算额度',
  `actual_cost_micros` BIGINT UNSIGNED NULL COMMENT '供应商用量证据折算的真实成本，人民币微元',
  `usage_evidence_ref` VARCHAR(128) NULL COMMENT '脱敏供应商用量证据引用',
  `platform_absorbed_cost_micros` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '超过预占且由平台承担的成本，人民币微元',
  `idempotency_key` VARCHAR(128) NOT NULL COMMENT '规范化幂等键',
  `request_hash` CHAR(64) NOT NULL COMMENT '规范化内部命令 SHA-256',
  `status` VARCHAR(32) NOT NULL COMMENT '状态：reserved、settled、released、pending_reconciliation',
  `expires_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '预占租约失效时间，UTC 毫秒',
  `version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '乐观并发版本',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ai_reservation_ref` (`reservation_ref`),
  UNIQUE KEY `uq_reservation_idempotency` (`user_internal_id`, `product_action_id`, `idempotency_key`),
  KEY `idx_ai_reservation_reconcile` (`status`, `expires_at_ms`),
  CONSTRAINT `ck_ai_reservation_positive` CHECK (`estimated_amount` > 0),
  CONSTRAINT `ck_ai_reservation_status` CHECK (`status` IN ('reserved', 'settled', 'released', 'pending_reconciliation')),
  CONSTRAINT `ck_ai_reservation_settlement_limit` CHECK (`settled_amount` IS NULL OR `settled_amount` <= `estimated_amount`),
  CONSTRAINT `ck_ai_reservation_terminal` CHECK ((`status` IN ('reserved', 'pending_reconciliation') AND `settled_amount` IS NULL) OR (`status` = 'settled' AND `settled_amount` IS NOT NULL) OR (`status` = 'released' AND `settled_amount` = 0)),
  CONSTRAINT `fk_ai_reservation_user` FOREIGN KEY (`user_internal_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 AI 产品动作额度预占';

CREATE TABLE `ai_quota_reservation_allocations` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '预占额度分摊内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `reservation_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '所属 AI 额度预占',
  `grant_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '被锁定的 AI 额度批次',
  `reserved_amount` INT UNSIGNED NOT NULL COMMENT '从该批次预占的额度',
  `settled_amount` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '从该批次结算的额度',
  `released_amount` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '退回该批次的额度',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_allocation_pair` (`reservation_internal_id`, `grant_internal_id`),
  KEY `idx_allocation_grant` (`grant_internal_id`),
  CONSTRAINT `ck_ai_allocation_positive` CHECK (`reserved_amount` > 0),
  CONSTRAINT `ck_ai_allocation_conservation` CHECK (`reserved_amount` = `settled_amount` + `released_amount`),
  CONSTRAINT `fk_allocation_reservation` FOREIGN KEY (`reservation_internal_id`) REFERENCES `ai_quota_reservations` (`id`),
  CONSTRAINT `fk_allocation_grant` FOREIGN KEY (`grant_internal_id`) REFERENCES `ai_quota_grants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 AI 预占跨额度批次分摊';

CREATE TABLE `ai_quota_ledger` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'AI 额度账本内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `ledger_ref` VARCHAR(64) NOT NULL COMMENT '高熵额度账本引用',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '统一用户内部主键',
  `grant_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '关联额度批次',
  `reservation_internal_id` BIGINT UNSIGNED NULL COMMENT '关联产品动作预占',
  `entry_type` VARCHAR(24) NOT NULL COMMENT '类型：grant、reserve、settle、release、expire、reverse',
  `amount` INT UNSIGNED NOT NULL COMMENT '本次状态转移额度',
  `operation_unique_key` VARCHAR(191) NOT NULL COMMENT '操作幂等唯一键',
  `original_ledger_internal_id` BIGINT UNSIGNED NULL COMMENT '冲正所引用原账本记录',
  `occurred_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '业务发生时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ai_ledger_ref` (`ledger_ref`),
  UNIQUE KEY `uq_ai_ledger_operation` (`operation_unique_key`),
  KEY `idx_ai_ledger_user_time` (`user_internal_id`, `occurred_at_ms`),
  CONSTRAINT `ck_ai_ledger_entry` CHECK (`entry_type` IN ('grant', 'reserve', 'settle', 'release', 'expire', 'reverse') AND `amount` > 0),
  CONSTRAINT `ck_ai_ledger_original` CHECK ((`entry_type` = 'reverse' AND `original_ledger_internal_id` IS NOT NULL) OR (`entry_type` <> 'reverse' AND `original_ledger_internal_id` IS NULL)),
  CONSTRAINT `fk_ai_ledger_user` FOREIGN KEY (`user_internal_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_ai_ledger_grant` FOREIGN KEY (`grant_internal_id`) REFERENCES `ai_quota_grants` (`id`),
  CONSTRAINT `fk_ai_ledger_reservation` FOREIGN KEY (`reservation_internal_id`) REFERENCES `ai_quota_reservations` (`id`),
  CONSTRAINT `fk_ai_ledger_original` FOREIGN KEY (`original_ledger_internal_id`) REFERENCES `ai_quota_ledger` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 不可变 AI 额度账本';

CREATE TABLE `subscription_reward_inbox` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '奖励事件收件内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `event_id` VARCHAR(64) NOT NULL COMMENT '全局高熵奖励事件标识',
  `event_type` VARCHAR(80) NOT NULL COMMENT '版本化奖励事件类型',
  `producer_domain` VARCHAR(32) NOT NULL COMMENT '事件生产业务域',
  `user_internal_id` BIGINT UNSIGNED NOT NULL COMMENT '统一用户内部主键',
  `user_plant_ref` VARCHAR(64) NULL COMMENT '可选用户植物公开引用',
  `business_unique_key` VARCHAR(191) NOT NULL COMMENT '奖励业务唯一键',
  `payload_hash` CHAR(64) NOT NULL COMMENT '规范化事件载荷 SHA-256',
  `payload_json` JSON NOT NULL COMMENT '奖励资格所需最小事实载荷',
  `policy_version` VARCHAR(64) NOT NULL COMMENT '生产事件携带的策略版本',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：received、applied、rejected',
  `result_ref` VARCHAR(64) NULL COMMENT '入账或拒绝结果引用',
  `rejection_code` VARCHAR(64) NULL COMMENT '脱敏拒绝代码',
  `received_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '接收时间，UTC 毫秒',
  `applied_at_ms` BIGINT UNSIGNED NULL COMMENT '事务生效时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_reward_event` (`event_id`),
  UNIQUE KEY `uq_reward_business` (`business_unique_key`),
  KEY `idx_reward_inbox_status` (`status`, `received_at_ms`),
  CONSTRAINT `ck_reward_inbox_status` CHECK ((`status` = 'received' AND `applied_at_ms` IS NULL AND `result_ref` IS NULL AND `rejection_code` IS NULL) OR (`status` = 'applied' AND `applied_at_ms` IS NOT NULL AND `result_ref` IS NOT NULL AND `rejection_code` IS NULL) OR (`status` = 'rejected' AND `applied_at_ms` IS NULL AND `result_ref` IS NULL AND `rejection_code` IS NOT NULL)),
  CONSTRAINT `fk_reward_inbox_user` FOREIGN KEY (`user_internal_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 奖励事件幂等收件箱';
