-- 青花植后端 v2 / 各写域可靠事件与安全审计空库 DDL。
-- 每个业务域拥有独立 outbox，禁止跨域直接写对方表。

CREATE TABLE `identity_outbox` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'identity 事件内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `event_id` VARCHAR(64) NOT NULL COMMENT '全局高熵事件标识',
  `aggregate_ref` VARCHAR(64) NOT NULL COMMENT '聚合公开引用',
  `aggregate_version` INT UNSIGNED NOT NULL COMMENT '聚合版本',
  `event_type` VARCHAR(96) NOT NULL COMMENT '版本化事件类型',
  `schema_version` VARCHAR(32) NOT NULL COMMENT '事件结构版本',
  `payload_json` JSON NOT NULL COMMENT '脱敏事件载荷',
  `payload_hash` CHAR(64) NOT NULL COMMENT '规范化载荷 SHA-256',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：pending、dispatching、delivered、dead_letter',
  `lease_owner` VARCHAR(64) NULL COMMENT '当前派发租约持有者',
  `lease_until_ms` BIGINT UNSIGNED NULL COMMENT '租约失效时间，UTC 毫秒',
  `attempt_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '派发尝试次数',
  `next_attempt_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '下次派发时间，UTC 毫秒',
  `occurred_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '业务发生时间，UTC 毫秒',
  `delivered_at_ms` BIGINT UNSIGNED NULL COMMENT '成功投递时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_identity_outbox_event` (`event_id`),
  UNIQUE KEY `uq_identity_outbox_version` (`aggregate_ref`, `aggregate_version`, `event_type`),
  KEY `idx_identity_outbox_dispatch` (`status`, `next_attempt_at_ms`, `lease_until_ms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 identity 可靠事件发件箱';

CREATE TABLE `plant_knowledge_outbox` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'plant-knowledge 事件内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `event_id` VARCHAR(64) NOT NULL COMMENT '全局高熵事件标识',
  `event_version` TINYINT UNSIGNED NOT NULL COMMENT '奖励事件合同版本，当前固定为 1',
  `producer_domain` VARCHAR(32) NOT NULL COMMENT '事件生产域，当前表固定为 plant-knowledge',
  `user_ref` VARCHAR(64) NOT NULL COMMENT '奖励归属的统一用户公开引用',
  `user_plant_ref` VARCHAR(64) NULL COMMENT '可选用户植物公开引用；知识贡献允许为空',
  `aggregate_ref` VARCHAR(64) NOT NULL COMMENT '聚合公开引用',
  `aggregate_version` INT UNSIGNED NOT NULL COMMENT '聚合版本',
  `occurrence_ref` VARCHAR(100) NOT NULL COMMENT '业务发生实例引用；同一事实重试保持不变',
  `event_type` VARCHAR(96) NOT NULL COMMENT '版本化事件类型',
  `producer_policy_version` VARCHAR(100) NOT NULL COMMENT '生产域形成业务事实时使用的策略版本',
  `payload_json` JSON NOT NULL COMMENT '脱敏事件载荷',
  `payload_hash` CHAR(64) NOT NULL COMMENT '规范化载荷 SHA-256',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：pending、dispatching、delivered、dead_letter',
  `lease_owner` VARCHAR(64) NULL COMMENT '当前派发租约持有者',
  `lease_until_ms` BIGINT UNSIGNED NULL COMMENT '租约失效时间，UTC 毫秒',
  `attempt_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '派发尝试次数',
  `next_attempt_at_ms` BIGINT UNSIGNED NULL COMMENT '下次派发时间，UTC 毫秒；未冻结自动派发策略时为空',
  `occurred_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '业务发生时间，UTC 毫秒',
  `delivered_at_ms` BIGINT UNSIGNED NULL COMMENT '成功投递时间，UTC 毫秒',
  `terminal_reason_code` VARCHAR(64) NULL COMMENT '脱敏终止原因；仅 dead_letter 状态允许填写',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_knowledge_outbox_event` (`producer_domain`, `event_id`),
  KEY `idx_knowledge_outbox_occurrence` (`occurrence_ref`),
  KEY `idx_knowledge_outbox_dispatch` (`status`, `next_attempt_at_ms`, `lease_until_ms`),
  CONSTRAINT `ck_knowledge_outbox_event_version` CHECK (`event_version` = 1),
  CONSTRAINT `ck_knowledge_outbox_domain` CHECK (`producer_domain` = 'plant-knowledge'),
  CONSTRAINT `ck_knowledge_outbox_event_type` CHECK (`event_type` = 'knowledge.contribution_released.v1'),
  CONSTRAINT `ck_knowledge_outbox_status` CHECK (`status` IN ('pending', 'dispatching', 'delivered', 'dead_letter')),
  CONSTRAINT `ck_knowledge_outbox_state_fields` CHECK ((`status` = 'pending' AND `lease_owner` IS NULL AND `lease_until_ms` IS NULL AND `delivered_at_ms` IS NULL AND `terminal_reason_code` IS NULL) OR (`status` = 'dispatching' AND `lease_owner` IS NOT NULL AND `lease_until_ms` IS NOT NULL AND `delivered_at_ms` IS NULL AND `terminal_reason_code` IS NULL) OR (`status` = 'delivered' AND `delivered_at_ms` IS NOT NULL AND `lease_owner` IS NULL AND `lease_until_ms` IS NULL AND `terminal_reason_code` IS NULL) OR (`status` = 'dead_letter' AND `lease_owner` IS NULL AND `lease_until_ms` IS NULL AND `delivered_at_ms` IS NULL AND `terminal_reason_code` IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 plant-knowledge 可靠事件发件箱';

CREATE TABLE `user_plant_outbox` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'user-plant 事件内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `event_id` VARCHAR(64) NOT NULL COMMENT '全局高熵事件标识',
  `event_version` TINYINT UNSIGNED NOT NULL COMMENT '奖励事件合同版本，当前固定为 1',
  `producer_domain` VARCHAR(32) NOT NULL COMMENT '事件生产域，当前表固定为 user-plant',
  `user_ref` VARCHAR(64) NOT NULL COMMENT '奖励归属的统一用户公开引用',
  `user_plant_ref` VARCHAR(64) NULL COMMENT '奖励事实所属用户植物公开引用',
  `aggregate_ref` VARCHAR(64) NOT NULL COMMENT '聚合公开引用',
  `aggregate_version` INT UNSIGNED NOT NULL COMMENT '聚合版本',
  `occurrence_ref` VARCHAR(100) NOT NULL COMMENT '业务发生实例引用；同一事实重试保持不变',
  `event_type` VARCHAR(96) NOT NULL COMMENT '版本化事件类型',
  `producer_policy_version` VARCHAR(100) NOT NULL COMMENT '生产域形成业务事实时使用的策略版本',
  `payload_json` JSON NOT NULL COMMENT '脱敏事件载荷',
  `payload_hash` CHAR(64) NOT NULL COMMENT '规范化载荷 SHA-256',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：pending、dispatching、delivered、dead_letter',
  `lease_owner` VARCHAR(64) NULL COMMENT '当前派发租约持有者',
  `lease_until_ms` BIGINT UNSIGNED NULL COMMENT '租约失效时间，UTC 毫秒',
  `attempt_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '派发尝试次数',
  `next_attempt_at_ms` BIGINT UNSIGNED NULL COMMENT '下次派发时间，UTC 毫秒；未冻结自动派发策略时为空',
  `occurred_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '业务发生时间，UTC 毫秒',
  `delivered_at_ms` BIGINT UNSIGNED NULL COMMENT '成功投递时间，UTC 毫秒',
  `terminal_reason_code` VARCHAR(64) NULL COMMENT '脱敏终止原因；仅 dead_letter 状态允许填写',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_plant_outbox_event` (`producer_domain`, `event_id`),
  KEY `idx_user_plant_outbox_occurrence` (`occurrence_ref`),
  KEY `idx_user_plant_outbox_dispatch` (`status`, `next_attempt_at_ms`, `lease_until_ms`),
  CONSTRAINT `ck_user_plant_outbox_event_version` CHECK (`event_version` = 1),
  CONSTRAINT `ck_user_plant_outbox_domain` CHECK (`producer_domain` = 'user-plant'),
  CONSTRAINT `ck_user_plant_outbox_event_type` CHECK (`event_type` = 'user_plant.profile_completed.v1'),
  CONSTRAINT `ck_user_plant_outbox_user_plant` CHECK (`user_plant_ref` IS NOT NULL),
  CONSTRAINT `ck_user_plant_outbox_status` CHECK (`status` IN ('pending', 'dispatching', 'delivered', 'dead_letter')),
  CONSTRAINT `ck_user_plant_outbox_state_fields` CHECK ((`status` = 'pending' AND `lease_owner` IS NULL AND `lease_until_ms` IS NULL AND `delivered_at_ms` IS NULL AND `terminal_reason_code` IS NULL) OR (`status` = 'dispatching' AND `lease_owner` IS NOT NULL AND `lease_until_ms` IS NOT NULL AND `delivered_at_ms` IS NULL AND `terminal_reason_code` IS NULL) OR (`status` = 'delivered' AND `delivered_at_ms` IS NOT NULL AND `lease_owner` IS NULL AND `lease_until_ms` IS NULL AND `terminal_reason_code` IS NULL) OR (`status` = 'dead_letter' AND `lease_owner` IS NULL AND `lease_until_ms` IS NULL AND `delivered_at_ms` IS NULL AND `terminal_reason_code` IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 user-plant 可靠事件发件箱';

CREATE TABLE `care_outbox` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'care 事件内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `event_id` VARCHAR(64) NOT NULL COMMENT '全局高熵事件标识',
  `event_version` TINYINT UNSIGNED NOT NULL COMMENT '奖励事件合同版本，当前固定为 1',
  `producer_domain` VARCHAR(32) NOT NULL COMMENT '事件生产域，当前表固定为 care',
  `user_ref` VARCHAR(64) NOT NULL COMMENT '奖励归属的统一用户公开引用',
  `user_plant_ref` VARCHAR(64) NULL COMMENT '奖励事实所属用户植物公开引用',
  `aggregate_ref` VARCHAR(64) NOT NULL COMMENT '聚合公开引用',
  `aggregate_version` INT UNSIGNED NOT NULL COMMENT '聚合版本',
  `occurrence_ref` VARCHAR(100) NOT NULL COMMENT '业务发生实例引用；同一事实重试保持不变',
  `event_type` VARCHAR(96) NOT NULL COMMENT '版本化事件类型',
  `producer_policy_version` VARCHAR(100) NOT NULL COMMENT '生产域形成业务事实时使用的策略版本',
  `payload_json` JSON NOT NULL COMMENT '脱敏事件载荷',
  `payload_hash` CHAR(64) NOT NULL COMMENT '规范化载荷 SHA-256',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：pending、dispatching、delivered、dead_letter',
  `lease_owner` VARCHAR(64) NULL COMMENT '当前派发租约持有者',
  `lease_until_ms` BIGINT UNSIGNED NULL COMMENT '租约失效时间，UTC 毫秒',
  `attempt_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '派发尝试次数',
  `next_attempt_at_ms` BIGINT UNSIGNED NULL COMMENT '下次派发时间，UTC 毫秒；未冻结自动派发策略时为空',
  `occurred_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '业务发生时间，UTC 毫秒',
  `delivered_at_ms` BIGINT UNSIGNED NULL COMMENT '成功投递时间，UTC 毫秒',
  `terminal_reason_code` VARCHAR(64) NULL COMMENT '脱敏终止原因；仅 dead_letter 状态允许填写',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_care_outbox_event` (`producer_domain`, `event_id`),
  KEY `idx_care_outbox_occurrence` (`occurrence_ref`),
  KEY `idx_care_outbox_dispatch` (`status`, `next_attempt_at_ms`, `lease_until_ms`),
  CONSTRAINT `ck_care_outbox_event_version` CHECK (`event_version` = 1),
  CONSTRAINT `ck_care_outbox_domain` CHECK (`producer_domain` = 'care'),
  CONSTRAINT `ck_care_outbox_event_type` CHECK (`event_type` IN ('care.soil_check_completed.v1', 'care.fertilizing_check_completed.v1')),
  CONSTRAINT `ck_care_outbox_user_plant` CHECK (`user_plant_ref` IS NOT NULL),
  CONSTRAINT `ck_care_outbox_status` CHECK (`status` IN ('pending', 'dispatching', 'delivered', 'dead_letter')),
  CONSTRAINT `ck_care_outbox_state_fields` CHECK ((`status` = 'pending' AND `lease_owner` IS NULL AND `lease_until_ms` IS NULL AND `delivered_at_ms` IS NULL AND `terminal_reason_code` IS NULL) OR (`status` = 'dispatching' AND `lease_owner` IS NOT NULL AND `lease_until_ms` IS NOT NULL AND `delivered_at_ms` IS NULL AND `terminal_reason_code` IS NULL) OR (`status` = 'delivered' AND `delivered_at_ms` IS NOT NULL AND `lease_owner` IS NULL AND `lease_until_ms` IS NULL AND `terminal_reason_code` IS NULL) OR (`status` = 'dead_letter' AND `lease_owner` IS NULL AND `lease_until_ms` IS NULL AND `delivered_at_ms` IS NULL AND `terminal_reason_code` IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 care 可靠事件发件箱';

CREATE TABLE `diagnosis_outbox` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'diagnosis 事件内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `event_id` VARCHAR(64) NOT NULL COMMENT '全局高熵事件标识',
  `event_version` TINYINT UNSIGNED NOT NULL COMMENT '奖励事件合同版本，当前固定为 1',
  `producer_domain` VARCHAR(32) NOT NULL COMMENT '事件生产域，当前表固定为 diagnosis',
  `user_ref` VARCHAR(64) NOT NULL COMMENT '奖励归属的统一用户公开引用',
  `user_plant_ref` VARCHAR(64) NULL COMMENT '奖励事实所属用户植物公开引用',
  `aggregate_ref` VARCHAR(64) NOT NULL COMMENT '聚合公开引用',
  `aggregate_version` INT UNSIGNED NOT NULL COMMENT '聚合版本',
  `occurrence_ref` VARCHAR(100) NOT NULL COMMENT '业务发生实例引用；同一事实重试保持不变',
  `event_type` VARCHAR(96) NOT NULL COMMENT '版本化事件类型',
  `producer_policy_version` VARCHAR(100) NOT NULL COMMENT '生产域形成业务事实时使用的策略版本',
  `payload_json` JSON NOT NULL COMMENT '脱敏事件载荷',
  `payload_hash` CHAR(64) NOT NULL COMMENT '规范化载荷 SHA-256',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：pending、dispatching、delivered、dead_letter',
  `lease_owner` VARCHAR(64) NULL COMMENT '当前派发租约持有者',
  `lease_until_ms` BIGINT UNSIGNED NULL COMMENT '租约失效时间，UTC 毫秒',
  `attempt_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '派发尝试次数',
  `next_attempt_at_ms` BIGINT UNSIGNED NULL COMMENT '下次派发时间，UTC 毫秒；未冻结自动派发策略时为空',
  `occurred_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '业务发生时间，UTC 毫秒',
  `delivered_at_ms` BIGINT UNSIGNED NULL COMMENT '成功投递时间，UTC 毫秒',
  `terminal_reason_code` VARCHAR(64) NULL COMMENT '脱敏终止原因；仅 dead_letter 状态允许填写',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_diagnosis_outbox_event` (`producer_domain`, `event_id`),
  KEY `idx_diagnosis_outbox_occurrence` (`occurrence_ref`),
  KEY `idx_diagnosis_outbox_dispatch` (`status`, `next_attempt_at_ms`, `lease_until_ms`),
  CONSTRAINT `ck_diagnosis_outbox_event_version` CHECK (`event_version` = 1),
  CONSTRAINT `ck_diagnosis_outbox_domain` CHECK (`producer_domain` = 'diagnosis'),
  CONSTRAINT `ck_diagnosis_outbox_event_type` CHECK (`event_type` = 'diagnosis.fixed_package_completed.v1'),
  CONSTRAINT `ck_diagnosis_outbox_user_plant` CHECK (`user_plant_ref` IS NOT NULL),
  CONSTRAINT `ck_diagnosis_outbox_status` CHECK (`status` IN ('pending', 'dispatching', 'delivered', 'dead_letter')),
  CONSTRAINT `ck_diagnosis_outbox_state_fields` CHECK ((`status` = 'pending' AND `lease_owner` IS NULL AND `lease_until_ms` IS NULL AND `delivered_at_ms` IS NULL AND `terminal_reason_code` IS NULL) OR (`status` = 'dispatching' AND `lease_owner` IS NOT NULL AND `lease_until_ms` IS NOT NULL AND `delivered_at_ms` IS NULL AND `terminal_reason_code` IS NULL) OR (`status` = 'delivered' AND `delivered_at_ms` IS NOT NULL AND `lease_owner` IS NULL AND `lease_until_ms` IS NULL AND `terminal_reason_code` IS NULL) OR (`status` = 'dead_letter' AND `lease_owner` IS NULL AND `lease_until_ms` IS NULL AND `delivered_at_ms` IS NULL AND `terminal_reason_code` IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 diagnosis 可靠事件发件箱';

CREATE TABLE `subscription_outbox` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'subscription 事件内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `event_id` VARCHAR(64) NOT NULL COMMENT '全局高熵事件标识',
  `aggregate_ref` VARCHAR(64) NOT NULL COMMENT '聚合公开引用',
  `aggregate_version` INT UNSIGNED NOT NULL COMMENT '聚合版本',
  `event_type` VARCHAR(96) NOT NULL COMMENT '版本化事件类型',
  `schema_version` VARCHAR(32) NOT NULL COMMENT '事件结构版本',
  `payload_json` JSON NOT NULL COMMENT '脱敏事件载荷',
  `payload_hash` CHAR(64) NOT NULL COMMENT '规范化载荷 SHA-256',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：pending、dispatching、delivered、dead_letter',
  `lease_owner` VARCHAR(64) NULL COMMENT '当前派发租约持有者',
  `lease_until_ms` BIGINT UNSIGNED NULL COMMENT '租约失效时间，UTC 毫秒',
  `attempt_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '派发尝试次数',
  `next_attempt_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '下次派发时间，UTC 毫秒',
  `occurred_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '业务发生时间，UTC 毫秒',
  `delivered_at_ms` BIGINT UNSIGNED NULL COMMENT '成功投递时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_subscription_outbox_event` (`event_id`),
  UNIQUE KEY `uq_subscription_outbox_version` (`aggregate_ref`, `aggregate_version`, `event_type`),
  KEY `idx_subscription_outbox_dispatch` (`status`, `next_attempt_at_ms`, `lease_until_ms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 subscription 可靠事件发件箱';

CREATE TABLE `security_audit_records` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '安全审计记录内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `audit_ref` VARCHAR(64) NOT NULL COMMENT '高熵审计记录引用',
  `principal_type` VARCHAR(16) NOT NULL COMMENT '主体类型：guest、user、service',
  `principal_safe_ref` VARCHAR(64) NOT NULL COMMENT '脱敏主体引用，不含平台标识',
  `action` VARCHAR(96) NOT NULL COMMENT '受控动作代码',
  `object_type` VARCHAR(64) NOT NULL COMMENT '对象类型',
  `object_public_ref` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '对象公开引用，无对象时为空',
  `result` VARCHAR(24) NOT NULL COMMENT '结果：allowed、denied、failed',
  `reason_code` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '脱敏原因代码',
  `occurred_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '发生时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_security_audit_ref` (`audit_ref`),
  KEY `idx_security_audit_subject` (`principal_type`, `principal_safe_ref`, `occurred_at_ms`),
  KEY `idx_security_audit_object` (`object_type`, `object_public_ref`, `occurred_at_ms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 脱敏安全审计记录';
