-- 青花植后端 v2 / 各写域可靠事件与安全审计空库 DDL。
-- 每个业务域拥有独立 outbox，禁止跨域直接写对方表。

CREATE TABLE `identity_outbox` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'identity 事件内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `event_id` VARCHAR(64) NOT NULL COMMENT '全局高熵事件标识',
  `aggregate_ref` VARCHAR(64) NOT NULL COMMENT '聚合公开引用',
  `aggregate_version` INT UNSIGNED NOT NULL COMMENT '聚合版本',
  `event_type` VARCHAR(96) NOT NULL COMMENT '版本化事件类型',
  `schema_version` VARCHAR(32) NOT NULL COMMENT '事件结构版本',
  `payload_json` JSON NOT NULL COMMENT '脱敏事件载荷',
  `payload_hash` CHAR(64) NOT NULL COMMENT '规范化载荷 SHA-256',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：pending、dispatching、delivered、dead_letter',
  `lease_owner` VARCHAR(64) NULL COMMENT '当前派发租约持有者',
  `lease_until_ms` BIGINT UNSIGNED NULL COMMENT '租约失效时间，UTC 毫秒',
  `attempt_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '派发尝试次数',
  `next_attempt_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '下次派发时间，UTC 毫秒',
  `occurred_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '业务发生时间，UTC 毫秒',
  `delivered_at_ms` BIGINT UNSIGNED NULL COMMENT '成功投递时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_identity_outbox_event` (`event_id`),
  UNIQUE KEY `uq_identity_outbox_version` (`aggregate_ref`, `aggregate_version`, `event_type`),
  KEY `idx_identity_outbox_dispatch` (`status`, `next_attempt_at_ms`, `lease_until_ms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 identity 可靠事件发件箱';

CREATE TABLE `plant_knowledge_outbox` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'plant-knowledge 事件内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `event_id` VARCHAR(64) NOT NULL COMMENT '全局高熵事件标识',
  `aggregate_ref` VARCHAR(64) NOT NULL COMMENT '聚合公开引用',
  `aggregate_version` INT UNSIGNED NOT NULL COMMENT '聚合版本',
  `event_type` VARCHAR(96) NOT NULL COMMENT '版本化事件类型',
  `schema_version` VARCHAR(32) NOT NULL COMMENT '事件结构版本',
  `payload_json` JSON NOT NULL COMMENT '脱敏事件载荷',
  `payload_hash` CHAR(64) NOT NULL COMMENT '规范化载荷 SHA-256',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：pending、dispatching、delivered、dead_letter',
  `lease_owner` VARCHAR(64) NULL COMMENT '当前派发租约持有者',
  `lease_until_ms` BIGINT UNSIGNED NULL COMMENT '租约失效时间，UTC 毫秒',
  `attempt_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '派发尝试次数',
  `next_attempt_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '下次派发时间，UTC 毫秒',
  `occurred_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '业务发生时间，UTC 毫秒',
  `delivered_at_ms` BIGINT UNSIGNED NULL COMMENT '成功投递时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_knowledge_outbox_event` (`event_id`),
  UNIQUE KEY `uq_knowledge_outbox_version` (`aggregate_ref`, `aggregate_version`, `event_type`),
  KEY `idx_knowledge_outbox_dispatch` (`status`, `next_attempt_at_ms`, `lease_until_ms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 plant-knowledge 可靠事件发件箱';

CREATE TABLE `user_plant_outbox` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'user-plant 事件内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `event_id` VARCHAR(64) NOT NULL COMMENT '全局高熵事件标识',
  `aggregate_ref` VARCHAR(64) NOT NULL COMMENT '聚合公开引用',
  `aggregate_version` INT UNSIGNED NOT NULL COMMENT '聚合版本',
  `event_type` VARCHAR(96) NOT NULL COMMENT '版本化事件类型',
  `schema_version` VARCHAR(32) NOT NULL COMMENT '事件结构版本',
  `payload_json` JSON NOT NULL COMMENT '脱敏事件载荷',
  `payload_hash` CHAR(64) NOT NULL COMMENT '规范化载荷 SHA-256',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：pending、dispatching、delivered、dead_letter',
  `lease_owner` VARCHAR(64) NULL COMMENT '当前派发租约持有者',
  `lease_until_ms` BIGINT UNSIGNED NULL COMMENT '租约失效时间，UTC 毫秒',
  `attempt_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '派发尝试次数',
  `next_attempt_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '下次派发时间，UTC 毫秒',
  `occurred_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '业务发生时间，UTC 毫秒',
  `delivered_at_ms` BIGINT UNSIGNED NULL COMMENT '成功投递时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_plant_outbox_event` (`event_id`),
  UNIQUE KEY `uq_user_plant_outbox_version` (`aggregate_ref`, `aggregate_version`, `event_type`),
  KEY `idx_user_plant_outbox_dispatch` (`status`, `next_attempt_at_ms`, `lease_until_ms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 user-plant 可靠事件发件箱';

CREATE TABLE `care_outbox` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'care 事件内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `event_id` VARCHAR(64) NOT NULL COMMENT '全局高熵事件标识',
  `aggregate_ref` VARCHAR(64) NOT NULL COMMENT '聚合公开引用',
  `aggregate_version` INT UNSIGNED NOT NULL COMMENT '聚合版本',
  `event_type` VARCHAR(96) NOT NULL COMMENT '版本化事件类型',
  `schema_version` VARCHAR(32) NOT NULL COMMENT '事件结构版本',
  `payload_json` JSON NOT NULL COMMENT '脱敏事件载荷',
  `payload_hash` CHAR(64) NOT NULL COMMENT '规范化载荷 SHA-256',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：pending、dispatching、delivered、dead_letter',
  `lease_owner` VARCHAR(64) NULL COMMENT '当前派发租约持有者',
  `lease_until_ms` BIGINT UNSIGNED NULL COMMENT '租约失效时间，UTC 毫秒',
  `attempt_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '派发尝试次数',
  `next_attempt_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '下次派发时间，UTC 毫秒',
  `occurred_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '业务发生时间，UTC 毫秒',
  `delivered_at_ms` BIGINT UNSIGNED NULL COMMENT '成功投递时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_care_outbox_event` (`event_id`),
  UNIQUE KEY `uq_care_outbox_version` (`aggregate_ref`, `aggregate_version`, `event_type`),
  KEY `idx_care_outbox_dispatch` (`status`, `next_attempt_at_ms`, `lease_until_ms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 care 可靠事件发件箱';

CREATE TABLE `diagnosis_outbox` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'diagnosis 事件内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `event_id` VARCHAR(64) NOT NULL COMMENT '全局高熵事件标识',
  `aggregate_ref` VARCHAR(64) NOT NULL COMMENT '聚合公开引用',
  `aggregate_version` INT UNSIGNED NOT NULL COMMENT '聚合版本',
  `event_type` VARCHAR(96) NOT NULL COMMENT '版本化事件类型',
  `schema_version` VARCHAR(32) NOT NULL COMMENT '事件结构版本',
  `payload_json` JSON NOT NULL COMMENT '脱敏事件载荷',
  `payload_hash` CHAR(64) NOT NULL COMMENT '规范化载荷 SHA-256',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：pending、dispatching、delivered、dead_letter',
  `lease_owner` VARCHAR(64) NULL COMMENT '当前派发租约持有者',
  `lease_until_ms` BIGINT UNSIGNED NULL COMMENT '租约失效时间，UTC 毫秒',
  `attempt_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '派发尝试次数',
  `next_attempt_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '下次派发时间，UTC 毫秒',
  `occurred_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '业务发生时间，UTC 毫秒',
  `delivered_at_ms` BIGINT UNSIGNED NULL COMMENT '成功投递时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_diagnosis_outbox_event` (`event_id`),
  UNIQUE KEY `uq_diagnosis_outbox_version` (`aggregate_ref`, `aggregate_version`, `event_type`),
  KEY `idx_diagnosis_outbox_dispatch` (`status`, `next_attempt_at_ms`, `lease_until_ms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 diagnosis 可靠事件发件箱';

CREATE TABLE `subscription_outbox` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'subscription 事件内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `event_id` VARCHAR(64) NOT NULL COMMENT '全局高熵事件标识',
  `aggregate_ref` VARCHAR(64) NOT NULL COMMENT '聚合公开引用',
  `aggregate_version` INT UNSIGNED NOT NULL COMMENT '聚合版本',
  `event_type` VARCHAR(96) NOT NULL COMMENT '版本化事件类型',
  `schema_version` VARCHAR(32) NOT NULL COMMENT '事件结构版本',
  `payload_json` JSON NOT NULL COMMENT '脱敏事件载荷',
  `payload_hash` CHAR(64) NOT NULL COMMENT '规范化载荷 SHA-256',
  `status` VARCHAR(24) NOT NULL COMMENT '状态：pending、dispatching、delivered、dead_letter',
  `lease_owner` VARCHAR(64) NULL COMMENT '当前派发租约持有者',
  `lease_until_ms` BIGINT UNSIGNED NULL COMMENT '租约失效时间，UTC 毫秒',
  `attempt_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '派发尝试次数',
  `next_attempt_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '下次派发时间，UTC 毫秒',
  `occurred_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '业务发生时间，UTC 毫秒',
  `delivered_at_ms` BIGINT UNSIGNED NULL COMMENT '成功投递时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_subscription_outbox_event` (`event_id`),
  UNIQUE KEY `uq_subscription_outbox_version` (`aggregate_ref`, `aggregate_version`, `event_type`),
  KEY `idx_subscription_outbox_dispatch` (`status`, `next_attempt_at_ms`, `lease_until_ms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 subscription 可靠事件发件箱';

CREATE TABLE `security_audit_records` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '安全审计记录内部主键',
  `_openid` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CloudBase 技术兼容字段，服务端表固定为空，不作为用户归属',
  `audit_ref` VARCHAR(64) NOT NULL COMMENT '高熵审计记录引用',
  `principal_type` VARCHAR(16) NOT NULL COMMENT '主体类型：guest、user、service',
  `principal_safe_ref` VARCHAR(64) NOT NULL COMMENT '脱敏主体引用，不含平台标识',
  `action` VARCHAR(96) NOT NULL COMMENT '受控动作代码',
  `object_type` VARCHAR(64) NOT NULL COMMENT '对象类型',
  `object_public_ref` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '对象公开引用，无对象时为空',
  `result` VARCHAR(24) NOT NULL COMMENT '结果：allowed、denied、failed',
  `reason_code` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '脱敏原因代码',
  `occurred_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '发生时间，UTC 毫秒',
  `created_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '创建时间，UTC 毫秒',
  `updated_at_ms` BIGINT UNSIGNED NOT NULL COMMENT '更新时间，UTC 毫秒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_security_audit_ref` (`audit_ref`),
  KEY `idx_security_audit_subject` (`principal_type`, `principal_safe_ref`, `occurred_at_ms`),
  KEY `idx_security_audit_object` (`object_type`, `object_public_ref`, `occurred_at_ms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='青花植 v2 脱敏安全审计记录';
