import { expect, test, vi } from 'vitest'
import type { UserRef, UserCapabilitySnapshotDto } from '../../src/contracts/types.js'
import { DatabaseCommitResultUnknownError } from '../../src/foundation/database/transaction-runner.js'
import { createGuestClaimCompletionApplicationService } from '../../src/user-plant/application/complete-guest-claim.js'

/** L1/unit_fake：独立应用合同；实际应用/事务Runner，替换驱动和Repository，真实SQL另验。 */
function input() { return { principal: { principalType: 'user' as const, user_id: 'usr_user00001' as UserRef, sessionVersion: 1, authenticatedVia: 'wechat' as const, issuedAt: '1970-01-01T00:00:00Z', expiresAt: '1970-01-01T00:00:10Z' }, proof: { guestSessionRef: 'gst_session01', possessionProof: 'p'.repeat(43), nowMs: 2000, proofRotationGraceSeconds: 300 }, guestPlantCaseRef: 'gpc_case00001', target: { type: 'existing_user_plant' as const, user_plant_id: 'upl_existing001' }, claimRef: 'gcl_claim0001', idempotencyKeyHash: 'b'.repeat(64), leaseOwnerHash: 'c'.repeat(64) } }
const capability: UserCapabilitySnapshotDto = { contractVersion: 'capability-snapshot/v1', snapshotRef: 'cps_claim_app001', subjectType: 'user', user_id: 'usr_user00001' as UserRef, tier: 'free', allowedCapabilities: ['USER_PLANT_CREATE'], rewardedAiScopes: [], activeUserPlantLimit: 1, generatedAt: '1970-01-01T00:00:01Z', validUntil: '1970-01-01T00:00:09Z', policyVersion: 'user-plant-limit/v1' }
const success = () => ({ status: 'completed' as const, claimRef: 'gcl_claim0001', userPlantRef: 'upl_existing001', guestPlantCaseRef: 'gpc_case00001', proofVersion: 1, claimedAtMs: 2000 })
function setup() {
 const tx = { transactionContext: true as const }
 const driver = { beginTransaction: vi.fn().mockResolvedValue(tx), commitTransaction: vi.fn().mockResolvedValue(undefined), rollbackTransaction: vi.fn().mockResolvedValue(undefined), recordRollbackFailure: vi.fn() }
 const existingRepository = { complete: vi.fn().mockResolvedValue(success()) }, newPlantRepository = { complete: vi.fn().mockResolvedValue({ ...success(), userPlantRef: 'upl_newplant001' }) }, completedReceiptReader = { readCompleted: vi.fn().mockResolvedValue(null) }
 const nowMs = vi.fn(() => 2100)
 return { driver, existingRepository, newPlantRepository, completedReceiptReader, tx, nowMs, app: createGuestClaimCompletionApplicationService({ driver, existingRepository, newPlantRepository, completedReceiptReader, nowMs }) }
}
test('已有目标只调用一次对应完成并提交后返回', async () => { const f = setup(), i = input(); expect(await f.app(i)).toEqual(success()); expect(f.existingRepository.complete).toHaveBeenCalledWith(f.tx, i); expect(f.newPlantRepository.complete).not.toHaveBeenCalled(); expect(f.driver.commitTransaction).toHaveBeenCalledOnce() })
test('新建目标消费新端口，原成功重放不依赖当前能力或候选', async () => {
 const f = setup(); f.completedReceiptReader.readCompleted.mockResolvedValue({ ...success(), claimRef: 'gcl_original001', userPlantRef: 'upl_original001', claimedAtMs: 1500 } as never); const i = { ...input(), target: { type: 'new_user_plant' as const }, newUserPlantRef: 'upl_newplant001', capabilitySnapshot: null }; expect(await f.app(i)).toEqual({ ...success(), claimRef: 'gcl_original001', userPlantRef: 'upl_original001', claimedAtMs: 1500 }); expect(f.driver.beginTransaction).not.toHaveBeenCalled(); expect(f.newPlantRepository.complete).not.toHaveBeenCalled()
})
test('新建首次调用新端口且只提交一次', async () => { const f = setup(), i = { ...input(), target: { type: 'new_user_plant' as const }, newUserPlantRef: 'upl_newplant001', capabilitySnapshot: capability }; expect(await f.app(i)).toEqual({ ...success(), userPlantRef: i.newUserPlantRef }); expect(f.newPlantRepository.complete).toHaveBeenCalledOnce(); expect(f.existingRepository.complete).not.toHaveBeenCalled(); expect(f.driver.commitTransaction).toHaveBeenCalledOnce() })
test.each(['unavailable', 'idempotency_conflict'] as const)('前置读取%s不得进入事务或写入', async status => { const f = setup(); f.completedReceiptReader.readCompleted.mockResolvedValue({ status } as never); expect(await f.app(input())).toEqual({ status }); expect(f.driver.beginTransaction).not.toHaveBeenCalled() })
test('前置读取技术故障没有写入重试', async () => { const f = setup(); f.completedReceiptReader.readCompleted.mockRejectedValue(new Error('受控故障')); expect(await f.app(input())).toEqual({ status: 'unavailable' }); expect(f.driver.beginTransaction).not.toHaveBeenCalled() })
test('提交未知只读核对完整原收据，不再完成或回滚', async () => { const f = setup(); f.driver.commitTransaction.mockRejectedValue(new DatabaseCommitResultUnknownError('受控未知提交')); f.completedReceiptReader.readCompleted.mockResolvedValueOnce(null).mockResolvedValueOnce(success() as never); expect(await f.app(input())).toEqual(success()); expect(f.existingRepository.complete).toHaveBeenCalledOnce(); expect(f.completedReceiptReader.readCompleted).toHaveBeenCalledTimes(2); expect(f.driver.rollbackTransaction).not.toHaveBeenCalled() })
test.each([null, { status: 'unavailable' }, { ...success(), proofVersion: 0 }, { ...success(), internalId: '8' }])('提交未知没有可靠完整收据时不可用%j', async receipt => { const f = setup(); f.driver.commitTransaction.mockRejectedValue(new DatabaseCommitResultUnknownError('受控未知提交')); f.completedReceiptReader.readCompleted.mockResolvedValueOnce(null).mockResolvedValueOnce(receipt as never); expect(await f.app(input())).toEqual({ status: 'unavailable' }); expect(f.existingRepository.complete).toHaveBeenCalledOnce(); expect(f.driver.beginTransaction).toHaveBeenCalledOnce(); expect(f.driver.rollbackTransaction).not.toHaveBeenCalled() })
test('完成存储不可用必须回滚，不能提交', async () => { const f = setup(); f.existingRepository.complete.mockResolvedValue({ status: 'unavailable' } as never); expect(await f.app(input())).toEqual({ status: 'unavailable' }); expect(f.driver.rollbackTransaction).toHaveBeenCalledOnce(); expect(f.driver.commitTransaction).not.toHaveBeenCalled() })
test.each([{ ...success(), claimRef: 'gcl_wrong0001' }, { ...success(), userPlantRef: 'upl_wrong0001' }, { ...success(), guestPlantCaseRef: 'gpc_wrong0001' }, { ...success(), claimedAtMs: 2001 }, { ...success(), proofVersion: 0 }, { ...success(), possessionProof: '禁止泄露' }])('拒绝错误或泄露结果并回滚%j', async result => { const f = setup(); f.existingRepository.complete.mockResolvedValue(result); await expect(f.app(input())).rejects.toThrow(); expect(f.driver.rollbackTransaction).toHaveBeenCalledOnce(); expect(f.driver.commitTransaction).not.toHaveBeenCalled() })
test('普通事务故障回滚且不进入未知核对或重试', async () => { const f = setup(); f.existingRepository.complete.mockRejectedValue(new Error('受控SQL错误')); await expect(f.app(input())).rejects.toThrow(); expect(f.driver.rollbackTransaction).toHaveBeenCalledOnce(); expect(f.completedReceiptReader.readCompleted).toHaveBeenCalledOnce(); expect(f.existingRepository.complete).toHaveBeenCalledOnce() })
test('等待时输入变更不能改变主体和原请求', async () => { const f = setup(), i = input(); f.completedReceiptReader.readCompleted.mockImplementationOnce(async () => { i.principal.user_id = 'usr_other0001' as UserRef; i.proof.nowMs = 9999; i.target.user_plant_id = 'upl_wrong0001'; return null }); expect(await f.app(i)).toEqual(success()); expect(f.existingRepository.complete.mock.calls[0]![1].principal.user_id).toBe('usr_user00001'); expect(f.existingRepository.complete.mock.calls[0]![1].proof.nowMs).toBe(2000) })
test('同键并发预读为空后案例被先完成，只读返回原成功不重写', async () => { const f = setup(); f.existingRepository.complete.mockResolvedValue({ status: 'not_claimable' } as never); f.completedReceiptReader.readCompleted.mockResolvedValueOnce(null).mockResolvedValueOnce({ ...success(), claimedAtMs: 1500 } as never); expect(await f.app(input())).toEqual({ ...success(), claimedAtMs: 1500 }); expect(f.existingRepository.complete).toHaveBeenCalledOnce(); expect(f.driver.beginTransaction).toHaveBeenCalledOnce(); expect(f.completedReceiptReader.readCompleted).toHaveBeenCalledTimes(2) })
test('确定拒绝后仍无本键成功，保留拒绝且没有第二次写入', async () => { const f = setup(); f.existingRepository.complete.mockResolvedValue({ status: 'not_claimable' } as never); expect(await f.app(input())).toEqual({ status: 'not_claimable' }); expect(f.completedReceiptReader.readCompleted).toHaveBeenCalledTimes(2); expect(f.existingRepository.complete).toHaveBeenCalledOnce() })

test('后续收据时间晚于请求捕获但不晚于当前可信读取时间时可以回放', async () => { const f = setup(); f.completedReceiptReader.readCompleted.mockResolvedValue({ ...success(), claimedAtMs: 2050 } as never); expect(await f.app(input())).toEqual({ ...success(), claimedAtMs: 2050 }); expect(f.completedReceiptReader.readCompleted.mock.calls[0]![0].nowMs).toBe(2100); expect(f.driver.beginTransaction).not.toHaveBeenCalled() })
test.each([1999, Number.NaN, 10000])('可信读取时钟倒退/失效/身份过期时零事务%s', async time => { const f = setup(); f.nowMs.mockReturnValue(time); expect(await f.app(input())).toEqual({ status: 'unavailable' }); expect(f.driver.beginTransaction).not.toHaveBeenCalled(); expect(f.completedReceiptReader.readCompleted).not.toHaveBeenCalled() })
