'use strict'

module.exports = [
  'problems',
  'symptoms',
  'symptom_classes',
  'symptom_class_mapping',
  'symptom_problem_evidence',
  'plant_identity_diagnosis_links',
  'genus_problem_profiles',
  'problem_host_profiles',
  'plant_problem_profiles',
  'problem_causality',
  'class_question_group_strategy',
  'question_library_v5_real',
  'question_option_mapping_v5_real',
  'question_strategy_v5_real',
  'question_generation_engine',
  'diagnosis_result_explanations',
  'outcome_route_groups',
  'outcome_routes',
  'outcome_route_gates',
  'outcome_route_questions',
  'outcome_answer_effects',
  'outcome_action_profiles',
  'diagnosis_outcomes',
  'visual_supervision_records',
  'visual_out_of_pool_candidate_reviews',
  'visual_out_of_pool_proxy_mappings',
  'question_queue',
  'stop_state'
]
